// ═══ NA TIER A TOP5_FOOD ═══

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── CHICAGO ─────────────────────────────────────────────────────────────────

export const TOP5_FOOD_CHICAGO: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "산수갑산",
    nameEn: "San Soo Gab San",
    address: "5247 N Western Ave, Chicago, IL 60625",
    phone: "(773) 334-1589",
    hours: "월-일 24시간",
    rating: 4.3,
    ratingCount: "1,000+",
    why: "🥩 BBQ·한식\n올버니파크 한인타운 로렌스 애비뉴 인근 24시간 운영 전설의 한식당. 숯불 갈비와 삼겹살이 대표 메뉴로 시카고 교민 30년 단골 1순위. 새벽에도 불이 꺼지지 않아 야근 후 한 잔 하러 오는 교민들의 아지트다.",
    tip: "심야 할인 없지만 24시간이라 언제든 OK. 주차는 Western Ave 노상",
    website: "yelp.com/biz/san-soo-gab-san-chicago",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "조선옥",
    nameEn: "Cho Sun Ok",
    address: "4200 N Lincoln Ave, Chicago, IL 60618",
    phone: "(773) 549-5555",
    hours: "화-일 11:30am-10pm, 월 휴무",
    rating: 4.4,
    ratingCount: "800+",
    why: "🍲 갈비·냉면\n린컨스퀘어에 자리한 시카고 최고의 한식 명가. 뼈 붙은 LA 갈비와 물냉면은 시카고 한인이라면 한 번쯤 꼭 먹어봤을 메뉴. 한식 특유의 정갈한 반찬 구성이 서울 내 노포 느낌을 그대로 살렸다.",
    tip: "저녁 주말 예약 필수. 냉면은 여름철 특히 인기 폭발",
    website: "chosunokchicago.com",
  },
  {
    rank: 3,
    emoji: "🍗",
    nameKo: "크리스프",
    nameEn: "Crisp",
    address: "2940 N Broadway St, Chicago, IL 60657",
    phone: "(773) 697-7610",
    hours: "월-토 11am-9pm, 일 11am-8pm",
    rating: 4.5,
    ratingCount: "1,200+",
    why: "🍗 한국식 치킨·비빔밥\n시카고에서 한국식 프라이드치킨을 처음 알린 선구자. 겉바속촉 서울 치킨(Seoul Bird)은 현지인·교민 모두 열광하는 메뉴. 비빔밥과 곁들여 먹으면 점심 한 끼가 완벽하다.",
    tip: "치킨버거 'CB' 메뉴 강력 추천. 웨이팅 30분은 각오할 것",
    website: "crispchicago.com",
  },
  {
    rank: 4,
    emoji: "🥣",
    nameKo: "BCD 두부집 시카고",
    nameEen: "BCD Tofu House Chicago",
    address: "5334 N Lincoln Ave, Chicago, IL 60625",
    phone: "(773) 275-2227",
    hours: "월-일 11am-11pm",
    rating: 4.2,
    ratingCount: "600+",
    why: "🥣 순두부·한정식\n로렌스 애비뉴 한인타운 한복판의 순두부 전문점. 얼큰한 순두부찌개 한 그릇이면 시카고 추위가 싹 달아난다. 전국 체인이지만 이 곳 순두부는 재료가 신선하고 양이 푸짐해 교민들의 신뢰가 두텁다.",
    tip: "런치 세트 $12 내외. 순두부 맵기는 '중간'이 교민 추천 레벨",
    website: "bcdtofuhouse.com",
  },
  {
    rank: 5,
    emoji: "🫕",
    nameKo: "프렌드십 레스토랑",
    nameEn: "Friendship Restaurant",
    address: "4647 N Kedzie Ave, Chicago, IL 60625",
    phone: "(773) 583-5999",
    hours: "화-일 11am-9:30pm, 월 휴무",
    rating: 4.1,
    ratingCount: "350+",
    why: "🫕 가정식·백반\n올버니파크 교민들이 어머니 밥상처럼 찾는 오래된 한식 가정식집. 된장찌개·제육볶음·김치찜 같은 집밥 메뉴를 합리적인 가격에 즐길 수 있다. 인테리어는 소박하지만 맛만큼은 진심이라 주말마다 빈 자리가 없다.",
    tip: "점심 백반 $10 내외. 현금 결제 시 소폭 할인",
  },
];

// ─── WASHINGTON DC ────────────────────────────────────────────────────────────

export const TOP5_FOOD_DC: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "허니 피그",
    nameEn: "Honey Pig",
    address: "4710 Annandale Rd, Annandale, VA 22003",
    phone: "(703) 256-5229",
    hours: "월-일 24시간",
    rating: 4.3,
    ratingCount: "2,500+",
    why: "🥩 BBQ·삼겹살\n애나데일 '리틀서울' 한복판 24시간 한국식 BBQ의 대명사. 두꺼운 삼겹살과 갈비를 직접 구워 먹는 방식에 현지인·교민 모두 줄을 선다. DC 메트로 한인 9만 3천 명이 한 번쯤은 방문하는 교민 1번지 식당.",
    tip: "새벽 1-4시 웨이팅이 오히려 적다. 직원에게 된장찌개 무료 추가 요청 가능",
    website: "honeypigbbq.com",
  },
  {
    rank: 2,
    emoji: "🍜",
    nameKo: "매향 한식당",
    nameEn: "Maehyang Korean Restaurant",
    address: "7040 Little River Tpke, Annandale, VA 22003",
    phone: "(703) 941-3737",
    hours: "월-토 11am-10pm, 일 11am-9pm",
    rating: 4.4,
    ratingCount: "700+",
    why: "🍜 한정식·갈비탕\n애나데일 한식 명가로 갈비탕과 설렁탕이 특히 유명하다. 이른 아침부터 문을 열어 출근 전 뜨끈한 국밥 한 그릇 하려는 교민들의 발길이 끊이지 않는다. 깔끔하고 진한 사골 육수가 서울 종로 설렁탕 골목 느낌이다.",
    tip: "국물류는 오전이 더 맛있다. 주차장 넓어 가족 모임 적합",
  },
  {
    rank: 3,
    emoji: "🌮",
    nameKo: "타코리안 애나데일",
    nameEn: "Takorean Annandale",
    address: "7261 Little River Tpke, Annandale, VA 22003",
    phone: "(703) 256-8800",
    hours: "월-토 11am-9pm, 일 12pm-8pm",
    rating: 4.2,
    ratingCount: "500+",
    why: "🌮 퓨전 한식·타코\n한국 BBQ 재료로 만든 타코라는 독특한 콘셉트로 교민 2세와 현지인 모두를 사로잡은 곳. 불고기 타코와 비빔밥 볼은 한식을 모르는 직장 동료에게 소개하기 딱 좋은 메뉴. 애나데일 한인타운에서 가장 세련된 공간이다.",
    tip: "런치 2타코+음료 콤보 $13. 온라인 사전 주문 시 웨이팅 없음",
    website: "takorean.com",
  },
  {
    rank: 4,
    emoji: "🥘",
    nameKo: "서울 가든 애나데일",
    nameEn: "Seoul Garden Annandale",
    address: "4501 John Marr Dr, Annandale, VA 22003",
    phone: "(703) 354-1040",
    hours: "월-일 11am-10:30pm",
    rating: 4.1,
    ratingCount: "900+",
    why: "🥘 BBQ·해물탕\n25년 이상 애나데일을 지킨 교민 단골 BBQ 식당. 해물파전과 해물탕도 함께 즐길 수 있어 주말 가족 외식지로 최고다. 테이블마다 숯불 화로가 있어 직화 구이를 즐기는 정통 한국식 BBQ 경험을 선사한다.",
    tip: "주말 저녁 예약 권장. 모둠 고기 2인 세트 $55 가성비 탁월",
  },
  {
    rank: 5,
    emoji: "🍱",
    nameKo: "하나 한식당",
    nameEn: "Hana Korean Restaurant",
    address: "11048 Veirs Mill Rd, Wheaton, MD 20902",
    phone: "(301) 949-1416",
    hours: "화-일 11:30am-9:30pm, 월 휴무",
    rating: 4.3,
    ratingCount: "450+",
    why: "🍱 한정식·가정식\n록빌·위튼 MD 코리아타운 교민들이 오래 사랑해온 가정식 전문점. 제철 재료로 만든 반찬과 깔끔한 찌개류가 일품이며, 어버이날·추석 등 명절 때는 예약 없이는 자리 잡기 힘들 정도로 붐빈다.",
    tip: "런치 정식 $16. 사전 전화 예약 권장 (영어·한국어 모두 OK)",
  },
];

// ─── SAN DIEGO ───────────────────────────────────────────────────────────────

export const TOP5_FOOD_SANDIEGO: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "호도리 코리안 BBQ",
    nameEn: "Hodori Korean BBQ",
    address: "4645 Convoy St, San Diego, CA 92111",
    phone: "(858) 576-7655",
    hours: "월-일 11am-11pm",
    rating: 4.3,
    ratingCount: "1,100+",
    why: "🥩 BBQ·한식\n콘보이 스트리트 한인타운의 대표 BBQ 식당으로 교민과 현지인이 함께 즐기는 명소. 두꺼운 차돌박이와 항정살이 인기 메뉴이며 연기 배출 시스템이 잘 되어 있어 쾌적하게 식사할 수 있다. 20년 이상 콘보이 거리를 지켜온 터줏대감이다.",
    tip: "방문 전 Yelp 예약 권장. 2인 모둠 구성이 가장 합리적",
    website: "yelp.com/biz/hodori-korean-bbq-san-diego",
  },
  {
    rank: 2,
    emoji: "🥣",
    nameKo: "두부집 콘보이",
    nameEn: "Tofu House Convoy",
    address: "4620 Convoy St, Ste 104, San Diego, CA 92111",
    phone: "(858) 571-8636",
    hours: "월-일 11am-10pm",
    rating: 4.4,
    ratingCount: "800+",
    why: "🥣 순두부·한정식\n콘보이 한식 거리에서 순두부 하면 이 곳이 1번. 직접 만든 연두부가 들어간 순두부찌개는 부드럽고 진한 맛이 서울 강남 두부집 수준이다. 점심 식사 후 녹차 아이스크림 서비스가 교민들에게 호평받는 작은 배려다.",
    tip: "비건 옵션 있음. 두부 맵기는 3단계 중 선택 가능",
  },
  {
    rank: 3,
    emoji: "🍖",
    nameKo: "참숯갈비",
    nameEn: "Charcoal Galbi Korean BBQ",
    address: "4690 Convoy St, San Diego, CA 92111",
    phone: "(858) 278-2224",
    hours: "월-일 11:30am-10:30pm",
    rating: 4.2,
    ratingCount: "650+",
    why: "🍖 참숯 갈비·특수부위\n콘보이에서 참숯 직화 갈비를 가장 잘 하는 집으로 교민들 사이에서 정평이 나있다. 사전에 숙성된 LA갈비와 생 갈비를 모두 즐길 수 있으며, 깊은 숯향이 배어든 고기 맛이 압권이다.",
    tip: "냉면 추가 주문 강력 추천. 주차는 건물 뒤편 무료",
  },
  {
    rank: 4,
    emoji: "🫕",
    nameKo: "서울 한식당",
    nameEn: "Seoul Korean Restaurant",
    address: "4474 Convoy St, San Diego, CA 92111",
    phone: "(858) 268-7700",
    hours: "월-토 10:30am-9:30pm, 일 11am-9pm",
    rating: 4.3,
    ratingCount: "500+",
    why: "🫕 가정식·해장국\n콘보이 가장 오래된 한식당 중 하나로 해장국과 갈비탕이 주력. 이른 아침부터 문을 열어 주말 해장을 원하는 교민들의 발길이 잦다. 진한 사골 육수에 우거지가 듬뿍 들어간 해장국 한 그릇이면 전날 피로가 말끔히 풀린다.",
    tip: "오전 10:30 오픈과 동시에 방문하면 웨이팅 없음. 뚝배기 해장국 $15",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "면상 콘보이",
    nameEn: "Myeon Sang Noodle House",
    address: "4656 Convoy St, Ste 102, San Diego, CA 92111",
    phone: "(858) 715-9700",
    hours: "월-일 11am-9:30pm",
    rating: 4.5,
    ratingCount: "900+",
    why: "🍜 냉면·칼국수\n콘보이에서 면 요리만큼은 단연 최고라는 평가를 받는 집. 함흥식 회냉면과 비빔냉면, 사골 칼국수가 시그니처이며 여름 시즌에는 냉면 웨이팅이 30분 이상 발생할 정도로 인기다. 교민 2세들도 즐겨 찾는 세련된 분위기가 장점이다.",
    tip: "회냉면은 꼭 반반(비빔+물) 섞어 달라고 해볼 것. 칼국수는 매주 금-일만 판매",
    website: "yelp.com/biz/myeon-sang-san-diego",
  },
];

// ─── HONOLULU ─────────────────────────────────────────────────────────────────

export const TOP5_FOOD_HONOLULU: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "서울 가든 하와이",
    nameEn: "Seoul Garden Hawaii",
    address: "500 Ala Moana Blvd, Ste 6, Honolulu, HI 96813",
    phone: "(808) 591-2900",
    hours: "월-일 11am-10pm",
    rating: 4.3,
    ratingCount: "700+",
    why: "🥩 BBQ·한정식\n알라모아나 센터 인근 호놀룰루 교민의 대표 BBQ 식당. 하와이 특산 재료와 결합한 한국식 BBQ가 현지인과 관광객에게도 인기가 높다. 바다 내음을 맡으며 갈비를 구워 먹는 이 곳만의 하와이 한식 경험이 특별하다.",
    tip: "바다 전망 좌석 요청 가능. 하와이 전복(아발로니) 추가 구이 강력 추천",
    website: "seoulgardenhawaii.com",
  },
  {
    rank: 2,
    emoji: "🍗",
    nameKo: "시스터즈 코리안 BBQ",
    nameEn: "Sisters Korean BBQ",
    address: "747 Keeaumoku St, Honolulu, HI 96814",
    phone: "(808) 952-5959",
    hours: "월-일 11am-11pm",
    rating: 4.4,
    ratingCount: "1,000+",
    why: "🍗 BBQ·치킨\n키아우모쿠 스트리트 한식 클러스터의 중심 맛집. 두 자매가 운영하는 이 집은 한국식 치킨과 삼겹살이 트레이드마크. 하와이 교민 커뮤니티가 연말 모임 장소로 즐겨 찾는 곳으로 항상 활기차고 따뜻한 분위기가 넘친다.",
    tip: "키즈 메뉴 있음. 치킨 2인 세트 $35로 가성비 최고",
    website: "sisterskoreanbbq.com",
  },
  {
    rank: 3,
    emoji: "🥣",
    nameKo: "윤's 한식",
    nameEn: "Yoon's Korean Restaurant",
    address: "720 Keeaumoku St, Ste 101, Honolulu, HI 96814",
    phone: "(808) 946-1777",
    hours: "월-토 10:30am-9pm, 일 11am-8pm",
    rating: 4.2,
    ratingCount: "400+",
    why: "🥣 가정식·순두부\n키아우모쿠 거리 교민들이 '단골 가정식'으로 꼽는 소박하고 따뜻한 집. 순두부찌개와 갈비탕이 인기 메뉴로 하와이 특유의 열대 날씨에도 뜨끈한 국물 한 그릇이 그리운 교민들의 쉼터 역할을 한다.",
    tip: "런치 세트 $14. 주차는 건물 지하 무료 (2시간)",
  },
  {
    rank: 4,
    emoji: "🍖",
    nameKo: "하와이 갈비",
    nameEn: "Hawaii Galbi Korean BBQ",
    address: "615 Keeaumoku St, Honolulu, HI 96814",
    phone: "(808) 943-0600",
    hours: "화-일 11am-10pm, 월 휴무",
    rating: 4.1,
    ratingCount: "550+",
    why: "🍖 갈비·한식\n30년 역사의 호놀룰루 교민 터줏대감 갈비집. 하와이식으로 손질된 LA갈비는 육즙이 풍부하고 양념이 진해 밥 한 공기가 순식간에 사라진다. 하와이 한인 1세 어르신들이 '고향 갈비 맛'이라고 칭찬하는 집이다.",
    tip: "갈비 마리네이드는 24시간 숙성. 오픈 직후 방문하면 가장 신선한 고기를 맛볼 수 있다",
  },
  {
    rank: 5,
    emoji: "🍱",
    nameKo: "코리안 키친",
    nameEn: "Korean Kitchen Honolulu",
    address: "850 Kapahulu Ave, Honolulu, HI 96816",
    phone: "(808) 737-8765",
    hours: "월-일 10am-9pm",
    rating: 4.0,
    ratingCount: "300+",
    why: "🍱 백반·분식\n카파훌루 애비뉴에서 교민과 현지 한식 팬들이 함께 즐기는 가성비 백반집. 김치찌개·된장찌개·불고기 정식 등 기본 한식을 저렴하게 즐길 수 있어 유학생과 젊은 교민들에게 인기가 높다. 하와이에서 가장 저렴한 한식 정식을 찾는다면 이 곳이다.",
    tip: "테이크아웃 할인 10%. 현금 결제 선호",
  },
];

// ─── PORTLAND ─────────────────────────────────────────────────────────────────

export const TOP5_FOOD_PORTLAND: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥣",
    nameKo: "BCD 두부집 포틀랜드",
    nameEn: "BCD Tofu House Portland",
    address: "4434 SW 109th Ave, Beaverton, OR 97005",
    phone: "(503) 641-6377",
    hours: "월-일 11am-10:30pm",
    rating: 4.3,
    ratingCount: "800+",
    why: "🥣 순두부·한정식\n비버튼 한인 커뮤니티의 중심 순두부 전문점. 비버튼은 포틀랜드 메트로 내 한인 밀집 지역으로 이 집 순두부찌개는 교민들의 주말 외식 1순위다. 진한 조개 육수 베이스에 신선한 순두부가 가득해 한 그릇이 뚝딱이다.",
    tip: "런치 특선 $13. 모둠 순두부 2인 세트 추천",
    website: "bcdtofuhouse.com",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "강원 BBQ",
    nameEn: "Gangwon BBQ Beaverton",
    address: "10600 SW Canyon Rd, Beaverton, OR 97005",
    phone: "(503) 526-9226",
    hours: "화-일 11:30am-10pm, 월 휴무",
    rating: 4.4,
    ratingCount: "600+",
    why: "🥩 BBQ·갈비\n비버튼 한인 교민들이 가장 사랑하는 참숯 BBQ 전문점. 강원도식 황태 계란탕 서비스와 함께 나오는 고기 구이가 일품이다. 나이키·인텔 본사 인근 한인 직장인들이 야근 후 퇴근길에 자주 들른다.",
    tip: "황태 계란탕은 무한 리필. 고기는 미디엄 익히면 육즙 최대",
  },
  {
    rank: 3,
    emoji: "🌿",
    nameKo: "차야 포틀랜드",
    nameEn: "Cha Ya Portland",
    address: "6635 SE Milwaukie Ave, Portland, OR 97202",
    phone: "(503) 234-1242",
    hours: "화-일 5pm-9:30pm, 월 휴무",
    rating: 4.5,
    ratingCount: "900+",
    why: "🌿 비건 한식·사찰음식\n포틀랜드 SE 지역의 비건 한식·일식 퓨전 레스토랑. 교민 2세와 비건 성향의 현지인들이 즐겨 찾으며 사찰음식 스타일로 만든 비건 된장국과 나물 정식이 시그니처다. 한식의 건강함을 현지 감각으로 재해석한 독특한 경험이다.",
    tip: "저녁만 운영, 예약 필수. 비건이 아니더라도 맛에 놀라게 되는 집",
    website: "chayaportland.com",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "한양 식당",
    nameEn: "Hanyang Korean Restaurant",
    address: "3830 SW 117th Ave, Beaverton, OR 97005",
    phone: "(503) 643-3737",
    hours: "월-토 11am-9pm, 일 11am-8:30pm",
    rating: 4.2,
    ratingCount: "400+",
    why: "🍜 가정식·해장국\n비버튼 교민 가족들이 오래 다녀온 소박한 가정식 식당. 설렁탕·해장국·비빔밥 등 기본 메뉴를 정직한 가격에 즐길 수 있다. 교민 어르신들이 오래 사랑해온 집으로 식당 안에 들어서면 고향 밥집 냄새가 그대로 난다.",
    tip: "주말 점심 웨이팅 20분 예상. 설렁탕+반찬 구성이 $14로 가성비 최고",
  },
  {
    rank: 5,
    emoji: "🍗",
    nameKo: "치킨 마루 비버튼",
    nameEen: "Chicken Maru Beaverton",
    address: "12345 SW Canyon Rd, Beaverton, OR 97005",
    phone: "(503) 617-7777",
    hours: "월-일 11am-10pm",
    rating: 4.1,
    ratingCount: "350+",
    why: "🍗 한국식 치킨·맥주\n비버튼 한인타운 치맥의 대표 주자. 바삭한 한국식 양념치킨과 간장치킨을 지역 크래프트 맥주와 함께 즐길 수 있다. 퇴근 후 가볍게 치킨 한 마리 뜯으며 수다 떠는 교민 모임 장소로 인기가 높다.",
    tip: "반반(양념+간장) 주문이 정석. 대기 없이 먹으려면 평일 오후 6시 이전 방문 추천",
  },
];

// ─── DENVER ───────────────────────────────────────────────────────────────────

export const TOP5_FOOD_DENVER: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "서라벌 BBQ 오로라",
    nameEn: "Seorabeol Korean BBQ Aurora",
    address: "2620 S Parker Rd, Ste 1, Aurora, CO 80014",
    phone: "(303) 745-9292",
    hours: "월-일 11am-10:30pm",
    rating: 4.4,
    ratingCount: "900+",
    why: "🥩 BBQ·한식\n오로라 한인 커뮤니티 대표 BBQ 식당으로 하바나 스트리트 인근 교민들의 단골 1번지. 두꺼운 삼겹살과 LA갈비가 주력 메뉴이며 제대로 된 연기 환기 시스템이 갖춰져 쾌적하게 BBQ를 즐길 수 있다. 덴버 한인 모임의 필수 코스다.",
    tip: "대형 단체석 있어 교회 모임·동창회 활용 가능. 사전 예약 권장",
    website: "yelp.com/biz/seorabeol-korean-bbq-aurora",
  },
  {
    rank: 2,
    emoji: "🥣",
    nameKo: "진한 순두부",
    nameEn: "Jinha Sundubu Aurora",
    address: "9555 E Colfax Ave, Aurora, CO 80010",
    phone: "(720) 535-8880",
    hours: "화-일 11am-9:30pm, 월 휴무",
    rating: 4.3,
    ratingCount: "500+",
    why: "🥣 순두부·한정식\n오로라 한인타운 이스트 콜팩스 애비뉴에 자리한 순두부 전문점. 콜로라도 고원 기후 특성상 뜨끈한 순두부찌개 한 그릇이 특히 맛있게 느껴진다. 교민들은 이 집을 '고산지대 최고의 따뜻한 식사'라고 부른다.",
    tip: "순두부 칼칼한 맛이 특징. 고추장 추가는 무료로 요청 가능",
  },
  {
    rank: 3,
    emoji: "🍖",
    nameKo: "오로라 갈비집",
    nameEn: "Aurora Galbi House",
    address: "13761 E Mississippi Ave, Aurora, CO 80012",
    phone: "(303) 751-8888",
    hours: "월-토 11:30am-9:30pm, 일 12pm-9pm",
    rating: 4.2,
    ratingCount: "400+",
    why: "🍖 갈비·해물탕\n오로라 미시시피 애비뉴 교민 상권의 핵심 갈비 전문점. 24시간 숙성 LA갈비와 생갈비를 모두 즐길 수 있으며, 해물탕 주문 시 푸짐한 해산물이 들어가 2인 이상 모임에 최적이다. 덴버 대학교 한인 유학생들의 특별 외식 장소이기도 하다.",
    tip: "갈비+해물탕 조합이 2인 황금 세트. 주차장 넉넉함",
  },
  {
    rank: 4,
    emoji: "🫕",
    nameKo: "서울 식당 오로라",
    nameEn: "Seoul Restaurant Aurora",
    address: "14211 E Jewell Ave, Aurora, CO 80012",
    phone: "(303) 617-9000",
    hours: "월-토 10:30am-9pm, 일 11am-8:30pm",
    rating: 4.1,
    ratingCount: "350+",
    why: "🫕 가정식·백반\n오로라 교민 가족들이 매주 찾는 정직한 가정식 식당. 된장찌개·김치찌개·제육볶음 등 집밥 같은 메뉴를 합리적인 가격에 즐길 수 있다. 덴버 교민 커뮤니티에서 '어머니 밥상'이라는 애칭으로 불리는 곳이다.",
    tip: "점심 백반 $13. 포장 주문 시 반찬 추가 가능",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "H마트 푸드코트 덴버",
    nameEen: "H Mart Food Court Denver",
    address: "2770 S Havana St, Aurora, CO 80014",
    phone: "(303) 751-7900",
    hours: "월-일 9am-9pm",
    rating: 4.0,
    ratingCount: "600+",
    why: "🍜 분식·한식 코너\nH마트 덴버·오로라점 내 푸드코트는 교민들의 일상 식사 해결사. 떡볶이·순대·김밥·라면 등 분식부터 찌개류까지 다양한 한식 옵션이 한 자리에 모여있다. 장보기와 식사를 한 번에 해결할 수 있어 가족 단위 방문이 많다.",
    tip: "오전 오픈과 함께 방문 시 가장 신선. 주말 점심 시간대는 혼잡",
    website: "hmart.com",
  },
];
