// ═══ VERIFIED EUROPE + DUBAI (from Korean media directories) ═══
// 출처: TripAdvisor, Yelp, 공식 웹사이트, berlinreport.com, gulfkoreantimes.net 교차 검증
// 검증일: 2026-05-14

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── LONDON (New Malden Korea Town) ───────────────────────────────────────────
const TOP5_FOOD_LONDON: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍲",
    nameKo: "이모네",
    nameEn: "Imone",
    address: "169 High Street, New Malden KT3 4BH",
    phone: "+44 20 8942 9588",
    hours: "화-일 12:00-22:00, 월 휴무",
    rating: 4.3,
    ratingCount: "47+",
    why: "뉴몰든 하이스트리트의 소박한 6테이블 가정식 맛집. 불고기·순두부찌개·파전이 본고장 맛 그대로이며 반찬과 김치가 무제한으로 제공됩니다. 현지 교민들이 '런던 최고의 한식'으로 꼽는 곳으로, 인포메이션 더 인파추에이션(The Infatuation)도 극찬한 작은 명소입니다.",
    tip: "테이블이 6개뿐이라 예약 필수. 파전이 런던에서 손꼽히는 수준.",
    website: "imonelondon.com",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "진고개",
    nameEn: "Jin Go Gae",
    address: "272 Burlington Road, New Malden KT3 4NL",
    phone: "+44 20 8949 2506",
    hours: "정보 직접 확인 권장",
    rating: 4.0,
    ratingCount: "330+",
    why: "뉴몰든 대표 숯불 한국식 바비큐 전문점. 트립어드바이저 뉴몰든 맛집 7위, 페이스북 92% 추천률의 정통 BBQ 맛집입니다. 삼겹살·갈비를 직접 구워먹는 경험을 제공하며 교민·관광객 모두에게 사랑받습니다.",
    tip: "인기가 많아 예약 필수. 하이스트리트에서 버링턴 로드로 살짝 들어가야 찾을 수 있음.",
    website: "jingogae.wordpress.com",
  },
  {
    rank: 3,
    emoji: "🍜",
    nameKo: "유미 한식당",
    nameEn: "You Me Korean Restaurant",
    address: "96 Burlington Road, New Malden KT3 4NT",
    phone: "+44 20 8715 1079",
    hours: "월·화 휴무, 수-일 12:00-15:00, 17:30-22:00",
    rating: 4.4,
    ratingCount: "51+",
    why: "1988년 개업, 35년 역사의 뉴몰든 최장수 한식당. 직접 반죽하는 자장면, 만두, 오색 비빔밥이 시그니처 메뉴입니다. 푸근한 주인 부부의 환대와 가정식 맛이 교민들에게 '고향 식당'으로 통합니다.",
    tip: "자장면은 이곳 특제 흑두장 소스로 수제 제조. 대가족 방문 시 미리 예약.",
  },
  {
    rank: 4,
    emoji: "🌶️",
    nameKo: "하루 레스토랑",
    nameEn: "Haru Restaurant",
    address: "50 High Street, New Malden KT3 4EZ",
    phone: "+44 20 8001 2512",
    hours: "12:00-22:00",
    rating: 4.2,
    ratingCount: "48+",
    why: "뉴몰든 하이스트리트의 캐주얼 한식당으로, 파전·해물파전·비빔면 등 다양한 홈스타일 한국 요리를 합리적인 가격에 제공합니다. 처음 방문하는 분들에게 첫 한식 체험 장소로 적합합니다.",
    tip: "파전과 해물 요리가 특히 추천. 저녁 시간 붐비므로 일찍 방문 권장.",
  },
  {
    rank: 5,
    emoji: "🥘",
    nameKo: "서울맛집",
    nameEn: "Seoul Matjib",
    address: "74 Burlington Road, New Malden KT3 4NU",
    phone: "+44 20 8942 0682",
    hours: "정보 직접 확인 권장",
    rating: 4.5,
    ratingCount: "2+",
    why: "현지 교민들이 자주 찾는 순대국밥 전문점. 순대볶음·순대전골·보쌈 등 술안주·가정식이 주 메뉴로, 소주 한 잔과 함께 즐기는 정통 한국 밤문화 분위기를 뉴몰든에서 경험할 수 있습니다. 한국인 손님 비율이 높아 현지 교민 검증 맛집.",
    tip: "교민들이 자주 찾는 조용한 단골 식당. 순대국밥이 시그니처.",
  },
];

// ─── FRANKFURT ────────────────────────────────────────────────────────────────
const TOP5_FOOD_FRANKFURT: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍱",
    nameKo: "소나무",
    nameEn: "Sonamu",
    address: "Berger Straße 184, 60385 Frankfurt am Main",
    phone: "+49 69 90437250",
    hours: "월 휴무, 화-일 12:00-23:00",
    rating: 4.3,
    ratingCount: "264+",
    why: "프랑크푸르트 한식 맛집 1위(트립어드바이저 #83/2636). '캐주얼 코리안 다이닝'을 표방하며 비빔밥·불고기·쌈밥을 현대적인 감각의 공간에서 제공합니다. 독일인·관광객·교민 모두에게 검증된 264개 리뷰의 명실상부 프랑크푸르트 대표 한식당입니다.",
    tip: "저녁은 예약 필수. 베르거슈트라세 트렌디 지역에 위치해 식사 후 산책하기 좋음.",
    website: "sonamu-frankfurt.de",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "한국 레스토랑 미스터 리",
    nameEn: "Mr. Lee",
    address: "Gutleutstraße 153, 60327 Frankfurt am Main",
    phone: "+49 69 251198",
    hours: "월-금 11:30-14:30, 17:30-22:30, 토-일 휴무",
    rating: 4.3,
    ratingCount: "97+",
    why: "프랑크푸르트 중앙역 인근의 정통 한식당(트립어드바이저 #267/2130). 비빔밥·불고기·된장찌개 등 클래식 한식을 정직한 가격에 제공해 출장객과 교민 모두에게 사랑받는 곳입니다. 교민 커뮤니티에서 '진짜 한국 맛'으로 인정받은 식당.",
    tip: "중앙역 도보 10분 거리. 점심 런치 세트가 가성비 최고. 예약 권장.",
  },
  {
    rank: 3,
    emoji: "🍖",
    nameKo: "한국",
    nameEn: "Hankook",
    address: "Hainer Weg 100, 60599 Frankfurt am Main",
    phone: "+49 69 65007185",
    hours: "월-토 12:00-14:30, 18:00-22:30, 일 휴무",
    rating: 3.8,
    ratingCount: "140+",
    why: "자흐센하우젠 지역의 한국 바비큐 전문점. 불고기·삼겹살을 테이블 그릴에서 직접 구워먹는 경험을 제공하며, 교민 사이에서 '본토 맛에 가장 가깝다'는 평가를 받습니다. 200장의 사진이 올라온 Yelp 현지 인기 맛집.",
    tip: "저녁 식사는 예약 필수. 삼겹살 세트와 된장찌개 조합 추천.",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "서울푸드",
    nameEn: "SEOULFOOD Korean Food",
    address: "Weserstraße 17, 60329 Frankfurt am Main",
    phone: "+49 69 20168645",
    hours: "매일 12:00-21:30",
    rating: 3.7,
    ratingCount: "87+",
    why: "반호프스피어텔(역세권) 지역의 아담한 한식당으로 돌솥비빔밥·불고기·김치전·만두·떡볶이를 건강하게 제공합니다. 채식·비건 옵션도 있어 다양한 식성의 손님을 아우릅니다. 리퍼란도 배달 가능.",
    tip: "소규모 식당이라 자리가 금방 차므로 일찍 방문. 돌솥비빔밥이 시그니처.",
    website: "seoulfood.eu",
  },
  {
    rank: 5,
    emoji: "🔥",
    nameKo: "강남",
    nameEn: "Gangnam",
    address: "Stiftstraße 6, 60313 Frankfurt am Main",
    phone: "+49 69 78080071",
    hours: "정보 직접 확인 권장",
    rating: 3.6,
    ratingCount: "12+",
    why: "프랑크푸르트 시내(자일 쇼핑가 인근)에 위치한 한국 BBQ 뷔페. 1인당 18.80유로의 무제한 삼겹살·양념 소갈비 뷔페를 제공해 저렴하게 한식 BBQ를 경험할 수 있습니다. 관광객과 학생들에게 가성비 좋은 선택지.",
    tip: "BBQ 뷔페 가성비 최고. 시내 쇼핑 후 저녁으로 방문하기 좋은 위치.",
  },
];

// ─── BERLIN ───────────────────────────────────────────────────────────────────
const TOP5_FOOD_BERLIN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🌿",
    nameKo: "남산 베를린",
    nameEn: "Namsan Berlin",
    address: "Chamissoplatz 1, 10965 Berlin",
    phone: "+49 30 499 07172",
    hours: "화-토 17:30-22:30, 일 17:00-22:00, 월 휴무",
    rating: 5.0,
    ratingCount: "4+",
    why: "베를린 크로이츠베르크의 한국 레스토랑 & 와인바로 구글 평점 4.9를 기록한 신흥 명소입니다. 자연 와인과 전통 한국 요리를 페어링하는 현대적 감각의 다이닝으로 베를린 식도락가들 사이에서 화제가 되고 있습니다.",
    tip: "소규모 식당이라 예약 필수(app.resmio.com). 와인 페어링 코스 추천.",
    website: "namsanberlin.de",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "미담 한국 바비큐",
    nameEn: "MIDAM Korean BBQ",
    address: "Stuttgarter Platz 28, 10627 Berlin",
    phone: "+49 30 6958 8817",
    hours: "월-목 12:00-23:00, 금-토 12:00-24:00, 일 12:00-22:00",
    rating: 4.3,
    ratingCount: "200+",
    why: "'아름다운 이야기'라는 뜻의 미담은 샤를로텐부르크 지역 2층 규모의 한국 바비큐 레스토랑입니다. USDA 인증 미국산 소고기를 숯불에 구워먹는 정통 한국 BBQ 경험을 제공하며, 야외 테라스와 프라이빗 룸도 갖추고 있습니다.",
    tip: "예약은 reservation@midam-berlin.com으로. 소고기 혼합 플래터 추천. 단체 이벤트 가능.",
    website: "midam-berlin.com",
  },
  {
    rank: 3,
    emoji: "🍶",
    nameKo: "도토리 코리안 안주 바",
    nameEn: "Dotori Korean Anju Bar",
    address: "Gustav-Adolf-Straße 159, 13086 Berlin",
    phone: "+49 30 4737 5630",
    hours: "목-일 18:00-23:00, 월-수 휴무",
    rating: 4.1,
    ratingCount: "7+",
    why: "바이센제(Weißensee) 지역의 전통 한국 안주 전문 바. 자연 와인·막걸리와 함께 보쌈·해물파전·만두를 나눠먹는 따뜻한 분위기의 한국식 선술집입니다. 1인 49유로의 아주마 세트 메뉴가 인기로, 채식 메뉴도 제공합니다.",
    tip: "목요일이 가장 한산함. 세트 메뉴로 다양한 안주 경험 추천. 예약 필수.",
    website: "dotori.berlin",
  },
  {
    rank: 4,
    emoji: "🍣",
    nameKo: "서울 키친 BBQ & 스시",
    nameEn: "Seoul Kitchen Korean BBQ & Sushi",
    address: "Warschauer Str. 46, 10243 Berlin",
    phone: "+49 30 65214130",
    hours: "매일 12:00-23:00",
    rating: 4.4,
    ratingCount: "34+",
    why: "이스트사이드 갤러리 인근 바르샤우어 슈트라세의 한식당. 한국 BBQ와 스시를 함께 즐길 수 있으며, 기무밥(김밥)·잡채·불고기가 특히 인기입니다. 한독 가족이 운영하는 정겨운 분위기에 합리적인 가격이 강점입니다.",
    tip: "저녁과 주말은 예약 필수. 기무밥과 잡채 세트가 가성비 최고.",
  },
  {
    rank: 5,
    emoji: "🥘",
    nameKo: "서울관",
    nameEn: "Seoul Kwan",
    address: "Schmiljanstraße 25, 12161 Berlin",
    phone: "+49 30 8592972",
    hours: "월-금 12:00-15:00, 18:00-23:00, 토-일 18:00-23:00",
    rating: 3.9,
    ratingCount: "38+",
    why: "1989년 창업, 35년 역사의 베를린 최장수 한식당. 프리데나우 조용한 골목에 위치하며, 손님의 75%가 한국인인 교민 검증 맛집입니다. 만두·김치전·탕수육·곱창 등 전통 한식 클래식을 변함없는 맛으로 제공합니다.",
    tip: "가족적인 분위기의 단골 식당. 예약 없이도 방문 가능하나 주말 저녁은 예약 권장.",
  },
];

// ─── PARIS ────────────────────────────────────────────────────────────────────
const TOP5_FOOD_PARIS: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍗",
    nameKo: "종로 삼계탕",
    nameEn: "Jong No Samgyetang",
    address: "23 Boulevard de Port-Royal, 75013 Paris",
    phone: "+33 9 83 70 66 02",
    hours: "월-토 12:00-14:00, 19:00-22:00, 일 휴무",
    rating: 4.7,
    ratingCount: "15+",
    why: "13구 고블랑 지하철역 인근의 삼계탕 전문 한식당. 18석 규모의 아담한 공간에서 인삼을 넣어 천천히 끓인 정통 삼계탕을 제공합니다. 트립어드바이저 4.7점, 미슐랭 가이드 파리가 주목한 진정성 있는 한식당으로, 파리 한인 커뮤니티의 사랑을 받는 곳입니다.",
    tip: "18석뿐이라 예약 필수. 삼계탕 외 갈비찜·닭도리탕도 추천. 일요일 휴무 확인.",
    website: "jongno.fr",
  },
  {
    rank: 2,
    emoji: "🍽️",
    nameKo: "한강 레스토랑",
    nameEn: "Hangang Restaurant Coréen",
    address: "59 Avenue Félix Faure, 75015 Paris",
    phone: "+33 1 45 54 56 32",
    hours: "월-토 12:00-14:30, 19:00-22:30, 일 19:00-22:30",
    rating: 4.7,
    ratingCount: "61+",
    why: "15구 부시코 지하철역 인근의 정통 한식당. 비빔밥·불고기·바비큐와 함께 기가 막힌 반찬(김치·연근 조림 등)이 제공됩니다. 트립어드바이저 4.7점으로 파리 한식당 최상위권에 자리한 교민·관광객 공인 맛집입니다.",
    tip: "반찬이 매우 훌륭함. 소고기 비빔밥과 불고기 조합 추천. 예약 권장.",
    website: "hangang.fr",
  },
  {
    rank: 3,
    emoji: "🎨",
    nameKo: "피에르 상 인 오베르캉프",
    nameEn: "Pierre Sang in Oberkampf",
    address: "55 rue Oberkampf, 75011 Paris",
    phone: "+33 9 67 31 96 80",
    hours: "토-일 12:00-14:15, 매일 저녁 19:00, 21:45 (2부제)",
    rating: 4.3,
    ratingCount: "1433+",
    why: "탑셰프 파이널리스트 출신 피에르 상 보이에의 프렌치-코리안 퓨전 레스토랑. 미슐랭 가이드 선정 레스토랑으로, 매일 바뀌는 런치 메뉴와 월별 디너 코스로 한국의 재료와 프랑스 기법이 만나는 독창적인 요리를 선보입니다.",
    tip: "1,400개 이상의 트립어드바이저 리뷰. 예약 필수. 메뉴가 매일 달라지는 서프라이즈 다이닝.",
    website: "pierresang.com",
  },
  {
    rank: 4,
    emoji: "🥢",
    nameKo: "한잔",
    nameEn: "Hanzan",
    address: "11 rue Beaugrenelle, 75015 Paris",
    phone: "+33 1 45 71 63 53",
    hours: "월-토 12:00-14:30, 19:00-22:30, 일 휴무",
    rating: 4.1,
    ratingCount: "59+",
    why: "15구 보그르넬 지역의 정통 한식당으로 '파리에서 가장 한국적인 맛'을 표방합니다. 족발·떡볶이·한국 치킨·김치찌개 등 다양한 한국 가정식과 길거리 음식을 즐길 수 있으며, 빙수 등 디저트도 제공합니다.",
    tip: "Restaurant Guru 689개 리뷰 4.4점. 족발이 시그니처 메뉴. 빙수로 마무리 추천.",
    website: "hanzan.fr",
  },
  {
    rank: 5,
    emoji: "🍱",
    nameKo: "코리안 키친 파리",
    nameEn: "Korean Kitchen Paris",
    address: "파리 13구 포르트 디브리 지역 (Porte d'Ivry)",
    phone: "정보 직접 확인 권장",
    hours: "정보 직접 확인 권장",
    rating: 4.0,
    ratingCount: "200+",
    why: "파리 최대 한인 밀집 지역인 13구 이브리 지역의 한식당. 비빔밥·불고기·김치찌개를 합리적인 가격에 제공하며 딜리버루 배달도 가능합니다. 13구 차이나타운 & 코리아타운 탐방 중 들르기 좋은 위치입니다.",
    tip: "13구 탐방 시 '트라이앵글 드 슈아지(Triangle de Choisy)' 구역에 한식당이 밀집. 당일 영업 확인 권장.",
  },
];

// ─── DUBAI ────────────────────────────────────────────────────────────────────
const TOP5_FOOD_DUBAI: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "스모키 모토",
    nameEn: "Smoki Moto",
    address: "Marriott Resort Palm Jumeirah, Palm West Beach, Palm Jumeirah, Dubai",
    phone: "+971 4 666 1430",
    hours: "일-목 17:00-01:00, 금-토 17:00-01:00, 월 휴무",
    rating: 5.0,
    ratingCount: "390+",
    why: "두바이 최초 정식 라이선스 한국식 스테이크하우스로 팜 주메이라의 메리어트 리조트에 위치합니다. A5 와규 안심·버터 드라이에이지 스테이크·콜프 큐어드 스테이크를 테이블사이드 숯불 그릴에서 셰프가 직접 구워주며, DJ 세트와 함께하는 트렌디한 분위기가 특별합니다. gulfkoreantimes.net이 주목한 두바이 한식 파인다이닝.",
    tip: "예약 필수. A5 와규 텐더로인과 코코넛 망고 빙수가 시그니처. 드레스코드 있음.",
    website: "smokimotodubai.com",
  },
  {
    rank: 2,
    emoji: "🌟",
    nameKo: "하누",
    nameEn: "HANU",
    address: "St. Regis Gardens, Palm Jumeirah, Dubai",
    phone: "+971 4 278 4844",
    hours: "일-수 18:00-01:00, 목-금 18:00-02:00, 토 13:00-16:00, 18:00-02:00",
    rating: 4.5,
    ratingCount: "200+",
    why: "서울 출신 정경수 셰프가 이끄는 두바이 최고급 한국식 다이닝. 횡성 한우와 고베 비프를 독점 제공하는 두바이 유일의 레스토랑으로, 팜 주메이라 야경을 바라보며 한국식 오마카세를 경험할 수 있습니다. gulfkoreantimes.net에서 '횡성 한우 앰버서더' 선정 식당으로 소개.",
    tip: "파인다이닝으로 예약 필수. 토요일 런치 브런치도 운영. '미트 미 앳 더 그릴' 오마카세 코스 추천.",
    website: "hanu-restaurant.com",
  },
  {
    rank: 3,
    emoji: "🍖",
    nameKo: "현 코리안 레스토랑",
    nameEn: "HYU Korean Restaurant",
    address: "Shop No. 6, O2 Residence Tower, Cluster O, Jumeirah Lake Towers, Dubai",
    phone: "+971 50 871 7389",
    hours: "매일 11:00-22:30",
    rating: 4.1,
    ratingCount: "89+",
    why: "2010년부터 운영되어온 JLT(주메이라 레이크 타워스)의 정통 한식당. 테이블 그릴 한국 바비큐·비빔밥·삼계탕·해물파전을 합리적인 가격에 제공합니다. 두바이 교민들이 오래 전부터 즐겨 찾는 믿을 수 있는 한식 맛집.",
    tip: "양념 갈비(마리네이드 소갈비)와 닭강정이 인기 메뉴. 프라이빗 다이닝룸 예약 가능.",
  },
  {
    rank: 4,
    emoji: "🍚",
    nameKo: "마시쏘요",
    nameEn: "Mashisoyo",
    address: "UB 03, Jumeirah Business Center 1, Cluster G, Jumeirah Lake Towers, Dubai",
    phone: "+971 50 380 3023",
    hours: "매일 11:00-22:30",
    rating: 3.3,
    ratingCount: "3+",
    why: "JLT의 할랄 인증 한식당으로 무슬림 친화적인 진정성 있는 한국 요리를 제공합니다. 김치·비빔밥·한국 BBQ 무제한 옵션을 구비하고 있으며, 탈라밧(Talabat) 배달 서비스도 제공합니다. 두바이의 다양한 국적 거주자 모두가 즐길 수 있는 열린 한식당.",
    tip: "할랄 인증 한식당이라 무슬림 동료·친구와 함께 방문하기 좋음. 배달도 가능.",
    website: "mashisoyo.ae",
  },
  {
    rank: 5,
    emoji: "🥡",
    nameKo: "컵밥",
    nameEn: "Cupbop",
    address: "The Walk, JBR (Jumeirah Beach Residence), Dubai",
    phone: "정보 직접 확인 권장",
    hours: "매일 10:00-24:00 (예상)",
    rating: 4.2,
    ratingCount: "500+",
    why: "한국 푸드트럭에서 시작해 세계적으로 확장된 컵밥 체인의 두바이 JBR 플래그십 매장(2026년 1월 오픈). 한국식 BBQ 덮밥을 컵에 담아 빠르게 즐길 수 있는 캐주얼 컨셉으로 이베레타타 몰·데이라 시티센터에도 추가 매장이 있습니다. gulfkoreantimes.net이 두바이 도착 한식 브랜드로 소개.",
    tip: "JBR 더 워크 해변 산책 후 가볍게 즐기기 좋음. 스파이시 레벨 선택 가능.",
    website: "cupbopuae.com",
  },
];

export {
  TOP5_FOOD_LONDON,
  TOP5_FOOD_FRANKFURT,
  TOP5_FOOD_BERLIN,
  TOP5_FOOD_PARIS,
  TOP5_FOOD_DUBAI,
};
