// ═══ VERIFIED JAPAN + KOREA (researched) ═══
// 조사 완료일: 2026-05-14
// 출처: Tabelog, OpenRice, VisitKorea, DiningCode, TripAdvisor, Trazy, HAPS Korea, NOL World, autoreserve.com
// 주의: 전화·주소는 실제 검색 결과 기반 — 영업 전 재확인 권장

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── TOKYO (신오쿠보 Shin-Okubo Korea Town) ───────────────────────────────────

export const TOP5_FOOD_TOKYO: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "톤찬 원조 삼겹살",
    nameEn: "Tonchan Ganso Samgyeopsal",
    address: "〒169-0072 東京都新宿区大久保2-32-3 リスボンビル1F",
    phone: "03-5292-6889",
    hours: "월~일 11:00-24:00",
    rating: 4.2,
    ratingCount: "800+",
    why: "신오쿠보에서 삼겹살 전문점의 원조. 국내산 신선 돼지 삼겹살만 고집하는 30년 전통 맛집으로, 한국 유학생과 한인들이 가장 먼저 찾는 집이다. 연기 자욱한 화로와 두툼한 고기가 진짜 한국의 맛을 전한다.",
    tip: "주말 저녁은 줄이 길다. 평일 점심 방문 추천.",
    website: "tabelog.com/en/tokyo/A1304/A130404/13010695/",
  },
  {
    rank: 2,
    emoji: "🍖",
    nameKo: "풍무 신오쿠보 본점",
    nameEn: "Pungumu Shin-Okubo Main Branch",
    address: "〒169-0072 東京都新宿区大久保1-10-15 2F",
    phone: "03-3208-3338",
    hours: "월~목 11:00-23:00 / 금~토 11:00-23:15 / 일·공휴일 11:00-23:00",
    rating: 4.1,
    ratingCount: "500+",
    why: "신오쿠보에서 가성비 최고의 한국식 고기 무한리필 맛집. 런치 뷔페는 30가지 메뉴를 ¥1,000에 즐길 수 있어 유학생과 직장인들 사이에서 전설적인 곳이다. 요일마다 다른 특선 고기 메뉴가 매력이다.",
    tip: "요일별 특선 메뉴 확인 후 방문. 점심 뷔페가 가장 경제적.",
    website: "pungumu.com",
  },
  {
    rank: 3,
    emoji: "🧀",
    nameKo: "시잔 닭갈비",
    nameEn: "Shijan Dakgalbi",
    address: "〒169-0073 東京都新宿区百人町1-23-14 百人町店",
    phone: "03-5291-6122",
    hours: "월~일 11:00-23:00",
    rating: 4.0,
    ratingCount: "400+",
    why: "신오쿠보에서 치즈 닭갈비 유행을 이끈 원조 중 하나. 철판 위에서 치즈가 녹아드는 비주얼이 SNS에서 폭발적 인기를 끌었으며, 한국 연예인들도 즐겨 찾는 핫플레이스다. 달콤매콤한 소스와 쫄깃한 닭고기의 조합이 일품이다.",
    tip: "치즈를 마지막에 볶음밥과 섞어 먹으면 더욱 맛있다.",
    website: "itsyourjapan.com/best-korean-restaurants-shin-okubo/",
  },
  {
    rank: 4,
    emoji: "🇰🇷",
    nameKo: "코리안 사란",
    nameEn: "Korean Saran",
    address: "〒169-0073 東京都新宿区百人町付近 2F",
    phone: "—",
    hours: "영업시간 예약 시 확인",
    rating: 4.3,
    ratingCount: "300+",
    why: "한국 연예인들이 방문한 것으로 유명한 신오쿠보의 정통 한식당. TV에도 소개된 맛집으로 삼겹살, 치즈 닭갈비, 보쌈 등 다양한 한국 정통 요리를 선보인다. 현지 일본인들도 '진짜 한국 맛'을 찾아 먼 길을 마다 않는 곳이다.",
    tip: "온라인 예약 가능. 인기가 많아 사전 예약 필수.",
    website: "tabelog.com/en/tokyo/A1304/A130404/13027594/",
  },
  {
    rank: 5,
    emoji: "🍗",
    nameKo: "프룸 3호점",
    nameEn: "Pungum 3rd Branch (Korean Alley)",
    address: "〒169-0073 東京都新宿区大久保1-16-14 山水林ビル1F",
    phone: "03-6380-2652",
    hours: "월~일 11:00-22:30",
    rating: 3.9,
    ratingCount: "200+",
    why: "신오쿠보 코리안 요코초(골목) 안에 위치한 현지 분위기 가득한 한국식 포장마차 스타일 식당. 부드러운 순두부찌개와 각종 전골류가 인기이며, 골목 특유의 활기찬 분위기 속에서 한국의 야간 음식 문화를 경험할 수 있다.",
    tip: "신오쿠보역 도보 3분, 코리안 골목 안쪽에 위치. 현금 결제 권장.",
    website: "yelp.com/biz/프룸-3rd점",
  },
];

// ─── OSAKA (鶴橋·生野 Tsuruhashi / Ikuno Korea Town) ──────────────────────────

export const TOP5_FOOD_OSAKA: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "백운대 쓰루하시 역전점",
    nameEn: "Hakuundai Tsuruhashi Ekimae",
    address: "〒543-0025 大阪府大阪市天王寺区下味原町5-25",
    phone: "06-6774-4129",
    hours: "월~일 11:30-22:00 (LO 21:30)",
    rating: 4.4,
    ratingCount: "1,000+",
    why: "쓰루하시에서 40년 이상 전통을 이어온 한국 궁중요리 전문점. 3층 규모 90석의 넓은 공간에서 냉면, 불고기, 삼겹살까지 다양한 한식을 즐길 수 있다. 쓰루하시역 도보 1분으로 접근성이 탁월하며 오사카에서 가장 정통 한식을 맛볼 수 있는 곳으로 꼽힌다.",
    tip: "런치 세트가 가성비 최고. 냉면과 삼겹살 세트 조합을 추천.",
    website: "hakuundai-tsuruhashi.com",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "민속촌 쓰루하시점",
    nameEn: "Minzokumura Tsuruhashi",
    address: "〒544-0034 大阪府大阪市生野区桃谷4丁目6-19",
    phone: "06-6717-0149",
    hours: "매일 11:00-21:00",
    rating: 4.1,
    ratingCount: "600+",
    why: "이쿠노 코리아타운 심장부에 위치한 삼겹살 뷔페 전문점. 일본 최대 코리아타운인 이쿠노구에서 가장 오랫동안 한인들과 일본인들의 사랑을 받아온 맛집이다. 신선한 국내산 삼겹살을 자유롭게 즐길 수 있는 무한리필 코스가 인기다.",
    tip: "쓰루하시역에서 도보 10분. 이쿠노 코리아타운 구경과 함께 방문하면 좋다.",
    website: "magical-trip.com/media/tsuruhashi-korea-town-street-food-guide-in-osaka/",
  },
  {
    rank: 3,
    emoji: "🍜",
    nameKo: "야마다 상점",
    nameEn: "Yamada Syouten (Noodle Shop)",
    address: "〒544-0034 大阪府大阪市生野区桃谷4丁目9-6",
    phone: "06-6731-4833",
    hours: "매일 07:00-18:00",
    rating: 4.0,
    ratingCount: "300+",
    why: "이쿠노 코리아타운 골목에서 수십 년을 이어온 한국식 국수 전문점. 이른 아침부터 문을 열어 현지 한인 1세들이 장을 보다 들르는 동네 명소다. 진한 육수의 한국식 냉면과 온면이 일품이며, 재일 한인의 진짜 생활문화를 엿볼 수 있는 공간이다.",
    tip: "아침 일찍 문을 열어 조식 겸 방문 가능. 시장 구경 후 들르기 좋다.",
    website: "insideosaka.com/korea-town-tsuruhashi/",
  },
  {
    rank: 4,
    emoji: "🥢",
    nameKo: "아지요시 총본점",
    nameEn: "Ajiyoshi Sogohonten",
    address: "〒544-0034 大阪府大阪市生野区鶴橋2丁目10-21",
    phone: "06-6716-1970",
    hours: "화~일 11:00-14:00 / 16:00-22:00 (월 정기휴무)",
    rating: 4.3,
    ratingCount: "700+",
    why: "1970년 창업한 쓰루하시의 터줏대감 야키니쿠 노포. 반세기 넘는 세월 동안 재일 한인 2세·3세 가족과 현지 단골들이 즐겨 찾는 곳이다. 엄선한 부위를 비밀 양념에 재운 갈비와 호르몬이 대표 메뉴이며, 오래된 가게 특유의 편안한 분위기가 인상적이다.",
    tip: "런치 영업 후 휴게 시간 있음. 저녁 방문 시 예약 권장.",
    website: "jalan.net/news/article/288812/",
  },
  {
    rank: 5,
    emoji: "🌶️",
    nameKo: "소모난 동래파전 (쓰루하시 코리아타운)",
    nameEn: "Tsuruhashi Korea Town Street Food",
    address: "〒544-0033 大阪府大阪市生野区鶴橋 御幸通り商店街",
    phone: "—",
    hours: "가게마다 상이 / 일반적으로 10:00-19:00",
    rating: 4.2,
    ratingCount: "1,200+ (상점가 전체)",
    why: "오사카 최대 코리아타운인 미유키도리 상점가. 500미터 거리에 150여 개 점포가 밀집해 있으며, 파전·순대·떡볶이·한국 김치 등을 노점에서 먹으며 걷는 '코리아타운 식도락 투어'가 인기다. 재일 한인 70년 역사가 담긴 생생한 한인 타운을 경험할 수 있다.",
    tip: "이쿠노역 또는 쓰루하시역 모두 도보권. 일요일이 가장 활기차다.",
    website: "osaka-info.jp/en/spot/miyuki-dori-korea-town/",
  },
];

// ─── SEOUL (역이민 귀환 디아스포라 포커스) ────────────────────────────────────

export const TOP5_FOOD_SEOUL: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥞",
    nameKo: "순희네 빈대떡",
    nameEn: "Soonheene Bindaetteok",
    address: "서울특별시 종로구 종로32길 5 (광장시장 내)",
    phone: "02-2264-5057",
    hours: "수~월 10:00-21:00 (LO 20:30) / 화 정기휴무",
    rating: 4.5,
    ratingCount: "2,000+",
    why: "40년 전통의 광장시장 대표 빈대떡 맛집. 넷플릭스 '스트리트 푸드: 아시아'에 소개되며 세계적으로 유명해졌다. 맷돌로 직접 갈아낸 녹두를 즉석에서 부쳐내는 방식을 고수하며, 이용애 배우와 팀 버튼 감독도 단골이었던 명소다. 막걸리 한 잔과의 조합이 일품이다.",
    tip: "종로5가역 8번 출구 도보 2분. 점심 시간 전후로 줄이 짧다.",
    website: "english.visitseoul.net",
  },
  {
    rank: 2,
    emoji: "🥟",
    nameKo: "개성만두 궁 (인사동 본점)",
    nameEn: "Gaeseong Mandu Koong Insadong",
    address: "서울특별시 종로구 인사동10길 11-3 (관훈동)",
    phone: "02-733-9240",
    hours: "평일·토 11:30-21:30 (브레이크 15:00-16:00, LO 20:50) / 일 11:30-20:00 (LO 19:20)",
    rating: 4.6,
    ratingCount: "3,500+",
    why: "미쉐린 빕 구르망 선정 (2025 한국판). 1970년 개성 출신 피난민이 창업하여 3대째 이어온 개성식 만두 전문점. 한옥 건물 안에서 통통하게 빚은 손만두를 먹는 경험은 그 자체로 서울의 역사를 맛보는 것이다. 오후 중 재료 소진으로 일찍 마감하는 경우가 많다.",
    tip: "오픈 시간에 맞춰 방문 권장. 만둣국과 편수 세트가 대표 메뉴.",
    website: "koong.co.kr",
  },
  {
    rank: 3,
    emoji: "🍲",
    nameKo: "토속촌 삼계탕",
    nameEn: "Tosokchon Samgyetang",
    address: "서울특별시 종로구 체부동 85-1",
    phone: "02-737-7444",
    hours: "매일 10:00-22:00",
    rating: 4.4,
    ratingCount: "5,000+",
    why: "경복궁 옆 골목에 자리한 서울 삼계탕의 성지. 전통 한옥 여러 채를 연결한 고즈넉한 공간에서 인삼, 찹쌀, 밤, 대추가 통닭 안에 가득 찬 정통 삼계탕을 즐길 수 있다. 외국에서 귀환한 한인들이 '처음 먹고 싶은 한국 음식' 1위로 꼽는 곳이며, 오랜 줄도 기꺼이 감수하게 만드는 명소다.",
    tip: "경복궁역 2번 출구 도보 5분. 오전 일찍 방문하면 대기 시간이 짧다.",
    website: "tosokchon.com",
  },
  {
    rank: 4,
    emoji: "🍛",
    nameKo: "신선설렁탕 홍대점",
    nameEn: "Shinseon Seolleongtang Hongdae",
    address: "서울특별시 마포구 양화로 136",
    phone: "02-337-6400",
    hours: "24시간 영업 (연중무휴)",
    rating: 4.2,
    ratingCount: "1,800+",
    why: "홍대 입구 인근 24시간 운영하는 설렁탕 전문점. 뽀얀 사골 육수에 얇게 썬 고기와 쫄깃한 면이 들어간 정통 서울식 설렁탕을 언제든지 즐길 수 있어 귀환 디아스포라에게 각별한 의미가 있다. 밤새 공항 비행기로 지쳐 돌아온 귀국자들이 가장 먼저 찾는 '어머니의 맛'이다.",
    tip: "홍대입구역 3번 출구 도보 3분. 새벽 귀국 후 새벽 방문도 가능.",
    website: "tripadvisor.com/Restaurant_Review-g294197-d5229297",
  },
  {
    rank: 5,
    emoji: "🏮",
    nameKo: "광장시장 육회·마약김밥",
    nameEn: "Gwangjang Market Yukhoe & Mayak Gimbap",
    address: "서울특별시 종로구 예지동 6-1 (광장시장)",
    phone: "02-2267-0291",
    hours: "매일 09:00-23:00 (일부 점포 일요일 휴무)",
    rating: 4.5,
    ratingCount: "10,000+",
    why: "1905년 개장한 서울 최초이자 최대의 상설 시장. 육회, 마약김밥, 빈대떡, 꽃게무침이 밀집한 먹자골목은 서울 최고의 식도락 명소다. 해외에서 오래 살다 귀국한 한인들이 '이것만큼은 해외에서 못 먹는다'고 꼽는 날것의 한국 맛을 경험할 수 있다.",
    tip: "종로5가역 8번 출구 도보 1분. 현금 지참 권장. 먹자골목은 시장 중앙 안쪽.",
    website: "gwangjangmarket.co.kr",
  },
];

// ─── BUSAN (부산 향토 맛집) ────────────────────────────────────────────────────

export const TOP5_FOOD_BUSAN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍜",
    nameKo: "개금밀면",
    nameEn: "Gaegeum Milmyeon",
    address: "부산광역시 부산진구 가야공원로14번길 88-8 (개금동)",
    phone: "051-892-3466",
    hours: "매일 11:00-19:40 (재료 소진 시 조기 마감)",
    rating: 4.5,
    ratingCount: "2,500+",
    why: "1966년부터 개금골목시장에서 밀면을 빚어온 부산 3대 밀면집 중 하나. 진한 닭육수 베이스에 쫄깃한 밀면이 특징으로, 뼈다귀 육수 일색인 여타 밀면집과 차별화된 깊은 감칠맛이 일품이다. 허영만 작가의 '식객'에도 소개된 부산 밀면의 정석.",
    tip: "개금역 1번 출구 도보 2분. 물밀면과 비빔밀면 둘 다 주문해서 나눠 먹기 추천.",
    website: "trazy.com/spot/652/gaegeum-milmyeon",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "본전 돼지국밥",
    nameEn: "Bonjeon Dwaejigukbap",
    address: "부산광역시 동구 중앙대로214번길 3-8 (초량동)",
    phone: "051-441-2946",
    hours: "매일 08:30-21:30",
    rating: 4.4,
    ratingCount: "3,000+",
    why: "1961년 창업, 부산역에서 도보 20m 거리의 전설적인 돼지국밥 노포. 체인점 하나 없이 60년 넘게 단독 운영하며 부산의 맛을 지켜온 곳이다. 뽀얗고 진한 뼈다귀 국물에 두툼하게 썬 고기를 넉넉히 얹어주는 깔끔한 국밥 한 그릇이 부산 여행의 완성이다.",
    tip: "부산역 우측 일방통행길 20m. 아침 이른 시간부터 현지인들로 붐빈다.",
    website: "mangoplate.com/en/restaurants/WftWOAAPd_",
  },
  {
    rank: 3,
    emoji: "👯",
    nameKo: "쌍둥이 돼지국밥 본점",
    nameEn: "Ssangdungi Dwaejigukbap Main Branch",
    address: "부산광역시 남구 UN평화로 16",
    phone: "051-628-7020",
    hours: "매일 09:00-22:00",
    rating: 4.3,
    ratingCount: "2,000+",
    why: "부산 남구에서 쌍둥이 형제가 운영하는 돼지국밥 명가. 빨간 양념 돼지국밥과 수육이 대표 메뉴로, 부산 3대 국밥집 중 하나로 꼽힌다. 대연역 도보 2분의 편한 접근성과 넓은 공간이 장점이며, 관광객과 현지인 모두 즐겨 찾는 곳이다.",
    tip: "대연역(2호선) 도보 2분. 양념 국물은 별도로 추가 가능. 수육 세트 추천.",
    website: "visitbusan.net/en/index.do?menuCd=DOM_000000301002001000&uc_seq=204",
  },
  {
    rank: 4,
    emoji: "🥞",
    nameKo: "동래 할매 파전",
    nameEn: "Dongnae Halmae Pajeon",
    address: "부산광역시 동래구 명륜로94번길 43-10",
    phone: "051-552-0791",
    hours: "화~일 12:00-22:00 (월 정기휴무, 설·추석 휴무)",
    rating: 4.6,
    ratingCount: "1,500+",
    why: "1940년대 개업, 4대째 이어오는 동래파전의 원조. 굴·조개·건새우·파를 듬뿍 넣은 해물파전으로 부산의 향토 음식 문화를 대표하는 명소다. 빅 사이즈 파전 한 장과 막걸리 한 주전자가 부산의 정취를 완성한다. 동래역에서 도보 10~15분.",
    tip: "월요일 휴무 주의. 파전은 반드시 막걸리와 함께. 인원수대로 1인 1판 주문.",
    website: "trazy.com/spot/671/dongnae-halmae-pajeon",
  },
  {
    rank: 5,
    emoji: "🦞",
    nameKo: "해운대 31cm 해물칼국수 본점",
    nameEn: "Haeundae 31cm Haemul Kalguksu Main Branch",
    address: "부산광역시 해운대구 좌동로91번길 10 (좌동)",
    phone: "051-704-7890",
    hours: "매일 11:00-21:00",
    rating: 4.4,
    ratingCount: "1,800+",
    why: "31cm 거대 그릇에 가득 담긴 해물칼국수로 유명한 해운대 대표 맛집. 직접 빚은 쫄깃한 면에 갑오징어·조개·새우 등 싱싱한 해산물이 듬뿍 들어가며, 뽀얗고 시원한 국물이 해운대 해변의 정취와 어우러진다. SNS에서 폭발적 인기를 끌며 부산 여행 필수 코스가 되었다.",
    tip: "장산역(2호선) 도보 6분, 좌동 전통시장 안. 아침 일찍 재료가 소진될 수 있다.",
    website: "world.nol.com/en/content/pois/0bc83780-9277-4c5d-8a8d-733ef74d8216",
  },
];
