// ═══ EUROPE TOP5_FOOD DATA ═══

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── LONDON ───────────────────────────────────────────────────────────────────
const TOP5_FOOD_LONDON: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍖",
    nameKo: "코리아나 레스토랑",
    nameEn: "Koreana Restaurant",
    address: "1 Lancaster Ct, New Malden KT3 4DX",
    phone: "+44 20 8942 0203",
    hours: "화-일 12:00-14:30, 18:00-22:00",
    rating: 4.4,
    ratingCount: "600+",
    why: "🍖 뉴몰든 한식 명가\n런던 최대 한인 커뮤니티인 뉴몰든(New Malden)의 대표 한식당으로, 30년 넘게 한국 교민들의 밥상을 책임져온 곳입니다. 삼겹살·갈비·된장찌개 등 정통 가정식이 한국 본토의 맛과 거의 차이가 없어 런던 교민들 사이에서 '고향 음식'으로 통합니다.",
    tip: "주말 점심은 자리가 빨리 차니 사전 예약 필수. 주차는 인근 공영주차장 이용.",
    website: "koreanarestaurant.co.uk",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "진주 가든",
    nameEn: "Jinju Garden",
    address: "20 Burlington Rd, New Malden KT3 4NQ",
    phone: "+44 20 8949 7079",
    hours: "월-일 11:30-22:00",
    rating: 4.3,
    ratingCount: "400+",
    why: "🥩 뉴몰든 정통 BBQ\n뉴몰든 한인 타운 내에서 가장 활기 넘치는 한국식 바베큐 전문점입니다. 테이블 직화 그릴에서 굽는 한우 등심과 갈비가 일품이며, 반찬 구성도 한국 현지 수준으로 풍성합니다. 주말 저녁에는 한국 가족 손님들로 가득 찬 정겨운 분위기를 느낄 수 있습니다.",
    tip: "된장찌개나 순두부찌개 등 찌개류 세트를 주문하면 가성비가 높습니다.",
  },
  {
    rank: 3,
    emoji: "🍣",
    nameKo: "아리랑 한식당",
    nameEn: "Arirang Korean Restaurant",
    address: "31-32 Poland St, London W1F 8QY",
    phone: "+44 20 7437 9662",
    hours: "월-토 12:00-15:00, 18:00-22:30",
    rating: 4.2,
    ratingCount: "800+",
    why: "🍣 소호 한식의 오랜 전통\n런던 웨스트엔드 소호 한복판에 자리한 아리랑은 1972년 개업 이후 50년 넘게 영국 주류 미디어와 교민 모두에게 사랑받아온 역사적인 한식당입니다. 비빔밥·불고기·잡채 등 클래식 메뉴가 탄탄하고, 관광객과 교민이 함께 어우러지는 런던 한식 문화의 상징 같은 곳입니다.",
    tip: "평일 점심 세트 메뉴가 합리적인 가격으로 구성되어 있어 직장인들에게 인기입니다.",
    website: "arirangkorean.co.uk",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "도라지 한식당",
    nameEn: "Doraji Korean Restaurant",
    address: "51 Burlington Rd, New Malden KT3 4NE",
    phone: "+44 20 8942 1560",
    hours: "화-일 11:30-21:30",
    rating: 4.3,
    ratingCount: "350+",
    why: "🍜 순대·국밥 전문 가정식\n뉴몰든 교민 사회에서 '엄마 손맛'으로 유명한 가정식 전문점입니다. 순대국밥·감자탕·설렁탕 등 국물 요리에 강점이 있으며, 시원한 국물 한 그릇이 그리울 때 가장 먼저 찾게 되는 곳입니다. 교민 어르신들의 단골 식당으로도 잘 알려져 있습니다.",
    tip: "주중 오전 11시 30분 오픈 직후 방문하면 여유 있게 식사할 수 있습니다.",
  },
  {
    rank: 5,
    emoji: "🥘",
    nameKo: "서울 플라자",
    nameEn: "Seoul Plaza",
    address: "59A Kingston Rd, New Malden KT3 3PB",
    phone: "+44 20 8942 3655",
    hours: "월-일 10:00-21:00",
    rating: 4.1,
    ratingCount: "300+",
    why: "🥘 한국 식품점 겸 분식 코너\n뉴몰든의 대표 한인 마트 겸 분식 공간으로, 떡볶이·김밥·라면·만두 등 간단한 한국 분식을 저렴하게 즐길 수 있습니다. 한국 식품 쇼핑과 간식을 한 번에 해결할 수 있어 교민들의 생필품 구매 루트로 필수 코스입니다.",
    tip: "한국 라면·고추장·된장 등 식재료를 함께 구매하면 장바구니를 채우기 좋습니다.",
  },
];

// ─── PARIS ────────────────────────────────────────────────────────────────────
const TOP5_FOOD_PARIS: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "오감도",
    nameEn: "Ogamdo",
    address: "19 Rue du Faubourg Saint-Antoine, 75011 Paris",
    phone: "+33 1 43 55 00 10",
    hours: "월-토 12:00-14:30, 18:30-22:30",
    rating: 4.4,
    ratingCount: "700+",
    why: "🥩 파리 한식의 새 기준\n파리 11구 바스티유 인근에 위치한 오감도는 모던 한식의 정수를 보여주는 레스토랑으로, 프랑스 미식 잡지에도 소개된 곳입니다. 한우 숙성 삼겹살과 제철 재료를 활용한 한식 코스 메뉴가 특히 호평받으며, 파리 한인 교민과 프랑스 현지인 모두가 즐겨 찾습니다.",
    tip: "코스 메뉴는 사전 예약 필수. 와인 페어링 옵션도 훌륭합니다.",
    website: "ogamdo-paris.fr",
  },
  {
    rank: 2,
    emoji: "🍜",
    nameKo: "한강 레스토랑",
    nameEn: "Han Kang Restaurant",
    address: "8 Rue de la Verrerie, 75004 Paris",
    phone: "+33 1 42 77 63 77",
    hours: "월-일 12:00-15:00, 18:00-23:00",
    rating: 4.3,
    ratingCount: "900+",
    why: "🍜 파리 중심부 정통 한식\n파리 4구 마레 지구 한복판에 자리한 한강은 관광 중심지임에도 가격 대비 음식 수준이 높아 교민과 여행객 모두에게 신뢰받는 곳입니다. 삼계탕·비빔밥·잡채 등 정통 한식 메뉴가 탄탄하며, 프랑스어 메뉴판도 잘 갖춰져 있어 언어 장벽 없이 편하게 이용할 수 있습니다.",
    tip: "삼계탕은 하루 한정 수량이라 점심 오픈 시간에 맞춰 방문하는 것이 좋습니다.",
  },
  {
    rank: 3,
    emoji: "🥗",
    nameKo: "코리아나 (13구)",
    nameEn: "Koreana Paris 13",
    address: "44 Avenue de Choisy, 75013 Paris",
    phone: "+33 1 45 84 05 88",
    hours: "화-일 11:30-14:30, 18:30-22:00",
    rating: 4.2,
    ratingCount: "500+",
    why: "🥗 파리 코리아타운 13구의 터줏대감\n파리 한인 커뮤니티의 중심지인 13구 쇼아지 대로(Avenue de Choisy) 한인 타운의 대표 식당입니다. 김치찌개·순두부찌개·된장찌개 등 찌개 종류가 특히 뛰어나고, 가정식 백반 메뉴로 한 끼 해결하기에 가격도 합리적입니다.",
    tip: "13구 한인 타운 내 한국 식품점들과 함께 들러 장보기도 겸할 수 있습니다.",
  },
  {
    rank: 4,
    emoji: "🍖",
    nameKo: "서울 BBQ 파리",
    nameEn: "Seoul BBQ Paris",
    address: "31 Avenue d'Ivry, 75013 Paris",
    phone: "+33 1 45 86 00 62",
    hours: "월-일 12:00-22:30",
    rating: 4.1,
    ratingCount: "600+",
    why: "🍖 13구 직화 바베큐 전문\n파리 13구 이브리 대로의 한국식 직화 바베큐 전문점으로, 현지 한인들이 특별한 날 모이는 단골 식당입니다. 삼겹살·목살·갈비를 테이블 그릴에서 직접 구워 먹는 방식이며, 밑반찬 구성도 한국에서 먹던 것과 큰 차이가 없어 교민들의 향수를 달래줍니다.",
    tip: "주말 저녁 단체 예약은 최소 2-3일 전 연락이 필요합니다.",
  },
  {
    rank: 5,
    emoji: "🍣",
    nameKo: "곱창 파리",
    nameEn: "Gopchang Paris",
    address: "68 Avenue de Choisy, 75013 Paris",
    phone: "+33 1 45 84 22 13",
    hours: "화-일 18:00-23:00",
    rating: 4.3,
    ratingCount: "400+",
    why: "🍣 파리 유일 곱창 전문\n파리에서 거의 유일하게 곱창·막창·대창 등 내장 구이를 제대로 맛볼 수 있는 곳으로, 파리 한인 커뮤니티에서 입소문이 자자합니다. 소주와 곱창의 조합으로 한국 포장마차 분위기를 파리 한복판에서 재현하며, 특히 주말 저녁에는 예약 없이 입장하기 어려울 만큼 인기가 높습니다.",
    tip: "소주 또는 막걸리와 함께 주문하면 서비스 안주가 나올 때도 있습니다.",
  },
];

// ─── BERLIN ───────────────────────────────────────────────────────────────────
const TOP5_FOOD_BERLIN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "기와",
    nameEn: "Kiwa Korean Restaurant",
    address: "Uhlandstraße 161, 10719 Berlin",
    phone: "+49 30 8862 6888",
    hours: "화-일 12:00-15:00, 18:00-22:30",
    rating: 4.5,
    ratingCount: "1000+",
    why: "🥩 베를린 최고 평점 한식당\n베를린 샤를로텐부르크(Charlottenburg) 지역에 위치한 기와는 구글·트립어드바이저에서 꾸준히 베를린 최고 한식당으로 꼽히는 곳입니다. 한국산 재료를 직수입하여 정통 맛을 구현하며, 삼겹살·갈비찜·불고기 모두 수준이 높습니다. 독일 미식가들 사이에서도 한식의 대명사로 알려져 있습니다.",
    tip: "점심 세트는 메인 요리에 된장국·반찬·밥이 포함되어 가성비가 최고입니다.",
    website: "kiwa-berlin.de",
  },
  {
    rank: 2,
    emoji: "🍜",
    nameKo: "서울 레스토랑",
    nameEn: "Restaurant Seoul",
    address: "Bleibtreustrae 37, 10623 Berlin",
    phone: "+49 30 881 9625",
    hours: "월-토 12:00-15:00, 18:00-22:00",
    rating: 4.2,
    ratingCount: "600+",
    why: "🍜 샤를로텐부르크 터줏대감\n1980년대 초반부터 운영된 베를린의 역사 깊은 한식당으로, 독일에 거주하는 1세대 교민들의 추억이 담긴 공간입니다. 냉면·불고기·비빔밥 등 전통 메뉴가 수십 년째 같은 맛을 지키며 현지 독일인과 한인 모두에게 안정적인 신뢰를 얻고 있습니다.",
    tip: "냉면이 특히 유명하니 여름철 방문 시 꼭 주문해보세요.",
  },
  {
    rank: 3,
    emoji: "🌶️",
    nameKo: "한강 베를린",
    nameEn: "Hangang Berlin",
    address: "Kantstraße 130, 10625 Berlin",
    phone: "+49 30 3151 5380",
    hours: "화-일 12:00-22:00",
    rating: 4.3,
    ratingCount: "500+",
    why: "🌶️ 베를린 중심부 직화 BBQ\n베를린 칸트슈트라세의 한강은 현지 MZ세대 한인과 독일 젊은이들에게 폭발적인 인기를 끌고 있는 한국식 직화 BBQ 전문점입니다. 최신 환풍 시스템을 갖춘 쾌적한 실내에서 삼겹살·목살·갈비를 즐길 수 있으며, 소주·막걸리 등 한국 주류도 다양하게 구비되어 있습니다.",
    tip: "평일 저녁도 빨리 차니 저녁 6시 이전에 방문하거나 예약을 권장합니다.",
  },
  {
    rank: 4,
    emoji: "🍲",
    nameKo: "코리아 하우스",
    nameEn: "Korea House Berlin",
    address: "Fuggerstraße 9, 10777 Berlin",
    phone: "+49 30 2196 7700",
    hours: "화-일 12:00-21:30",
    rating: 4.1,
    ratingCount: "400+",
    why: "🍲 쇠네베르크 교민 가정식\n베를린 쇠네베르크(Schöneberg) 지역 한인 교민들이 오래 애용해온 가정식 식당입니다. 된장찌개·부대찌개·순두부찌개 등 국물 요리와 제육볶음·오징어볶음 등 볶음 메뉴가 모두 '집밥' 느낌으로 편안합니다. 아주머니 특유의 정겨운 서비스도 이 집의 매력입니다.",
    tip: "점심시간에 가면 백반 메뉴를 합리적인 가격에 즐길 수 있습니다.",
  },
  {
    rank: 5,
    emoji: "🥗",
    nameKo: "프렌즐라워버그 한식",
    nameEn: "Arirang Berlin Prenzlauer Berg",
    address: "Dunckerstraße 10, 10437 Berlin",
    phone: "+49 30 4401 6688",
    hours: "월-일 12:00-22:00",
    rating: 4.2,
    ratingCount: "350+",
    why: "🥗 힙스터 동네의 한식 피난처\n베를린의 트렌디한 동네 프렌즐라우어 베르크(Prenzlauer Berg)에 자리한 아리랑은 이 지역에 사는 젊은 한인 유학생·직장인들의 든든한 한식 거점입니다. 유기농 재료를 활용한 건강 비빔밥과 두부 요리가 독일 현지인들에게도 인기이며, 채식 옵션도 갖추고 있습니다.",
    tip: "채식·비건 옵션을 요청하면 별도 메뉴를 안내받을 수 있습니다.",
  },
];

// ─── FRANKFURT ────────────────────────────────────────────────────────────────
const TOP5_FOOD_FRANKFURT: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "코리아나 프랑크푸르트",
    nameEn: "Koreana Frankfurt",
    address: "Weserstraße 17, 60329 Frankfurt am Main",
    phone: "+49 69 2424 6888",
    hours: "화-일 12:00-14:30, 18:00-22:00",
    rating: 4.4,
    ratingCount: "700+",
    why: "🥩 프랑크푸르트 1등 한식\n프랑크푸르트 중앙역(Hauptbahnhof) 인근에 위치한 코리아나는 교민·주재원·한국 출장자 모두가 먼저 찾는 프랑크푸르트 최고 인기 한식당입니다. 갈비·삼겹살·냉면의 퀄리티가 특히 뛰어나며, 깔끔한 인테리어와 한국어·영어·독일어 메뉴를 모두 갖추고 있어 접근성이 좋습니다.",
    tip: "메세(Messe) 행사 기간에는 자리가 매우 부족하니 출장 시 반드시 예약하세요.",
    website: "koreana-frankfurt.de",
  },
  {
    rank: 2,
    emoji: "🍜",
    nameKo: "한국관",
    nameEn: "Hanguk Guan",
    address: "Münchener Straße 38, 60329 Frankfurt am Main",
    phone: "+49 69 2420 9080",
    hours: "월-일 11:30-22:00",
    rating: 4.2,
    ratingCount: "500+",
    why: "🍜 중앙역 인근 교민 단골 식당\n프랑크푸르트 중앙역 근처 한인 밀집 구역에 자리한 한국관은 저렴한 가격으로 든든한 한식을 즐길 수 있는 곳입니다. 육개장·갈비탕·삼계탕 등 탕류와 백반 메뉴가 특히 인기이며, 점심시간에는 주변 회사원과 교민들로 항상 붐빕니다.",
    tip: "점심 세트를 주문하면 국·반찬이 푸짐하게 나와 배부르게 먹을 수 있습니다.",
  },
  {
    rank: 3,
    emoji: "🌶️",
    nameKo: "서울 하우스",
    nameEn: "Seoul House Frankfurt",
    address: "Kaiserstraße 64, 60329 Frankfurt am Main",
    phone: "+49 69 2424 4040",
    hours: "월-토 12:00-22:30",
    rating: 4.3,
    ratingCount: "600+",
    why: "🌶️ 카이저슈트라세 한식 명소\n프랑크푸르트 번화가 카이저슈트라세 중심부에 위치한 서울 하우스는 한인 주재원·유학생과 독일 현지인이 함께 즐기는 캐주얼 한식당입니다. 제육볶음·비빔밥·돌솥밥 등 메뉴가 다양하고, 한국 소주와 맥주도 합리적인 가격에 제공합니다.",
    tip: "금요일 저녁은 교민 직장인 회식으로 붐비니 사전 예약을 권장합니다.",
  },
  {
    rank: 4,
    emoji: "🍲",
    nameKo: "아리랑 프랑크푸르트",
    nameEn: "Arirang Frankfurt",
    address: "Elbestraße 15, 60329 Frankfurt am Main",
    phone: "+49 69 2400 6677",
    hours: "화-일 11:30-21:30",
    rating: 4.1,
    ratingCount: "350+",
    why: "🍲 교민 30년 단골 가정식\n프랑크푸르트 한인 사회에서 30년 이상 사랑받아온 아리랑은 '언제 가도 실망 없는' 가정식 레스토랑으로 정평이 나 있습니다. 두부찌개·부대찌개·김치볶음밥 등 편안한 메뉴 구성이 특히 타지 생활에 지친 교민들에게 위로가 됩니다. 가격도 프랑크푸르트 물가 대비 착한 편입니다.",
    tip: "한국에서 온 가족이나 지인 방문 때 데려가기 좋은 '무난하게 맛있는' 식당입니다.",
  },
  {
    rank: 5,
    emoji: "🥗",
    nameKo: "자하 한식",
    nameEn: "Jaha Korean Kitchen",
    address: "Gutleutstraße 22, 60329 Frankfurt am Main",
    phone: "+49 69 2400 8855",
    hours: "월-토 12:00-21:00",
    rating: 4.2,
    ratingCount: "280+",
    why: "🥗 점심 특선 김밥·분식 전문\n프랑크푸르트 구트로이트슈트라세의 자하는 김밥·떡볶이·순대·라면 등 한국식 분식 전문점으로, 가볍게 한국 간식을 즐기고 싶을 때 찾게 되는 곳입니다. 합리적인 가격 덕분에 한인 유학생들의 든든한 점심 장소로 자리잡았으며, 포장 주문도 가능합니다.",
    tip: "떡볶이+김밥+순대 세트 구성이 인기 메뉴로, 배달 앱으로도 주문 가능합니다.",
  },
];

export {
  TOP5_FOOD_LONDON,
  TOP5_FOOD_PARIS,
  TOP5_FOOD_BERLIN,
  TOP5_FOOD_FRANKFURT,
};
