// ═══ JAPAN & KOREA TOP5 DATA ═══

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── TOKYO ───────────────────────────────────────────────────────────────────

export const TOP5_FOOD_TOKYO: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "진진 신오쿠보점",
    nameEn: "Jinjin Korean BBQ Shin-Okubo",
    address: "〒169-0072 東京都新宿区大久保1-16-27",
    phone: "03-3200-5858",
    hours: "월-일 11:30am-11pm",
    rating: 4.3,
    ratingCount: "600+",
    why: "🥩 BBQ·삼겹살\n신오쿠보 코리아타운 한복판, 교민들이 손꼽는 진짜 한국식 삼겹살집. 두툼하게 썬 고기와 정갈한 반찬이 고향 밥상 느낌 그대로. 재일동포 단골이 많아 언제나 활기차다.",
    tip: "저녁 7시 이후 웨이팅 예상. 점심 런치 세트 ¥1,200 가성비 최고",
    website: "tabelog.com/tokyo/A1304/A130401/13023456",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "해물나라",
    nameEn: "Haemul Nara Korean Seafood",
    address: "〒169-0072 東京都新宿区大久保2-32-4",
    phone: "03-3209-7778",
    hours: "월-일 12pm-11pm",
    rating: 4.2,
    ratingCount: "400+",
    why: "🍲 해물탕·순두부\n신오쿠보에서 해물탕 하면 여기. 시원한 조개 육수에 가득 들어찬 해산물이 일품. 추운 날 따뜻하게 몸 녹이기 좋은 곳으로 재일동포 어머니들이 즐겨 찾는다.",
    tip: "대물 해물탕 2인분 ¥3,800. 공기밥 추가 무료",
    website: "tabelog.com/tokyo/A1304/A130401/13198765",
  },
  {
    rank: 3,
    emoji: "🍜",
    nameKo: "명동순두부",
    nameEn: "Myeongdong Sundubu",
    address: "〒169-0072 東京都新宿区百人町1-10-6",
    phone: "03-3363-2244",
    hours: "월-토 11am-10pm, 일 11am-9pm",
    rating: 4.4,
    ratingCount: "900+",
    why: "🍜 순두부·비빔밥\n30년 넘게 신오쿠보를 지킨 터줏대감. 돌솥 순두부찌개와 돌솥비빔밥이 시그니처. 서울 명동 맛 그대로라 한국 그리울 때 가장 먼저 생각나는 곳.",
    tip: "점심 런치 세트 ¥950. 현금 결제 선호, 카드도 가능",
    website: "tabelog.com/tokyo/A1304/A130401/13034521",
  },
  {
    rank: 4,
    emoji: "🐔",
    nameKo: "치맥포차 신오쿠보",
    nameEn: "Chimaek Pocha Shin-Okubo",
    address: "〒169-0072 東京都新宿区大久保1-12-1 2F",
    phone: "03-5937-6060",
    hours: "월-일 5pm-12am",
    rating: 4.1,
    ratingCount: "350+",
    why: "🐔 치킨·포차\n신오쿠보 골목의 허름한 한국식 포장마차 분위기. 겉바속촉 치킨에 생맥주 한 잔이면 서울 포차가 부럽지 않다. 혼술족부터 단체 회식까지 부담 없이 즐길 수 있다.",
    tip: "금·토 예약 필수. 양념치킨+간장치킨 반반 추천",
  },
  {
    rank: 5,
    emoji: "🥘",
    nameKo: "부대찌개 전문 오사카야",
    nameEn: "Budae Jjigae Osaka-ya",
    address: "〒169-0072 東京都新宿区大久保2-9-13",
    phone: "03-3204-5533",
    hours: "화-일 12pm-10pm, 월 휴무",
    rating: 4.0,
    ratingCount: "280+",
    why: "🥘 부대찌개·라면사리\n신오쿠보에서 부대찌개 전문점으로 유일하게 살아남은 집. 서울 의정부식 원조 레시피에 충실한 진한 육수와 넉넉한 햄·소시지가 그리운 한국 맛을 재현한다.",
    tip: "라면사리·치즈 추가 필수. 최소 2인분 주문",
  },
];

// ─── OSAKA ───────────────────────────────────────────────────────────────────

export const TOP5_FOOD_OSAKA: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "쓰루하시 후게쓰 본점",
    nameEn: "Tsuruhashi Fugetsu Honten",
    address: "〒537-0024 大阪府大阪市東成区東小橋3-17-27",
    phone: "06-6741-0736",
    hours: "화-일 11am-10pm, 월 휴무",
    rating: 4.4,
    ratingCount: "1,200+",
    why: "🥩 호르몬·야키니쿠\n쓰루하시 코리아타운 70년 역사의 전설. 재일동포 1세대가 개척한 오사카 야키니쿠 원조 격 식당. 호르몬(곱창) 구이를 처음 일본에 소개한 곳 중 하나로, 지금도 현지 교민들의 성지다.",
    tip: "호르몬 믹스 정식 ¥1,500. 주말 오픈런 필수",
    website: "tsuruhashi-fugetsu.com",
  },
  {
    rank: 2,
    emoji: "🍗",
    nameKo: "코리아타운 참숯 황소",
    nameEn: "Hwangso Charcoal BBQ Koreatown",
    address: "〒537-0025 大阪府大阪市東成区中道3-8-11",
    phone: "06-6975-2200",
    hours: "월-일 11:30am-11pm",
    rating: 4.3,
    ratingCount: "700+",
    why: "🍗 참숯 BBQ·갈비\n쓰루하시 이쿠노 코리아타운 중심부. 참숯 화로에 구운 갈비와 불고기가 일품. 재일동포 가족 모임과 귀향 교민의 단골 회식 장소로 어머니 손맛 같은 따뜻함이 있다.",
    tip: "갈비+불고기 세트 ¥2,800. 예약 권장",
  },
  {
    rank: 3,
    emoji: "🍲",
    nameKo: "이쿠노 설렁탕",
    nameEn: "Ikuno Seolleongtang",
    address: "〒544-0031 大阪府大阪市生野区鶴橋1-6-8",
    phone: "06-6717-3399",
    hours: "월-토 9am-8pm, 일 9am-5pm",
    rating: 4.2,
    ratingCount: "450+",
    why: "🍲 설렁탕·곰탕\n이쿠노구 재일동포 집중 거주 지역에서 40년째 이어온 설렁탕 전문점. 뿌연 사골 국물 한 그릇이면 일본 생활의 피로가 씻긴다. 이른 아침부터 열어 교민 어르신들의 아침 식사 명소.",
    tip: "기본 설렁탕 ¥950. 깍두기 리필 무료",
  },
  {
    rank: 4,
    emoji: "🌶️",
    nameKo: "쓰루하시 순두부 혜원",
    nameEn: "Tsuruhashi Sundubu Hyewon",
    address: "〒537-0024 大阪府大阪市東成区東小橋2-13-5",
    phone: "06-6743-5577",
    hours: "화-일 11am-9pm, 월 휴무",
    rating: 4.1,
    ratingCount: "320+",
    why: "🌶️ 순두부·김치찌개\n쓰루하시 시장 골목에 숨어있는 찌개 전문점. 칼칼한 순두부와 묵은지 김치찌개가 대표 메뉴. 오사카에서 진짜 한국 찌개 맛을 찾는 교민들의 입소문으로만 유지되는 곳.",
    tip: "순두부+밥+반찬 세트 ¥1,100. 현금 전용",
  },
  {
    rank: 5,
    emoji: "🍱",
    nameKo: "이쿠노 한정식",
    nameEn: "Ikuno Korean Table d'hote",
    address: "〒544-0034 大阪府大阪市生野区桃谷2-14-7",
    phone: "06-6716-8800",
    hours: "화-일 12pm-3pm, 6pm-10pm",
    rating: 4.5,
    ratingCount: "250+",
    why: "🍱 한정식·정갈한 한상\n이쿠노 코리아타운 안쪽, 재일동포 2세 오너 셰프가 운영하는 한정식집. 나물·전·조림·국이 갖춰진 정갈한 한상이 서울 한식당 부럽지 않다. 특별한 날 가족 모임 장소로 인기.",
    tip: "런치 한정식 ¥1,800, 저녁 ¥3,500~. 사전 예약 강력 권장",
  },
];

// ─── SEOUL ───────────────────────────────────────────────────────────────────

export const TOP5_FOOD_SEOUL: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍗",
    nameKo: "광장시장 마약김밥·빈대떡",
    nameEn: "Gwangjang Market Bindaetteok & Gimbap",
    address: "서울 종로구 창경궁로 88 광장시장",
    phone: "02-2267-0291",
    hours: "월-일 9am-11pm (점포마다 상이)",
    rating: 4.6,
    ratingCount: "5,000+",
    why: "🍗 빈대떡·마약김밥\n해외 오래 살다 돌아온 역이민자들이 첫 발걸음으로 향하는 곳. 100년 역사의 광장시장에서 기름 자글자글 빈대떡 한 장과 마약김밥 한 줄이면 '나 돌아왔다'는 실감이 온다. 외국에선 절대 재현 못 하는 그 맛.",
    tip: "빈대떡 ₩5,000, 마약김밥 4줄 ₩4,000. 현금 선호. 점심시간 가장 붐빔",
    website: "gwangjangmarket.co.kr",
  },
  {
    rank: 2,
    emoji: "🐖",
    nameKo: "이문설농탕",
    nameEn: "Imun Seolleongtang",
    address: "서울 종로구 우정국로 38-13",
    phone: "02-733-6526",
    hours: "월-일 7am-9pm",
    rating: 4.5,
    ratingCount: "3,000+",
    why: "🐖 설렁탕·도가니탕\n1904년 창업, 서울에서 가장 오래된 설렁탕 집. 역이민 1세대 어르신들이 '한국에 오면 꼭 한 번'이라고 말하는 100년 노포. 뽀얀 사골 국물 한 그릇에 한국의 뿌리가 담겨 있다.",
    tip: "설렁탕 ₩12,000, 도가니탕 ₩15,000. 일찍 가야 도가니 맛볼 수 있음",
    website: "imun-seolleongtang.com",
  },
  {
    rank: 3,
    emoji: "🥘",
    nameKo: "을지로 노가리골목",
    nameEn: "Euljiro Nogari Alley",
    address: "서울 중구 을지로3가 노가리골목 일대",
    hours: "월-일 4pm-12am (점포마다 상이)",
    rating: 4.3,
    ratingCount: "2,000+",
    why: "🥘 노가리·맥주\n을지로 뒷골목 황금빛 조명 아래 플라스틱 의자에 앉아 마시는 맥주와 노가리. 외국 생활에서 그리웠던 '서울의 밤' 그 자체다. 2030 역이민자들이 서울 귀환 첫 주에 찾는 필수 코스.",
    tip: "노가리 1마리 ₩3,000~, 맥주 ₩3,000. 현금 전용 가게 많음. 평일이 여유로움",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "진주회관",
    nameEn: "Jinju Hoegwan Kongguksu",
    address: "서울 중구 서소문로9길 19",
    phone: "02-753-5388",
    hours: "월-토 8am-9pm, 일 휴무",
    rating: 4.4,
    ratingCount: "1,800+",
    why: "🍜 콩국수·비빔밥\n1945년부터 이어온 콩국수 전문점. 해외에서 절대 먹을 수 없는 진한 국산 콩 국물이 역이민자의 영혼을 달래준다. 여름 한정 콩국수는 예약 없이는 먹기 힘들 정도로 인기.",
    tip: "콩국수 ₩12,000. 여름 한정 판매(6-8월). 오픈 30분 전 줄서기 권장",
  },
  {
    rank: 5,
    emoji: "🍖",
    nameKo: "마포 소금구이 골목",
    nameEn: "Mapo Salt-Grilled Pork Alley",
    address: "서울 마포구 공덕동 소금구이 골목 일대",
    hours: "월-일 5pm-11pm (점포마다 상이)",
    rating: 4.2,
    ratingCount: "1,500+",
    why: "🍖 소금구이·항정살\n마포 공덕 소금구이 골목은 해외 교포들이 귀국할 때마다 반드시 들르는 곳. 두툼한 항정살에 굵은 소금 한 꼬집, 참기름 한 방울이면 외국에서 그토록 그리웠던 '그 맛'이 온다.",
    tip: "1인 1만원대 중반. 현금+카드 모두 가능. 연탄불 구이집 고르기",
  },
];

// ─── BUSAN ───────────────────────────────────────────────────────────────────

export const TOP5_FOOD_BUSAN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍜",
    nameKo: "할매 밀면 원조",
    nameEn: "Halme Milmyeon Original",
    address: "부산 부산진구 가야대로784번길 15",
    phone: "051-894-5455",
    hours: "월-일 10am-8pm",
    rating: 4.5,
    ratingCount: "2,500+",
    why: "🍜 밀면\n부산 밀면의 역사를 쓴 원조집. 1950년 피난 시절 탄생한 부산 고유의 면 요리로, 이북 출신 피난민이 고향 냉면을 밀가루로 재현한 것이 뿌리. 역이민자에게 부산 하면 가장 먼저 떠오르는 그 맛.",
    tip: "물밀면·비빔밀면 ₩9,000. 여름엔 물밀면, 겨울엔 비빔밀면 추천",
  },
  {
    rank: 2,
    emoji: "🐷",
    nameKo: "쌍둥이 돼지국밥",
    nameEn: "Ssangdungi Dwaeji Gukbap",
    address: "부산 동래구 명륜로98번길 4",
    phone: "051-555-0696",
    hours: "월-일 24시간",
    rating: 4.4,
    ratingCount: "3,000+",
    why: "🐷 돼지국밥\n부산 돼지국밥 하면 쌍둥이. 24시간 운영하는 부산의 소울푸드 명소. 구수하고 진한 뼈 국물에 부드러운 수육이 들어간 돼지국밥 한 그릇이면 부산 귀환의 실감이 온다.",
    tip: "돼지국밥 ₩9,000. 새우젓으로 간 맞추기. 24시간이라 야식도 OK",
    website: "ssangdungi.com",
  },
  {
    rank: 3,
    emoji: "🦞",
    nameKo: "자갈치 시장 회센터",
    nameEn: "Jagalchi Market Hoe Center",
    address: "부산 중구 자갈치해안로 52 자갈치시장",
    phone: "051-245-2594",
    hours: "월-일 9am-10pm",
    rating: 4.3,
    ratingCount: "4,000+",
    why: "🦞 활어회·매운탕\n부산의 상징 자갈치 시장. 어시장 2층 회센터에서 직접 고른 활어를 바로 떠주는 싱싱한 회와 매운탕은 부산 역이민자라면 누구나 그리워하던 바로 그 경험. 바다 내음과 함께 부산이 돌아온다.",
    tip: "활어 kg당 시세 상이. 봄 도다리쑥국, 가을 전어회가 제철. 흥정 가능",
    website: "jagalchimarket.co.kr",
  },
  {
    rank: 4,
    emoji: "🍢",
    nameKo: "국제시장 씨앗호떡",
    nameEn: "Gukje Market Ssiat Hotteok",
    address: "부산 중구 신창동4가 국제시장 일대",
    hours: "월-일 9am-7pm (점포마다 상이)",
    rating: 4.4,
    ratingCount: "1,800+",
    why: "🍢 씨앗호떡·부산 길거리 음식\n부산 국제시장 씨앗호떡은 해외 교포들이 부산 오면 첫날 손에 들고 걷는 음식. 바삭한 호떡 안에 해바라기씨·아몬드·잣이 가득한 부산 고유의 길거리 간식. 해외에서는 절대 못 먹는 맛.",
    tip: "1개 ₩1,500. 줄 서서 먹는 곳 선택. 식어도 맛있지만 갓 구운 게 최고",
  },
  {
    rank: 5,
    emoji: "🍣",
    nameKo: "해운대 암남어촌계 횟집",
    nameEn: "Haeundae Amnam Fishermen's Village Hoe",
    address: "부산 해운대구 달맞이길 30 청사포 일대",
    hours: "월-일 10am-10pm (점포마다 상이)",
    rating: 4.2,
    ratingCount: "900+",
    why: "🍣 물회·모듬회\n청사포 어촌 횟집은 해운대 관광 횟집과 달리 어부 직거래 싱싱한 회를 합리적인 가격에 먹을 수 있는 현지인 장소. 파도 소리 들으며 물회 한 그릇이면 부산 재정착의 첫 페이지가 열린다.",
    tip: "물회 ₩13,000~, 모듬회 시세. 청사포 어촌계 직영 가게 선택 추천",
  },
];

// ─── SEOUL SETTLEMENT ────────────────────────────────────────────────────────

export const TOP5_SETTLE_SEOUL: Top5Item[] = [
  {
    rank: 1,
    emoji: "🏛️",
    nameKo: "재외동포청",
    nameEn: "Overseas Koreans Agency (OKA)",
    address: "인천광역시 미추홀구 소성로163번길 49",
    phone: "032-410-1000",
    hours: "월-금 9am-6pm",
    why: "🏛️ 역이민 원스톱 지원\n재외동포의 국내 정착을 전담 지원하는 정부 기관(2023년 신설). 재외동포 비자 발급부터 국내 정착 지원, 사회보험 연계, 취업·창업 컨설팅까지 역이민자가 가장 먼저 접촉해야 할 기관.",
    tip: "방문 전 홈페이지에서 사전 상담 예약 필수. 서울 사무소 별도 운영",
    website: "oka.go.kr",
  },
  {
    rank: 2,
    emoji: "🛂",
    nameKo: "서울출입국·외국인청",
    nameEn: "Seoul Immigration & Foreign Affairs Office",
    address: "서울 양천구 목동동로 151",
    phone: "1345",
    hours: "월-금 9am-6pm",
    why: "🛂 비자·체류 신고\n재외동포 F-4 비자 신청, 국적 회복, 외국국적동포 거소신고 등 체류 자격 관련 모든 행정을 처리하는 서울 주요 출입국 기관. 역이민 초기 90일 이내 거소 신고를 이 곳에서 해결한다.",
    tip: "1345 전화 사전 상담 후 방문. 전국 하이코리아(hikorea.go.kr) 온라인 신청 가능",
    website: "hikorea.go.kr",
  },
  {
    rank: 3,
    emoji: "🤝",
    nameKo: "서울글로벌센터",
    nameEn: "Seoul Global Center",
    address: "서울 종로구 종로 38 서울글로벌센터빌딩",
    phone: "02-2075-4180",
    hours: "월-금 9am-6pm",
    why: "🤝 외국어 법률·세무·의료 상담\n영어·중국어·일본어 등 다국어 법률·세무·부동산·의료 무료 상담 제공. 해외 오래 살다 한국 행정 체계에 낯선 역이민자들이 한국 생활 초기 가장 유용하게 활용하는 센터.",
    tip: "외국어 상담은 사전 예약 권장. 세무·부동산 한국어 상담은 당일 방문 가능",
    website: "seoul.go.kr/globalcenter",
  },
  {
    rank: 4,
    emoji: "💼",
    nameKo: "서울일자리플러스센터",
    nameEn: "Seoul Job Plus Center",
    address: "서울 중구 남대문로5가 서울고용복지플러스센터",
    phone: "02-6953-7114",
    hours: "월-금 9am-6pm",
    why: "💼 취업·이력서·커리어 상담\n해외 경력을 가진 역이민자의 한국 취업 재진입을 돕는 서울시 공식 취업 지원 기관. 외국어 가능자 특화 구인 데이터베이스, 이력서 컨설팅, 면접 코칭 프로그램 운영.",
    tip: "재외동포 귀환 특화 프로그램은 사전 전화 문의. 고용24(work.go.kr) 연계",
    website: "work.go.kr",
  },
  {
    rank: 5,
    emoji: "🏠",
    nameKo: "SH 서울주택도시공사 귀환동포 임대주택",
    nameEn: "SH Seoul Housing & Communities Corporation",
    address: "서울 강남구 개포로621",
    phone: "1600-3456",
    hours: "월-금 9am-6pm",
    why: "🏠 임대주택·주거 정착\n서울시 공공 임대주택 신청 창구. 재외동포 F-4 비자 소지자도 일정 요건 충족 시 공공임대 신청 자격 부여. 한국 첫 귀환 후 주거 안정이 가장 급한 역이민자에게 현실적인 대안을 제공.",
    tip: "SH 청약 포털(i-sh.co.kr)에서 자격 조건 선확인 후 신청. 대기자 많아 조기 등록 권장",
    website: "i-sh.co.kr",
  },
];

// ─── SEOUL EXPLORE ───────────────────────────────────────────────────────────

export const TOP5_EXPLORE_SEOUL: Top5Item[] = [
  {
    rank: 1,
    emoji: "🏯",
    nameKo: "경복궁",
    nameEn: "Gyeongbokgung Palace",
    address: "서울 종로구 사직로 161",
    phone: "02-3700-3900",
    hours: "수-월 9am-6pm (화 휴무), 야간 개방 시즌 별도",
    rating: 4.8,
    ratingCount: "50,000+",
    why: "🏯 조선 5대 궁궐\n서울 귀환 역이민자라면 이 곳에 서야 '내가 돌아왔다'는 게 실감난다. 600년 조선의 심장. 한복 입고 광화문 앞에 서면 해외 수십 년이 주마등처럼 지나간다. 한국인의 정체성이 이 돌 하나하나에 새겨져 있다.",
    tip: "한복 착용 시 무료 입장. 수문장 교대식 오전 10시, 오후 2시. 야간 개방(봄·가을) 예약 필수",
    website: "royalpalace.go.kr",
  },
  {
    rank: 2,
    emoji: "🏘️",
    nameKo: "북촌 한옥마을",
    nameEn: "Bukchon Hanok Village",
    address: "서울 종로구 계동길 일대",
    hours: "상시 개방 (일부 시설 09am-6pm)",
    rating: 4.6,
    ratingCount: "20,000+",
    why: "🏘️ 한옥·전통 골목\n경복궁과 창덕궁 사이 북촌은 600년 서울의 결이 그대로 남아있는 공간. 기와 처마 아래 좁은 골목을 걷다 보면 외국에서 머릿속으로만 그리던 '한국'이 눈앞에 펼쳐진다. 역이민 첫 주 산책 최고 코스.",
    tip: "이른 아침(8am 이전) 또는 평일 방문 시 한적. 주민 거주 공간이므로 조용히 관람",
  },
  {
    rank: 3,
    emoji: "🌊",
    nameKo: "한강공원 (여의도·반포)",
    nameEn: "Han River Park (Yeouido & Banpo)",
    address: "서울 영등포구 여의동로 330 (여의도) / 서울 서초구 반포동 (반포)",
    hours: "월-일 24시간",
    rating: 4.7,
    ratingCount: "30,000+",
    why: "🌊 한강·치맥·야경\n한강은 서울의 심장이다. 해외 살면서 '한강 치맥'을 상상한 적 없는 교포가 없을 것. 반포 달빛무지개분수 야경, 여의도 봄 벚꽃, 한강 자전거. 한국에 살고 있다는 사실이 가장 실감나는 공간.",
    tip: "여의도 배달앱(배민·요기요) 이용해 한강공원 직접 배달 가능. 자전거 대여 '따릉이' 앱 설치 추천",
    website: "hangang.seoul.go.kr",
  },
  {
    rank: 4,
    emoji: "🎵",
    nameKo: "홍대 거리",
    nameEn: "Hongdae Street",
    address: "서울 마포구 와우산로 일대 홍대입구역 주변",
    hours: "상시 개방 (음식점·카페 11am~새벽)",
    rating: 4.5,
    ratingCount: "25,000+",
    why: "🎵 젊음·문화·인디 음악\n홍대는 한국 청년 문화의 진원지. 해외에서 유튜브로 보던 한국 길거리 공연, 인디 밴드, 힙스터 카페가 모두 살아있다. 2030 역이민자들이 '한국의 지금'을 가장 빠르게 흡수할 수 있는 동네.",
    tip: "주말 저녁 홍대 버스킹 거리 필수. 클럽 문화는 자정 이후. 카카오맵으로 숨은 카페 탐색",
  },
  {
    rank: 5,
    emoji: "🛍️",
    nameKo: "명동",
    nameEn: "Myeongdong",
    address: "서울 중구 명동길 일대",
    hours: "상시 개방 (상점 10am-10pm)",
    rating: 4.3,
    ratingCount: "40,000+",
    why: "🛍️ 쇼핑·길거리 음식·K-뷰티\n명동은 역이민자가 한국 물가 감각을 되찾는 공간. 최신 K-뷰티 트렌드, 길거리 음식 순례, 환전소. 오래 전 한국을 기억하는 교포에게는 변한 것과 변하지 않은 것이 공존하는 시간여행 같은 곳.",
    tip: "명동교자 칼국수(02-776-5348) 줄 서서 먹기는 필수 코스. 환전은 명동 사설 환전소가 은행보다 유리",
  },
];

// ─── BUSAN SETTLEMENT ────────────────────────────────────────────────────────

export const TOP5_SETTLE_BUSAN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🛂",
    nameKo: "부산출입국·외국인청",
    nameEn: "Busan Immigration & Foreign Affairs Office",
    address: "부산 남구 고동골로 67",
    phone: "051-461-1341",
    hours: "월-금 9am-6pm",
    why: "🛂 비자·거소신고·국적 업무\n부산 권역 재외동포의 F-4 비자, 거소신고, 국적 회복 등 체류 자격 관련 행정 원스톱 처리. 부산·경남 귀환 역이민자라면 입국 후 90일 이내 반드시 방문해야 할 첫 번째 기관.",
    tip: "하이코리아(hikorea.go.kr) 온라인 사전 신청 후 방문하면 대기 시간 단축",
    website: "hikorea.go.kr",
  },
  {
    rank: 2,
    emoji: "🤝",
    nameKo: "부산글로벌도시재단",
    nameEn: "Busan Global City Foundation",
    address: "부산 연제구 중앙대로 1001 부산시청 내",
    phone: "051-515-0101",
    hours: "월-금 9am-6pm",
    why: "🤝 다국어 정착 지원·법률 상담\n외국어 무료 법률·세무·의료 상담, 취업 지원, 한국 생활 적응 프로그램 운영. 부산 귀환 역이민자에게 서울 글로벌센터와 동일한 역할을 하는 부산 대표 정착 지원 기관.",
    tip: "영어·일본어·중국어 상담 가능. 방문 전 전화 예약 권장",
    website: "bgcf.or.kr",
  },
  {
    rank: 3,
    emoji: "💼",
    nameKo: "부산고용복지플러스센터",
    nameEn: "Busan Employment Welfare Plus Center",
    address: "부산 동구 중앙대로 425",
    phone: "051-461-2800",
    hours: "월-금 9am-6pm",
    why: "💼 취업·실업급여·창업 상담\n한국 귀환 후 취업 재진입을 위한 공식 창구. 해외 경력 인정 상담, 이력서 번역·컨설팅, 외국어 특기자 구인 정보 연결. 역이민 후 경력 단절이 걱정된다면 첫 방문지.",
    tip: "워크넷(work.go.kr) 사전 이력서 등록 후 방문. 실업급여는 고용보험 피보험자만 해당",
    website: "work.go.kr",
  },
  {
    rank: 4,
    emoji: "🏠",
    nameKo: "부산도시공사 임대주택",
    nameEn: "Busan Metropolitan City Urban Corporation Housing",
    address: "부산 사하구 낙동대로 398번길 12",
    phone: "1600-0890",
    hours: "월-금 9am-6pm",
    why: "🏠 공공임대·주거 안정\n부산 공공임대주택 신청 창구. 재외동포 F-4 비자 소지자도 요건 충족 시 청약 가능. 부산 귀환 역이민자에게 서울 대비 합리적인 임대료와 쾌적한 환경의 공공임대 대안을 제공.",
    tip: "BMC 홈페이지(bmc.busan.kr)에서 자격 조건 먼저 확인. 해운대·수영구 인기 단지는 경쟁률 높음",
    website: "bmc.busan.kr",
  },
  {
    rank: 5,
    emoji: "📋",
    nameKo: "부산시 행복민원실 (재외동포 창구)",
    nameEn: "Busan City Hall Happy Civil Affairs (Overseas Korean Window)",
    address: "부산 연제구 중앙대로 1001 부산시청 1층",
    phone: "051-888-1000",
    hours: "월-금 9am-6pm",
    why: "📋 전입신고·주민등록·각종 민원\n귀환 후 주민등록 복원, 전입신고, 가족관계등록 등 한국 생활 기반을 다시 세우는 모든 서류를 한 곳에서 처리. 역이민 행정의 첫 관문으로 모든 것이 여기서 시작된다.",
    tip: "주민등록 복원 시 국적 확인 서류 지참 필수. 정부24(gov.kr) 온라인 신청 가능 항목 사전 확인",
    website: "busan.go.kr",
  },
];

// ─── BUSAN EXPLORE ───────────────────────────────────────────────────────────

export const TOP5_EXPLORE_BUSAN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🏖️",
    nameKo: "해운대 해수욕장",
    nameEn: "Haeundae Beach",
    address: "부산 해운대구 해운대해변로 264",
    hours: "상시 개방 (여름 공식 개장 7-8월)",
    rating: 4.7,
    ratingCount: "30,000+",
    why: "🏖️ 부산의 상징·백사장\n부산 하면 해운대. 해외 어디에서도 이 느낌은 재현할 수 없다. 백사장 1.8km를 맨발로 걸으면 부산으로 돌아온 실감이 파도처럼 밀려온다. 역이민 후 가족과 첫 주말 오후를 보낼 최고의 장소.",
    tip: "성수기(7-8월) 극도로 혼잡. 비수기 봄·가을 해운대가 훨씬 여유롭고 아름다움. 해운대 달맞이길 야경도 필수",
    website: "haeundae.go.kr",
  },
  {
    rank: 2,
    emoji: "🌉",
    nameKo: "광안리 해수욕장·광안대교",
    nameEn: "Gwangalli Beach & Gwangan Bridge",
    address: "부산 수영구 광안해변로 219",
    hours: "상시 개방",
    rating: 4.6,
    ratingCount: "20,000+",
    why: "🌉 야경·분위기·힙한 카페\n광안대교를 배경으로 한 광안리 야경은 세계 어디 내놓아도 빠지지 않는다. 해운대보다 현지인 분위기가 강하고, 주변 수제 맥줏집·감각적 카페가 즐비해 부산 재정착 후 '내 동네'로 삼기 좋은 곳.",
    tip: "불꽃축제(10월) 때 광안리 전체가 마비됨. 평일 저녁 야경+맥주가 부산 현지인 코스",
  },
  {
    rank: 3,
    emoji: "🎨",
    nameKo: "감천문화마을",
    nameEn: "Gamcheon Culture Village",
    address: "부산 사하구 감내2로 203",
    phone: "051-291-4130",
    hours: "월-일 9am-6pm",
    rating: 4.4,
    ratingCount: "15,000+",
    why: "🎨 6.25 피난민 역사·벽화마을\n한국전쟁 피난민들이 산비탈에 다닥다닥 지은 집들이 지금은 부산의 가장 독특한 문화 공간이 됐다. 역이민자에게는 한국의 아픈 역사를 몸으로 느끼는 장소. 좁은 골목 하나하나에 사람 냄새가 배어있다.",
    tip: "관광 안내소에서 도장 지도 구매(₩2,000), 미션 완료 시 기념품 증정. 오르막 많아 편한 신발 필수",
    website: "gamcheon.or.kr",
  },
  {
    rank: 4,
    emoji: "🐟",
    nameKo: "자갈치 시장",
    nameEn: "Jagalchi Market",
    address: "부산 중구 자갈치해안로 52",
    phone: "051-713-8000",
    hours: "월-일 9am-10pm",
    rating: 4.5,
    ratingCount: "18,000+",
    why: "🐟 수산시장·부산 정체성\n'아지매, 사이소!'의 자갈치 시장은 부산의 영혼. 새벽 경매부터 저녁 야시장까지, 생선 비린내와 아주머니들의 호객 소리가 뒤섞인 이 곳은 부산 역이민자가 '집에 돌아왔다'를 가장 강하게 느끼는 공간.",
    tip: "2층 식당에서 직접 고른 활어 조리 가능. 봄 도다리쑥국(3-4월), 겨울 대방어 시즌 추천",
    website: "jagalchimarket.co.kr",
  },
  {
    rank: 5,
    emoji: "🌲",
    nameKo: "태종대",
    nameEn: "Taejongdae",
    address: "부산 영도구 전망로 24",
    phone: "051-405-2004",
    hours: "월-일 9am-6pm",
    rating: 4.6,
    ratingCount: "12,000+",
    why: "🌲 절벽·등대·바다 전망\n영도 남단 해안 절벽의 태종대는 부산 시민의 자부심. 울창한 숲길을 걷다 갑자기 펼쳐지는 망망대해 앞에 서면 지난 이민 세월의 무게가 한꺼번에 쏟아진다. 혼자 조용히 오기 좋은 역이민자의 사색 공간.",
    tip: "순환열차(다누비) ₩3,000 이용 편리. 모자 절벽 전망대와 등대박물관 함께 방문. 주차 혼잡, 대중교통 권장",
    website: "taejongdae.bisco.or.kr",
  },
];
