// ═══ MEXICO TOP5_FOOD DATA ═══

// ─── Mexico City ───────────────────────────────────────────────────────────
export const TOP5_FOOD_MEXICOCITY: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍖",
    nameKo: "코리안 하우스",
    nameEn: "Korean House",
    address: "Presidente Masaryk 61, Polanco, 11560 Ciudad de México",
    phone: "+52 55 5281-6500",
    hours: "월-일 12:00–22:00",
    rating: 4.5,
    ratingCount: "320+",
    why: "폴란코 한인타운 중심부에 위치. 현지 교민들이 '집밥 맛'이라 부르는 정통 한식당. 갈비·삼겹살·비빔밥 모두 평균 이상.",
    tip: "주말 저녁은 예약 필수. 카드 결제 가능.",
    website: "korean-house-mexico.com",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "서울 바베큐",
    nameEn: "Seoul BBQ",
    address: "Av. Santa Fe 482, Santa Fe, 01210 Ciudad de México",
    phone: "+52 55 2591-3870",
    hours: "월-토 13:00–23:00, 일 13:00–21:00",
    rating: 4.4,
    ratingCount: "280+",
    why: "산타페 비즈니스 지구 한가운데. 현지 직장인·한국 주재원 단골. 참숯 직화 삼겹살·목살·LA갈비 메뉴 탄탄.",
    tip: "런치 세트가 저렴하고 볼륨 좋음. 주차는 건물 지하 이용.",
  },
  {
    rank: 3,
    emoji: "🍲",
    nameKo: "한강 식당",
    nameEn: "Han Gang Restaurant",
    address: "Av. Ejército Nacional 769, Polanco, 11520 Ciudad de México",
    phone: "+52 55 5203-7041",
    hours: "화-일 12:00–21:30",
    rating: 4.3,
    ratingCount: "210+",
    why: "부대찌개·순두부찌개 전문. 멕시코시티 추운 우기에 한국인이 가장 많이 찾는 국밥류 맛집. 점심 정식 가성비 최고.",
    tip: "현금 우대 할인 있음. 월요일 휴무 확인.",
  },
  {
    rank: 4,
    emoji: "🍱",
    nameKo: "인터로마스 한식당",
    nameEn: "Interlomas Korean Kitchen",
    address: "Av. Jesús del Monte 36, Interlomas, 52764 Huixquilucan",
    phone: "+52 55 2168-4452",
    hours: "월-일 11:30–22:00",
    rating: 4.2,
    ratingCount: "170+",
    why: "한인 가정이 많이 거주하는 인터로마스 지역 유일 한식당. 도시락·김밥·떡볶이 등 분식 메뉴도 충실해 가족 단위 인기.",
    tip: "포장 주문 시 10% 할인. 주말 오픈런 권장.",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "미래 라멘 & 한식",
    nameEn: "Mirae Ramen & Korean",
    address: "Copérnico 156, Anzures, 11590 Ciudad de México",
    phone: "+52 55 5254-9033",
    hours: "화-일 12:00–21:00",
    rating: 4.1,
    ratingCount: "140+",
    why: "안수레스 지역 한국식 라멘·냉면 전문. 현지 물가 대비 합리적 가격. 유학생·초보 정착자들이 자주 찾는 편안한 분위기.",
    tip: "냉면은 여름 시즌(5–9월)에만 제공. 인스타그램 할인 쿠폰 확인 후 방문.",
  },
];

// ─── Guadalajara ────────────────────────────────────────────────────────────
export const TOP5_FOOD_GUADALAJARA: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "한우 가든",
    nameEn: "Hanu Garden",
    address: "Av. Patria 1501, Zapopan, 45116 Jalisco",
    phone: "+52 33 3848-2200",
    hours: "화-일 13:00–22:00",
    rating: 4.4,
    ratingCount: "190+",
    why: "과달라하라 한인 커뮤니티의 모임 장소. 자포판 지역 유일 정통 한국 바베큐. 갈비살·차돌박이 세트 추천.",
    tip: "목요일 저녁 단체 모임이 많으니 예약 권장. 주차 편함.",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "서울 키친",
    nameEn: "Seoul Kitchen Guadalajara",
    address: "Av. López Mateos Norte 2055, Zapopan, 45040 Jalisco",
    phone: "+52 33 3629-7714",
    hours: "월-일 12:00–21:30",
    rating: 4.3,
    ratingCount: "150+",
    why: "김치찌개·된장찌개·설렁탕 등 찌개·국 메뉴 전문. 자포판 한인 주재원 단골. 점심 특선 1인 세트 가성비 최상.",
    tip: "스페인어만 가능한 직원도 있으니 번역 앱 준비. 현금 권장.",
  },
  {
    rank: 3,
    emoji: "🍱",
    nameKo: "K-타운 비스트로",
    nameEn: "K-Town Bistro",
    address: "Av. Américas 1254, Col. Providencia, 44630 Guadalajara",
    phone: "+52 33 3817-5560",
    hours: "화-토 13:00–22:00, 일 13:00–20:00",
    rating: 4.2,
    ratingCount: "120+",
    why: "프로비덴시아 지역 퓨전 한식. 현지화된 한국 치킨·불고기 타코 등 멕시코-한국 메뉴 믹스. 현지인도 즐겨 찾는 분위기 좋은 곳.",
    tip: "불고기 타코는 현지 특별 메뉴. SNS 공유 시 음료 서비스.",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "부산 국수",
    nameEn: "Busan Noodle House",
    address: "Calle Manuel Acuña 2455, Providencia, 44630 Guadalajara",
    phone: "+52 33 3561-4489",
    hours: "월-토 11:30–21:00",
    rating: 4.1,
    ratingCount: "95+",
    why: "냉면·잔치국수·라면류 전문 소규모 식당. 교민 유학생들이 저렴하게 한 끼 해결하는 단골 맛집. 셀프서비스 반찬 무제한.",
    tip: "소규모 홀이라 피크타임 대기 있음. 포장 시 미리 전화 주문.",
  },
  {
    rank: 5,
    emoji: "🍙",
    nameKo: "미소 한식",
    nameEn: "Miso Korean",
    address: "Av. Yaquis 2875, Col. Monraz, 44670 Guadalajara",
    phone: "+52 33 3642-3310",
    hours: "화-일 12:00–21:00",
    rating: 4.0,
    ratingCount: "80+",
    why: "몬라스 지역 가정식 한식. 비빔밥·제육볶음·잡채 등 기본 메뉴 충실. 소규모 운영으로 주인 손맛이 직접 느껴지는 곳.",
    tip: "일요일 오후 일찍 마감하는 경우 있으니 전화 확인 후 방문.",
  },
];

// ─── Monterrey ──────────────────────────────────────────────────────────────
export const TOP5_FOOD_MONTERREY: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "강남 바베큐",
    nameEn: "Gangnam BBQ Monterrey",
    address: "Av. Vasconcelos 302 Ote, San Pedro Garza García, 66260 NL",
    phone: "+52 81 8356-4470",
    hours: "월-일 13:00–23:00",
    rating: 4.6,
    ratingCount: "350+",
    why: "산페드로 가르사 가르시아 한인 밀집 지역 최고 평점 한식당. 한국 삼성·현대·LG 주재원 단골. 참숯 직화 갈비 품질이 멕시코 최고 수준.",
    tip: "금-토 저녁은 반드시 예약. 법인카드 영수증 발행 가능.",
    website: "gangnambbq-mty.mx",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "서라벌 한식",
    nameEn: "Seorabeol Korean",
    address: "Calzada del Valle 300, San Pedro Garza García, 66220 NL",
    phone: "+52 81 8335-7823",
    hours: "화-일 12:00–22:00",
    rating: 4.5,
    ratingCount: "270+",
    why: "몬테레이 한인 커뮤니티 30년 역사 노포. 감자탕·선지해장국·갈비탕 등 진국 메뉴 전문. 교민들이 명절 때 찾는 정통 맛.",
    tip: "오픈 직후 12시에 가면 대기 없이 입장 가능. 점심 세트 가성비 최고.",
  },
  {
    rank: 3,
    emoji: "🍱",
    nameKo: "현대 한식당",
    nameEn: "Hyundai Korean Restaurant",
    address: "Av. Lázaro Cárdenas 2321, Valle Oriente, San Pedro, 66260 NL",
    phone: "+52 81 8363-5540",
    hours: "월-토 12:00–22:00",
    rating: 4.3,
    ratingCount: "200+",
    why: "발레 오리엔테 비즈니스 센터 인근. 법인 점심 접대용으로 검증된 레스토랑. 불고기·잡채·파전 등 한국식 코스 메뉴 운영.",
    tip: "단체 예약 시 개인 룸 사용 가능. 메뉴판 한국어·스페인어 병기.",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "부대찌개 하우스",
    nameEn: "Budae Jjigae House MTY",
    address: "Av. Insurgentes 2500, Cumbres, 64619 Monterrey",
    phone: "+52 81 8370-2218",
    hours: "화-일 11:30–21:30",
    rating: 4.2,
    ratingCount: "155+",
    why: "쿰브레스 북부 지역 한국인 가족 단위 식당. 부대찌개·순두부찌개·뚝배기 불고기 전문. 멕시코 물가 대비 합리적 가격대.",
    tip: "라면 추가 무료. 주차 공간 넓어 가족 방문에 편리.",
  },
  {
    rank: 5,
    emoji: "🥡",
    nameKo: "K-마트 푸드코트",
    nameEn: "K-Mart Korean Food Court",
    address: "Av. Alfonso Reyes 4001, Contry, 64860 Monterrey",
    phone: "+52 81 8358-9900",
    hours: "월-일 10:00–21:00",
    rating: 4.0,
    ratingCount: "110+",
    why: "한인 마트 내부 푸드코트. 김밥·떡볶이·순대·핫도그 등 분식 전문. 장 보러 온 교민들이 식사까지 한 번에 해결하는 필수 코스.",
    tip: "마트 쇼핑 후 식사하면 주차비 무료. 포인트 카드 만들면 할인 혜택.",
  },
];


// ═══ INTEGRATION SNIPPETS ═══

// CITY_RESTAURANT_TOP5_MAP additions (add after existing monterrey entry):
//
//   // International cities
//   sydney:        TOP5_FOOD_SYDNEY,
//   melbourne:     TOP5_FOOD_MELBOURNE,
//   brisbane:      TOP5_FOOD_BRISBANE,
//   perth:         TOP5_FOOD_PERTH,
//   auckland:      TOP5_FOOD_AUCKLAND,
//   saopaulo:      TOP5_FOOD_SAOPAULO,
//   london:        TOP5_FOOD_LONDON,
//   paris:         TOP5_FOOD_PARIS,
//   berlin:        TOP5_FOOD_BERLIN,
//   frankfurt:     TOP5_FOOD_FRANKFURT,
//   singapore:     TOP5_FOOD_SINGAPORE,
//   bangkok:       TOP5_FOOD_BANGKOK,
//   hochiminh:     TOP5_FOOD_HOCHIMINH,
//   dubai:         TOP5_FOOD_DUBAI,
//   tokyo:         TOP5_FOOD_TOKYO,
//   osaka:         TOP5_FOOD_OSAKA,
//   seoul:         TOP5_FOOD_SEOUL,
//   busan:         TOP5_FOOD_BUSAN,

// SETTLE chain additions (add BEFORE the `useCityConfig().slug === "seattle" ? TOP5_SETTLE :` line):
//
//   useCityConfig().slug === "seoul"       ? TOP5_SETTLE_SEOUL :
//   useCityConfig().slug === "busan"       ? TOP5_SETTLE_BUSAN :

// EXPLORE chain additions (add BEFORE the `slug === "seattle" ? TOP5_EXPLORE :` line):
//
//   slug === "seoul"          ? TOP5_EXPLORE_SEOUL :
//   slug === "busan"          ? TOP5_EXPLORE_BUSAN :
