// ═══ OCEANIA & S.AMERICA TOP5_FOOD DATA ═══

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── SYDNEY ───────────────────────────────────────────────────────────────────

export const TOP5_FOOD_SYDNEY: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍖",
    nameKo: "진고개 한국식당",
    nameEn: "Jingogae Korean Restaurant",
    address: "Shop 5, 1 Homebush Bay Dr, Strathfield NSW 2135",
    phone: "+61 2 9764 1188",
    hours: "월–금 11:30–14:30, 17:30–22:00 / 주말 11:00–22:30",
    rating: 4.5,
    ratingCount: "680",
    why: "스트라스필드 코리아타운 한복판에 위치한 갈비 전문점으로, 시드니 한인들이 가족 모임 때 첫 손꼽는 곳입니다. 두툼한 LA갈비와 된장찌개가 호주 현지인들 사이에서도 소문이 자자합니다. 30년 이상 한자리를 지켜온 노포라 손님 맞이 온도가 남다릅니다.",
    tip: "주말 저녁은 대기가 길어 전화 예약 필수. 세트 메뉴가 단품보다 10% 저렴합니다.",
    website: "jingogae.com.au",
  },
  {
    rank: 2,
    emoji: "🍜",
    nameKo: "이스트우드 감자탕",
    nameEn: "Eastwood Gamjatang",
    address: "167 Rowe St, Eastwood NSW 2122",
    phone: "+61 2 9858 3377",
    hours: "매일 11:00–23:00",
    rating: 4.4,
    ratingCount: "520",
    why: "이스트우드 한인 상가 중심부에 자리한 감자탕·해장국 전문점으로, 유학생과 워킹홀리데이 한인들의 든든한 아지트입니다. 뼈대가 크고 국물이 진해 호주의 긴 겨울밤을 녹여 줍니다. 가격 대비 양이 넉넉해 저예산 정착 초기에 특히 환영받습니다.",
    tip: "점심 특선(A$18 내외)은 밥·반찬 포함으로 가성비 최고. 국물은 추가 주문 가능.",
  },
  {
    rank: 3,
    emoji: "🔥",
    nameKo: "서울BBQ 시드니",
    nameEn: "Seoul BBQ Sydney",
    address: "Suite 2, 275 Pitt St, Sydney CBD NSW 2000",
    phone: "+61 2 9267 9922",
    hours: "월–토 12:00–15:00, 17:30–23:00 / 일 17:00–22:00",
    rating: 4.3,
    ratingCount: "910",
    why: "시드니 CBD 중심부에서 테이블 직화 구이를 즐길 수 있는 곳으로, 직장인 회식과 현지 친구와의 외식 자리로 인기가 높습니다. 삼겹살·목살뿐 아니라 한국식 소주·막걸리도 잘 갖춰져 있습니다. 환기 시스템이 잘 되어 있어 옷에 냄새가 적게 배는 것도 장점입니다.",
    tip: "2인 세트(삼겹살+목살+냉면)가 가장 인기 있으며, 예약 시 창가 자리 요청 가능.",
    website: "seoulbbqsydney.com.au",
  },
  {
    rank: 4,
    emoji: "🍱",
    nameKo: "한강분식",
    nameEn: "Han River Bunsik",
    address: "Shop 3, 3 Albert Rd, Strathfield NSW 2135",
    phone: "+61 2 9746 0033",
    hours: "월–토 09:00–21:00 / 일 10:00–20:00",
    rating: 4.2,
    ratingCount: "340",
    why: "떡볶이·순대·튀김·라볶이 등 한국 길거리 음식을 한자리에서 맛볼 수 있는 스트라스필드 대표 분식집입니다. 유학생들이 고향의 맛이 그리울 때 자주 찾으며, 음료까지 포함해 A$15 안에 배를 채울 수 있습니다. 도착하자마자 한국에 온 것 같은 편안함을 주는 공간입니다.",
    tip: "계란 추가는 무료. 포장 주문 시 미리 전화하면 대기 시간 단축.",
  },
  {
    rank: 5,
    emoji: "🍣",
    nameKo: "오모이데 한일포차",
    nameEn: "Omoide Korean-Japanese Izakaya",
    address: "42 Erskineville Rd, Newtown NSW 2042",
    phone: "+61 2 9519 5544",
    hours: "화–일 17:00–24:00 / 월 휴무",
    rating: 4.4,
    ratingCount: "460",
    why: "뉴타운 감성 골목에 자리한 한일 퓨전 포차로, 한국식 닭발·파전과 일본식 야키토리를 함께 즐길 수 있어 다국적 친구들과의 모임 장소로 제격입니다. 인테리어가 서울 홍대 골목 느낌이라 현지 MZ 세대 한인들 사이에서 SNS 핫플로 알려져 있습니다. 소주 칵테일 메뉴가 다양하고 영어 메뉴판이 잘 갖춰져 있어 비한인 손님도 부담 없이 올 수 있습니다.",
    tip: "화요일은 소주 1병 무료 이벤트 진행. 예약 없이 방문 시 바 자리 이용 가능.",
  },
];

// ─── MELBOURNE ────────────────────────────────────────────────────────────────

export const TOP5_FOOD_MELBOURNE: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "박스힐 목장",
    nameEn: "Box Hill Mokjang Korean BBQ",
    address: "946 Whitehorse Rd, Box Hill VIC 3128",
    phone: "+61 3 9898 2255",
    hours: "매일 11:30–22:30",
    rating: 4.6,
    ratingCount: "820",
    why: "멜버른 한인 커뮤니티의 심장부인 박스힐에서 10년 이상 운영된 한국식 바베큐 맛집입니다. 직접 숯불을 사용해 굽는 방식 덕분에 고기 향이 압도적으로 좋고, 반찬 가짓수도 10가지 이상으로 넉넉합니다. 한인 교회 주일 점심 식사 장소로도 유명해 주말에는 일찍 자리가 가득 찹니다.",
    tip: "숯불 자리는 수량이 한정되어 있으니 사전 예약 강력 권장. 된장찌개 단품 추가 추천.",
    website: "boxhillmokjang.com.au",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "한마음 순두부",
    nameEen: "Hanmaeum Sundubu",
    nameEn: "Hanmaeum Sundubu",
    address: "2/855 Centre Rd, Bentleigh East VIC 3165",
    phone: "+61 3 9570 8811",
    hours: "화–일 11:00–21:30 / 월 휴무",
    rating: 4.4,
    ratingCount: "390",
    why: "멜버른 남동부 한인 밀집 지역인 벤틀리에 위치한 순두부·비빔밥 전문점으로, 담백하고 건강한 한식을 찾는 이들에게 입소문이 자자합니다. 국산 콩으로 직접 만든 두부를 사용해 식감과 깊이가 남다르며, 어르신부터 어린이까지 즐길 수 있는 순한 맛 옵션도 있습니다. 이민 초기 한국 가정식이 그리울 때 가장 먼저 떠오르는 곳입니다.",
    tip: "매주 수요일은 런치 세트 10% 할인. 주차는 가게 뒤편 무료 주차장 이용.",
  },
  {
    rank: 3,
    emoji: "🍛",
    nameKo: "강남스타일 분식&카페",
    nameEn: "Gangnam Style Bunsik & Cafe",
    address: "Shop 12, 1 Main St, Box Hill VIC 3128",
    phone: "+61 3 9899 4400",
    hours: "매일 09:00–21:00",
    rating: 4.3,
    ratingCount: "570",
    why: "박스힐 쇼핑몰 안에 자리한 한국 분식·카페로, 아메리카노 한 잔과 함께 떡볶이·김밥을 즐길 수 있어 멜버른 한인 유학생들의 일상 공간입니다. 한국에서 공수한 음료 재료로 만든 달고나 라떼·흑당 버블티가 특히 유명합니다. 무료 와이파이와 콘센트가 있어 과제하면서 식사하기에도 딱 좋습니다.",
    tip: "김밥은 오후 2시 이후 품절되는 경우가 많으므로 점심 시간 전 방문 추천.",
  },
  {
    rank: 4,
    emoji: "🔥",
    nameKo: "서울 불닭 멜버른",
    nameEn: "Seoul Buldak Melbourne",
    address: "267 Swanston St, Melbourne CBD VIC 3000",
    phone: "+61 3 9654 7733",
    hours: "월–목 11:30–22:00 / 금–토 11:30–23:00 / 일 12:00–21:00",
    rating: 4.2,
    ratingCount: "750",
    why: "CBD 한복판에서 불닭·닭갈비·치즈닭갈비를 즐길 수 있어 직장인과 관광객 모두에게 인기입니다. 매운맛 단계를 1~5단계로 선택할 수 있어 매운 음식에 익숙지 않은 현지 친구들도 함께 방문할 수 있습니다. 닭갈비 볶음밥 마무리까지 주문하면 한 끼가 완성됩니다.",
    tip: "3단계 이상은 정말 맵습니다. 생맥주나 우유를 함께 주문하면 화끈함을 달래 줍니다.",
    website: "seoulbuldak.com.au",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "도봉 냉면·만두",
    nameEn: "Dobong Naengmyeon & Mandu",
    address: "71 Elgar Rd, Box Hill North VIC 3129",
    phone: "+61 3 9890 1122",
    hours: "화–일 11:30–20:30 / 월 휴무",
    rating: 4.4,
    ratingCount: "290",
    why: "멜버른에서 평양식 물냉면과 수제 만두를 제대로 먹을 수 있는 몇 안 되는 가게입니다. 사골 육수를 12시간 이상 끓여 내린 냉면 국물은 깔끔하면서도 깊은 맛이 나 여름철 시원하게 즐기기 좋습니다. 한국 직수입 메밀을 사용한 면발의 탄력이 인상적입니다.",
    tip: "만두는 찐만두와 군만두 중 반반 주문이 가능. 1인도 편하게 식사할 수 있는 분위기입니다.",
  },
];

// ─── BRISBANE ─────────────────────────────────────────────────────────────────

export const TOP5_FOOD_BRISBANE: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "써니뱅크 고기집",
    nameEn: "Sunnybank Korean BBQ House",
    address: "Shop 8, 358 McCullough St, Sunnybank QLD 4109",
    phone: "+61 7 3344 8877",
    hours: "매일 11:30–22:30",
    rating: 4.5,
    ratingCount: "610",
    why: "브리즈번 최대 아시안 푸드 허브인 써니뱅크 중심에 자리한 한식 바비큐 전문점으로, 브리즈번 한인 커뮤니티의 사랑방 역할을 합니다. 가성비가 뛰어난 소갈비·삼겹살 세트와 직접 담근 깍두기가 손님들의 재방문을 이끌어 냅니다. 한국어·영어 메뉴가 모두 준비되어 있어 다양한 배경의 손님을 편안하게 맞이합니다.",
    tip: "주차는 써니뱅크 플라자 공영주차장 이용. 금요일 저녁 7시 이후는 대기 예상.",
    website: "sunnybankbbq.com.au",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "웨스트엔드 한식당",
    nameEn: "West End Korean Kitchen",
    address: "5/14 Boundary St, West End QLD 4101",
    phone: "+61 7 3255 6600",
    hours: "화–일 12:00–21:30 / 월 휴무",
    rating: 4.3,
    ratingCount: "340",
    why: "브리즈번의 힙스터 동네 웨스트엔드에서 정갈한 가정식 한상 차림을 내놓는 식당입니다. 된장·시래기·제육볶음 등 집밥 메뉴가 주를 이루어 장기 체류 한인들에게 특히 위안이 되는 공간입니다. 현지인 단골도 많아 언제나 활기차고 따뜻한 분위기입니다.",
    tip: "런치 세트는 A$16부터 시작해 브리즈번 물가에서 상당히 합리적입니다.",
  },
  {
    rank: 3,
    emoji: "🌶️",
    nameKo: "코리안 치킨 브리즈번",
    nameEn: "Korean Fried Chicken Brisbane",
    address: "127 Adelaide St, Brisbane CBD QLD 4000",
    phone: "+61 7 3210 4400",
    hours: "매일 11:00–23:00",
    rating: 4.2,
    ratingCount: "820",
    why: "브리즈번 CBD에서 한국식 후라이드·양념·반반 치킨을 배달·포장·매장 식사로 모두 즐길 수 있어 유학생과 직장인 모두에게 인기입니다. 바삭한 튀김 옷에 달콤 매콤한 양념이 잘 배어 있으며, 치즈볼·떡볶이 사이드 메뉴도 훌륭합니다. 피자와의 조합 세트를 제공해 퀸즐랜드대 학생들 사이에서 야식 1순위로 꼽힙니다.",
    tip: "앱 주문 시 첫 주문 15% 할인 쿠폰 제공. 뼈없는 순살 옵션 선택 가능.",
    website: "kfcbrisbane.com.au",
  },
  {
    rank: 4,
    emoji: "🍱",
    nameKo: "써니뱅크 김밥천국",
    nameEn: "Sunnybank Gimbap Heaven",
    address: "1F, Sunnybank Hills Shoppingtown, 661 Compton Rd, Sunnybank Hills QLD 4109",
    phone: "+61 7 3345 1100",
    hours: "월–토 08:30–20:00 / 일 09:00–18:00",
    rating: 4.3,
    ratingCount: "270",
    why: "한국 어디서나 볼 수 있는 '김밥천국' 스타일의 메뉴를 브리즈번에서 그대로 재현한 곳으로, 김밥·라면·비빔밥을 빠르고 저렴하게 먹을 수 있습니다. 이민 초창기에 익숙한 한국 분식집 분위기가 정착 스트레스를 잠시 잊게 해 줍니다. 아침 일찍 열어 출근 전 간단한 한식 아침 식사를 원하는 분들에게 특히 인기입니다.",
    tip: "계란 김밥과 참치 김밥이 가장 먼저 팔리므로 오전 중 방문 권장.",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "브리즈번 우동·라멘 포차",
    nameEn: "Brisbane Udon & Ramen Pojangmacha",
    address: "22 Fish Lane, South Brisbane QLD 4101",
    phone: "+61 7 3844 2211",
    hours: "화–토 17:00–23:30 / 일·월 휴무",
    rating: 4.4,
    ratingCount: "380",
    why: "사우스 브리즈번 피시 레인의 감성 골목에 자리한 한국식 포차로, 우동·라멘·안주 메뉴와 함께 소주·막걸리를 즐길 수 있습니다. 이자카야 감성에 한국 포장마차 분위기를 더해 현지 호주 청년들도 즐겨 찾는 핫플레이스입니다. 브리즈번 한인 청년들의 주말 밤 첫 번째 약속 장소로 자리 잡고 있습니다.",
    tip: "야외 테이블은 선착순으로 앉을 수 있으며 저녁 7시 이후 분위기가 최고조.",
  },
];

// ─── PERTH ────────────────────────────────────────────────────────────────────

export const TOP5_FOOD_PERTH: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "노스브리지 한우마당",
    nameEn: "Northbridge Hanwoo Korean BBQ",
    address: "Shop 3, 186 William St, Northbridge WA 6003",
    phone: "+61 8 9228 4411",
    hours: "매일 12:00–22:30",
    rating: 4.5,
    ratingCount: "490",
    why: "퍼스 한인 커뮤니티의 중심지인 노스브리지에서 가장 오래된 한국식 바비큐 레스토랑으로, 퍼스 한인들의 경조사 자리를 오랫동안 함께해 왔습니다. 웨스턴 오스트레일리아산 와규를 한국식으로 마리네이드해 구워 내는 독특한 메뉴가 이 집만의 자랑거리입니다. 한국어가 가능한 직원이 항상 있어 처음 퍼스에 정착한 분도 편안하게 방문할 수 있습니다.",
    tip: "점심 특선(A$25 내외 1인 세트)은 예약 없이도 비교적 여유롭게 이용 가능.",
    website: "northbridgehanwoo.com.au",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "캐닝턴 한식 마을",
    nameEn: "Cannington Korean Village",
    address: "4/1420 Albany Hwy, Cannington WA 6107",
    phone: "+61 8 9356 7722",
    hours: "화–일 11:00–21:00 / 월 휴무",
    rating: 4.4,
    ratingCount: "310",
    why: "퍼스 남동쪽 캐닝턴 한인 상가 안에 자리한 가정식 전문점으로, 부대찌개·순두부·고등어조림 등 집에서 먹던 반찬과 국이 거의 다 나옵니다. 퍼스 거주 한인 어머니들이 직접 운영하는 느낌의 소박하고 따뜻한 공간입니다. 밥 양이 넉넉하고 국물이 진해 긴 하루 일을 마친 후 방문하기 딱 좋습니다.",
    tip: "주말에는 순대국밥 조기 품절 가능성이 있으니 점심 시간 전 방문 권장.",
  },
  {
    rank: 3,
    emoji: "🌶️",
    nameKo: "퍼스 치킨&포차",
    nameEn: "Perth Chicken & Pojang",
    address: "68 Lake St, Northbridge WA 6003",
    phone: "+61 8 9227 8833",
    hours: "수–월 16:30–24:00 / 화 휴무",
    rating: 4.3,
    ratingCount: "420",
    why: "퍼스에서 찾아보기 힘든 한국식 야식 문화를 제대로 즐길 수 있는 곳입니다. 바삭한 치킨에 시원한 맥주를 곁들이는 치맥 조합은 퍼스 한인 청년들이 모이는 단골 이유입니다. 포차 스타일의 인테리어와 한국 팝 음악 덕분에 현지 호주인들도 이색 문화 체험 장소로 자주 찾습니다.",
    tip: "수요일은 치킨 주문 시 감자튀김 무료 서비스. 예약 없이 방문하는 경우 바 좌석 활용.",
  },
  {
    rank: 4,
    emoji: "🍱",
    nameKo: "퍼스 한강 도시락",
    nameEn: "Perth Hangang Dosirak",
    address: "Shop 7, 532 Hay St, Perth CBD WA 6000",
    phone: "+61 8 9321 5566",
    hours: "월–금 08:00–17:00 / 주말 휴무",
    rating: 4.2,
    ratingCount: "180",
    why: "퍼스 CBD에서 직장인들을 위한 한식 도시락·점심 세트를 합리적인 가격에 제공하는 곳입니다. 매일 달라지는 반찬 구성과 적당한 양으로 퍼스 한인 직장인들의 평일 점심을 책임지고 있습니다. 정성스럽게 싼 도시락을 먹다 보면 잠깐이나마 한국의 편의점 도시락을 먹던 기억이 떠오릅니다.",
    tip: "전날 오후 5시까지 다음 날 도시락 예약 주문이 가능해 품절 걱정이 없습니다.",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "노스브리지 냉면&설렁탕",
    nameEn: "Northbridge Naengmyeon & Seolleongtang",
    address: "112 Aberdeen St, Northbridge WA 6003",
    phone: "+61 8 9228 9900",
    hours: "화–일 11:30–21:00 / 월 휴무",
    rating: 4.4,
    ratingCount: "240",
    why: "퍼스에서 맑고 깊은 설렁탕 한 그릇을 제대로 먹을 수 있는 귀한 곳입니다. 사골을 하루 종일 고아 낸 뽀얀 국물과 부드러운 수육이 추운 퍼스의 겨울밤을 든든하게 채워 줍니다. 여름에는 시원한 물냉면으로 메뉴를 바꿔 먹는 단골이 많아 사계절 내내 사랑받는 곳입니다.",
    tip: "깍두기 국물을 설렁탕에 조금 넣으면 깊이가 배가됩니다. 국내산 소금과 후추는 테이블에 직접 조절.",
  },
];

// ─── AUCKLAND ─────────────────────────────────────────────────────────────────

export const TOP5_FOOD_AUCKLAND: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "오클랜드 고기나라",
    nameEn: "Auckland Gogi Nara Korean BBQ",
    address: "3/291 New North Rd, Kingsland, Auckland 1021",
    phone: "+64 9 846 3300",
    hours: "매일 12:00–22:30",
    rating: 4.5,
    ratingCount: "730",
    why: "오클랜드 한인 밀집 지역인 뉴노스로드 킹슬랜드에 자리한 한식 바비큐로, 뉴질랜드에서 가장 한국다운 고기집으로 손꼽힙니다. 뉴질랜드산 프리미엄 소고기를 한국 양념으로 숙성시킨 메뉴가 특히 인기가 높고, 셀프 바 형식의 반찬 코너가 풍성합니다. 주일 예배 후 교인들이 단체로 방문하는 교회 단골 식당으로도 유명합니다.",
    tip: "주말 점심 12시~1시 사이가 가장 혼잡. 평일 방문 시 주차도 여유롭고 훨씬 편안합니다.",
    website: "goginara.co.nz",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "헨더슨 한마당",
    nameEn: "Henderson Hanmadang",
    address: "7/10 Alderman Dr, Henderson, Auckland 0610",
    phone: "+64 9 838 5511",
    hours: "화–일 11:00–21:30 / 월 휴무",
    rating: 4.4,
    ratingCount: "350",
    why: "오클랜드 서부 헨더슨 한인 상가에 자리한 가정식 전문점으로, 다양한 찌개와 구이를 합리적인 NZ$ 가격에 제공합니다. 뉴질랜드 물가가 높은 점을 감안했을 때 양과 질 모두 만족스러운 몇 안 되는 곳입니다. 이민 1세대부터 유학생까지 모든 세대가 편하게 드나드는 포근한 식당입니다.",
    tip: "된장찌개+공기밥+반찬 세트가 NZ$17 내외로 오클랜드에서 가성비 최고입니다.",
  },
  {
    rank: 3,
    emoji: "🌶️",
    nameKo: "CBD 코리안 스트리트",
    nameEn: "CBD Korean Street Food",
    address: "Level 1, 21 Queen St, Auckland CBD 1010",
    phone: "+64 9 379 8822",
    hours: "매일 10:00–22:00",
    rating: 4.2,
    ratingCount: "890",
    why: "퀸스트리트 한복판에서 한국 길거리 음식을 즐길 수 있는 오클랜드 최중심 한식 패스트푸드 공간입니다. 핫도그·떡볶이·어묵·호떡 등 K-스트리트 메뉴를 빠르게 즐길 수 있어 오클랜드 시티에서 일하는 한인들의 점심 순위권 장소입니다. 한류에 관심 있는 현지 뉴질랜드 청소년들도 K-드라마에서 본 음식을 직접 체험하려고 줄을 서는 모습이 자주 보입니다.",
    tip: "오후 3시~5시 간식 타임에 호떡과 타피오카 음료 세트가 특가로 제공됩니다.",
    website: "cbdkoreanstreet.co.nz",
  },
  {
    rank: 4,
    emoji: "🍣",
    nameKo: "오클랜드 한일포차",
    nameEn: "Auckland Han-Il Pojangmacha",
    address: "14 O'Connell St, Auckland CBD 1010",
    phone: "+64 9 302 1144",
    hours: "월–토 17:00–24:00 / 일 휴무",
    rating: 4.3,
    ratingCount: "420",
    why: "오클랜드 CBD의 아늑한 골목에 자리한 한일 퓨전 이자카야로, 퇴근 후 동료들과 한잔하기 좋은 뉴질랜드 한인들의 단골 술자리 장소입니다. 소주·막걸리·일본 사케를 모두 갖추고 있으며, 파전·닭발·야키토리가 안주 메뉴로 조화롭게 공존합니다. 뉴질랜드 현지인과 한인이 함께 어울리는 분위기가 자연스럽게 형성되어 있습니다.",
    tip: "금요일 밤은 자리 잡기 어려우니 오픈 시간에 맞춰 도착하는 것이 좋습니다.",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "뉴노스로드 순대국",
    nameEn: "New North Rd Sundaeguk",
    address: "403 New North Rd, Kingsland, Auckland 1021",
    phone: "+64 9 845 7700",
    hours: "월–토 07:00–20:00 / 일 휴무",
    rating: 4.4,
    ratingCount: "260",
    why: "오클랜드에서 아침 7시부터 뜨끈한 순대국밥 한 그릇을 맛볼 수 있는 귀한 식당입니다. 이른 아침 출근 전 해장을 위해 찾는 한인 직장인들로 오전 시간대는 항상 자리가 차 있습니다. 뉴질랜드에서 구하기 힘든 순대와 내장을 직접 손질해 사용한다는 점에서 주인의 정성이 느껴집니다.",
    tip: "국물 농도를 진하게·보통·연하게 선택할 수 있습니다. 고수 추가는 무료.",
  },
];

// ─── SÃO PAULO ────────────────────────────────────────────────────────────────

export const TOP5_FOOD_SAOPAULO: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "리베르다지 한국관",
    nameEn: "Liberdade Korean Gwan",
    address: "Rua Galvão Bueno 83, Liberdade, São Paulo - SP, 01506-000",
    phone: "+55 11 3277 8844",
    hours: "화–일 11:30–15:00, 18:00–22:30 / 월 휴무",
    rating: 4.6,
    ratingCount: "840",
    why: "상파울루 아시아 문화의 중심지 리베르다지에서 수십 년째 운영 중인 한식 명가로, 한국 교민과 브라질 현지인 모두에게 가장 인지도 높은 한국 식당입니다. 숯불 갈비와 비빔밥을 포르투갈어 메뉴로도 완벽하게 안내해 비한인 손님도 편안하게 방문할 수 있습니다. 브라질의 높은 물가 속에서도 합리적인 런치 세트로 꾸준히 사랑받고 있습니다.",
    tip: "점심 '알모소' 세트(갈비+밥+국+반찬)가 평일에만 제공되며 가장 인기 있는 메뉴입니다.",
    website: "coreanorestaurante.com.br",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "봄 헤치루 불고기 하우스",
    nameEn: "Bom Retiro Bulgogi House",
    address: "Rua José Paulino 152, Bom Retiro, São Paulo - SP, 01120-000",
    phone: "+55 11 3361 5500",
    hours: "매일 11:00–22:00",
    rating: 4.4,
    ratingCount: "560",
    why: "한국계 브라질인이 가장 많이 거주하는 봄 헤치루 지역의 대표 한식당으로, 브라질 스타일로 변형된 불고기와 정통 한국 레시피가 공존하는 독특한 메뉴 구성이 특징입니다. 패션 의류 도매상가 밀집 지역이라 점심 시간에는 한인 사업가들로 북적이며 활기찬 분위기를 자랑합니다. 상파울루 한인 타운의 생동감을 가장 잘 느낄 수 있는 공간입니다.",
    tip: "불고기 덮밥 위에 달걀 프라이를 추가하는 것이 현지 단골들의 비밀 주문법입니다.",
  },
  {
    rank: 3,
    emoji: "🍲",
    nameKo: "서울 감자탕 상파울루",
    nameEn: "Seoul Gamjatang São Paulo",
    address: "Rua Tabatinguera 340, Liberdade, São Paulo - SP, 01022-001",
    phone: "+55 11 3105 7722",
    hours: "월–토 11:00–21:30 / 일 11:00–20:00",
    rating: 4.3,
    ratingCount: "390",
    why: "브라질에서 감자탕을 제대로 먹을 수 있는 손꼽히는 곳으로, 상파울루 교민들이 한국이 그리울 때 가장 먼저 찾는 식당입니다. 뼈를 오래 끓여 낸 진한 국물과 부드럽게 떨어지는 뼈 살이 브라질의 더운 날씨에도 마음을 따뜻하게 해 줍니다. 상파울루에 처음 정착해 외로움을 느끼는 이민자들에게 특히 위안이 되는 곳입니다.",
    tip: "인원이 2인 이상이면 냄비 추가 국물 서비스를 받을 수 있으니 요청해 보세요.",
  },
  {
    rank: 4,
    emoji: "🍱",
    nameKo: "K-팝 분식 & 카페",
    nameEn: "K-Pop Bunsik & Cafe",
    address: "Rua Galvão Bueno 371, Liberdade, São Paulo - SP, 01506-001",
    phone: "+55 11 3208 9933",
    hours: "매일 09:00–21:00",
    rating: 4.2,
    ratingCount: "650",
    why: "한류 열풍을 타고 브라질 현지 청소년들에게도 큰 인기를 얻고 있는 K-팝 테마 분식집으로, 떡볶이·김밥·라면과 함께 한국 아이돌 포토카드를 교환하는 공간이 마련되어 있습니다. 한국 음식이 처음인 브라질 친구들과 함께 방문하기 가장 좋은 입문 식당입니다. 상파울루 한인 2세들이 브라질 친구들에게 한국 문화를 자연스럽게 소개하는 다리 역할을 하고 있습니다.",
    tip: "한국 음료 수입품 코너가 있어 한국 편의점 음료를 구입할 수도 있습니다.",
    website: "kpopbunsik.com.br",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "교민 냉면·칼국수",
    nameEn: "Gyomin Naengmyeon & Kalguksu",
    address: "Rua da Glória 230, Liberdade, São Paulo - SP, 01510-000",
    phone: "+55 11 3341 6644",
    hours: "화–일 11:00–20:00 / 월 휴무",
    rating: 4.5,
    ratingCount: "310",
    why: "상파울루 교민 사회에서 '칼국수 맛집'으로 오랫동안 불려 온 면 요리 전문점으로, 남미에서 이 수준의 칼국수를 먹기 어렵다는 평이 자자합니다. 직접 손 반죽해 뽑은 면발의 탄력과 사골 육수의 깊이가 수천 킬로 떨어진 브라질 땅에서도 고향의 맛을 느끼게 해 줍니다. 교민 1세 어르신들부터 유학생까지 세대를 초월해 사랑받는 역사 깊은 공간입니다.",
    tip: "칼국수는 주문 후 면을 반죽하기 때문에 15~20분 기다림이 있지만 충분한 가치가 있습니다.",
  },
];
