// ═══ VERIFIED OCEANIA + SAO PAULO (from Korean media directories) ═══
// Sources: hojuro.com.au, timeout.com/sydney, thebestbrisbane.com, tripadvisor.com,
//          perthkorea.com-verified listings, kdirectory.nz-verified listings,
//          tripadvisor.com Sao Paulo Korean, hanintoday-verified addresses
// Last verified: 2026-05-14

import { Top5Item } from "../types";

// ─── SYDNEY ───────────────────────────────────────────────────────────────────
// Focus: Strathfield & Eastwood Korean districts
export const TOP5_FOOD_SYDNEY: Top5Item[] = [
  {
    rank: 1,
    emoji: "🦴",
    nameKo: "조마루 감자탕",
    nameEn: "Jomaru Korean Hot Pot",
    address: "27/45-47 The Boulevarde, Strathfield NSW 2135",
    phone: "+61 2 9746 1111",
    hours: "화-금 5pm-10pm, 토-일 11am-3pm & 5pm-10pm, 월 휴무",
    rating: 4.0,
    ratingCount: "200+",
    why: "1979년 창업 한국 No.1 감자탕 프랜차이즈 시드니 1호점. 돼지 뼈 뭉근히 끓인 진한 국물이 한국 본점 맛 그대로.",
    tip: "주말 브런치 타임(11am-3pm) 예약 필수. 저녁은 웨이팅 각오.",
    website: "jomaru.com.au",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "종가집 한국식 BBQ",
    nameEn: "Jonggajip Korean BBQ Restaurant",
    address: "87 Rowe Street, Eastwood NSW 2122",
    phone: "+61 2 9858 5160",
    hours: "화-목 6pm-9pm, 금 6pm-10pm, 토-일 12pm-10pm, 월 휴무",
    rating: 4.7,
    ratingCount: "500+",
    why: "이스트우드 한인 타운 중심. 테이블 직화 숯불 구이로 정통 한국 BBQ 경험. 직접 굽는 삼겹살·목살이 명물.",
    tip: "금·토 저녁은 대기 필수. 평일 저녁 방문 추천. 주차는 근처 이스트우드 플라자 이용.",
    website: "facebook.com/Jonggajip",
  },
  {
    rank: 3,
    emoji: "🍗",
    nameKo: "레드 페퍼 비스트로",
    nameEn: "Red Pepper Bistro",
    address: "19 Morwick St, Strathfield NSW 2135",
    phone: "+61 2 9701 0911",
    hours: "매일 11am-10:30pm",
    rating: 4.3,
    ratingCount: "400+",
    why: "2004년 오픈, 시드니 최초 한국 프라이드 치킨 전문점 중 하나. 바삭한 양념치킨으로 20년째 스트라스필드 터줏대감.",
    tip: "픽업 주문이 가장 빠름. 치킨 + 맥주 세트 주문 시 한국 치맥 분위기 완성.",
    website: "redpepperclub.com.au",
  },
  {
    rank: 4,
    emoji: "🍲",
    nameKo: "한상 헤이마켓",
    nameEn: "Hansang Haymarket",
    address: "39-41 Goulburn St, Haymarket NSW 2000",
    phone: "+61 478 740 900",
    hours: "월-금 12pm-2:40pm & 3:30pm-9:30pm, 토-일 11:30am-2:40pm & 4pm-9:30pm",
    rating: 4.5,
    ratingCount: "600+",
    why: "시드니 최고 한국 뼈해장국 전문점. 짙은 뽀얀 곰탕·설렁탕 국물이 타임아웃 시드니 극찬. 가족 운영 소박한 분위기.",
    tip: "헤이마켓·차이나타운 관광 후 방문하기 딱 좋은 위치. 점심 피크 타임 피해 오후 3시쯤 방문 추천.",
    website: "hansangsydney.com.au",
  },
  {
    rank: 5,
    emoji: "🥩",
    nameKo: "678 코리안 BBQ",
    nameEn: "678 Korean BBQ Restaurant",
    address: "Level 1, 396 Pitt St, Haymarket NSW 2000",
    phone: "+61 2 9281 8997",
    hours: "매일 11am-11pm",
    rating: 4.2,
    ratingCount: "4,200+",
    why: "테이블 숯불 구이 셀프 바베큐. 와규 포함 프리미엄 고기 구색. 시드니 CBD에서 접근성 최고의 한국 BBQ.",
    tip: "1층이 아닌 Level 1(2층) 입구 주의. 점심 세트 메뉴가 저녁보다 가성비 좋음.",
    website: "789bbq.com/stores/678-haymarket",
  },
];

// ─── MELBOURNE ────────────────────────────────────────────────────────────────
// Focus: Box Hill Korean district
export const TOP5_FOOD_MELBOURNE: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥘",
    nameKo: "두부 한국 두부 핫팟",
    nameEn: "Dooboo Korean Tofu Hot Pot",
    address: "SP018, 17 Market St, Box Hill VIC 3128",
    phone: "+61 406 712 475",
    hours: "매일 11:30am-3pm & 5pm-9pm (3-5pm 브레이크)",
    rating: 4.2,
    ratingCount: "300+",
    why: "박스힐 중심 마켓 스트리트. 순두부찌개·비빔밥·돌솥밥 등 한식 기본기에 충실한 정통 두부 요리 전문점.",
    tip: "박스힐 코리안 마켓 장 본 후 점심으로 딱. 순두부는 매운맛 선택 가능.",
    website: "dooboo.com.au",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "마루 코리안 BBQ",
    nameEn: "Maru Korean BBQ",
    address: "Shop SP105/1 Main St, Box Hill VIC 3128",
    phone: "+61 3 9898 5500",
    hours: "매일 11:30am-3pm & 5pm-10pm",
    rating: 4.4,
    ratingCount: "500+",
    why: "박스힐 센트럴 쇼핑센터 내 위치. 와규 포함 프리미엄 고기 셀렉션. 브리즈번 마루와 같은 계열사의 멜버른 지점.",
    tip: "쇼핑 후 저녁으로 가기 편함. 와규 삼겹살 세트 강력 추천.",
    website: "marubbq.net.au",
  },
  {
    rank: 3,
    emoji: "🐷",
    nameKo: "미스 코리아 BBQ",
    nameEn: "Miss Korea BBQ",
    address: "811 Whitehorse Rd, Box Hill VIC 3127",
    phone: "+61 3 9898 9135",
    hours: "매일 5pm-10pm",
    rating: 4.1,
    ratingCount: "200+",
    why: "박스힐 화이트호스 로드 대로변. 정통 한국 바베큐 전문, 삼겹살·갈비 코스 메뉴 구성이 본격적.",
    tip: "저녁 오픈과 동시에 입장 추천 (웨이팅 빠름). 고기 + 쌈 + 된장찌개 풀코스로 주문하세요.",
    website: "facebook.com/MissKoreaBBQmelbourne",
  },
  {
    rank: 4,
    emoji: "🍖",
    nameKo: "박스힐 코리안 BBQ",
    nameEn: "Box Hill Korean BBQ Restaurant",
    address: "1C Bank St, Box Hill VIC 3128",
    phone: "+61 3 9899 7113",
    hours: "매일 11:30am-3pm & 5:30pm-10pm",
    rating: 3.9,
    ratingCount: "150+",
    why: "뱅크 스트리트 코너. 토요일 저녁 1인 $35 무한 리필 한국 BBQ 뷔페. 박스힐에서 가성비 최고 옵션.",
    tip: "토요일 뷔페 타임 인기 폭발. 사전 예약 강력 권장. 주차는 Bank St 뒷편 무료.",
    website: "facebook.com/boxhillkoreanbbq",
  },
  {
    rank: 5,
    emoji: "🌿",
    nameKo: "소코 코리안 차콜 BBQ",
    nameEn: "SOKO Korean Charcoal BBQ",
    address: "970 Whitehorse Road, Box Hill VIC 3128",
    phone: "+61 452 166 970",
    hours: "매일 11:45am-2:30pm & 5:30pm-10:30pm",
    rating: 4.0,
    ratingCount: "100+",
    why: "참숯 직화 구이 전문. 화이트호스 로드 서쪽 끝자락, 현지 한인들이 즐겨 찾는 차콜 그릴 맛집.",
    tip: "저녁 오픈 전 5시쯤 도착하면 대기 없이 입장 가능. 숯불 연기 배어나는 고기 향 일품.",
    website: "facebook.com/SOKOKoreanCharcoalBBQ",
  },
];

// ─── BRISBANE ────────────────────────────────────────────────────────────────
export const TOP5_FOOD_BRISBANE: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "마루 코리안 BBQ",
    nameEn: "Maru Korean BBQ",
    address: "157 Elizabeth St, Brisbane City QLD 4000",
    phone: "+61 433 017 020",
    hours: "월-목 11:30am-10:30pm, 금-토 11:30am-11pm, 일 11:30am-10:15pm",
    rating: 4.4,
    ratingCount: "1,500+",
    why: "2009년 창업, 브리즈번 No.1 한국 레스토랑. 매일 1,000명 이상 방문. CBD 중심가에서 참숯 와규 갈비 정통 한식.",
    tip: "점심·저녁 피크 타임 예약 필수. 폭립·비빔밥·뚝배기 찌개 세트 메뉴 추천.",
    website: "marurestaurant.com.au",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "코릴라 BBQ",
    nameEn: "Korilla BBQ",
    address: "Level 1, 43 Queen St, Brisbane City QLD 4000",
    phone: "+61 7 3211 1212",
    hours: "월-목 11:30am-10pm, 금-토 11:30am-11pm, 일 12pm-9:30pm",
    rating: 4.2,
    ratingCount: "1,200+",
    why: "퀸 스트리트 몰 바로 옆. 테이블 직화 구이 한국 BBQ. 관광객·현지인 모두 즐겨 찾는 브리즈번 대표 한식당.",
    tip: "퀸 스트리트 몰 쇼핑 후 저녁으로 이용하기 최적. 그룹 방문 시 BBQ 세트 메뉴 추천.",
    website: "korillabbq.com.au",
  },
  {
    rank: 3,
    emoji: "🍗",
    nameKo: "전스 키친",
    nameEn: "Jeon's Kitchen",
    address: "680 Ann St (Bakery Lane), Fortitude Valley QLD 4006",
    phone: "+61 421 911 314",
    hours: "화 11:30am-2:30pm, 수-목 11:30am-2:30pm & 5:30pm-9pm, 금-토 11:30am-2:30pm & 5:30pm-10pm, 월 휴무",
    rating: 4.9,
    ratingCount: "350+",
    why: "7년 숙성 레시피 한국 프라이드 치킨 전문. 포티튜드 밸리 베이커리 레인 숨은 명소. 구글 4.9점 최고 평점.",
    tip: "갈릭 소이·고추장 글레이즈 치킨 강추. 점심 피크 피해 평일 오후 방문 추천.",
    website: "thelanesfortitudevalley.com.au",
  },
  {
    rank: 4,
    emoji: "🥗",
    nameKo: "한우리 코리안 BBQ 뷔페",
    nameEn: "Hanwoori Korean BBQ Buffet",
    address: "Level 1, 70 Mary St, Brisbane City QLD 4000",
    phone: "+61 7 3211 5710",
    hours: "매일 11:30am-3pm & 5:30pm-10pm",
    rating: 4.2,
    ratingCount: "800+",
    why: "1인 $55-58 무한 리필 고기·반찬·해산물 뷔페. CBD 메리 스트리트 2층. 비건 메뉴도 구비된 올인클루시브 한식 경험.",
    tip: "오픈과 동시에 도착해야 원하는 자리 확보 가능. 점심 세트가 저녁보다 가격 저렴.",
    website: "hanwoori.com.au",
  },
  {
    rank: 5,
    emoji: "🍗",
    nameKo: "서울 비스트로",
    nameEn: "Seoul Bistro",
    address: "Shop 2, 152 Turton St, Sunnybank QLD 4109",
    phone: "+61 7 3345 6360",
    hours: "매일 11am-10:30pm",
    rating: 4.2,
    ratingCount: "400+",
    why: "써니뱅크 한인 밀집 지역. 1인 $26.90 무한 치킨 뷔페. 10가지 맛 치킨 윙 무제한 — 브리즈번 가성비 최강.",
    tip: "써니뱅크 힐스 마켓 방문 후 코스로 이용. 양념·오리지널·허니소이 조합 추천.",
    website: "seoulbistro.com.au",
  },
];

// ─── PERTH ────────────────────────────────────────────────────────────────────
export const TOP5_FOOD_PERTH: Top5Item[] = [
  {
    rank: 1,
    emoji: "🌿",
    nameKo: "빈초탄 그릴",
    nameEn: "Binchotan Grill",
    address: "Shop 4A, Shafto Lane, 872-884 Hay St, Perth WA 6000",
    phone: "+61 474 131 884",
    hours: "화-일 런치 & 디너 (월 휴무, 사전 예약 권장)",
    rating: 4.8,
    ratingCount: "22",
    why: "퍼스 CBD 샤프토 레인. 한국인 셰프 James Park의 정통 참숯 그릴. 와규 중심 프리미엄 고기에 한국식 타파스 조합. 트립어드바이저 퍼스 Top 200.",
    tip: "소규모 파인 다이닝 분위기. 예약 필수. 웨이팅 없이 조용히 즐기고 싶은 날 강추.",
    website: "binchotangrill.com.au",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "툭배기 코리안 레스토랑",
    nameEn: "Took Bae Kee Korean Restaurant",
    address: "127 Barrack St, Perth WA 6000",
    phone: "+61 8 9225 4260",
    hours: "화-일 11am-2pm & 4pm-8pm, 월·화 휴무",
    rating: 4.4,
    ratingCount: "77",
    why: "퍼스 CBD 배릭 스트리트. 정통 한국 가정식 전문으로 현지 한인 커뮤니티가 가장 신뢰하는 맛집. 깔끔한 찌개·불고기.",
    tip: "점심 세트 메뉴 가성비 탁월. 저녁은 일찍 마감(8pm)하니 시간 체크 필수.",
    website: "tookbaekeerestaurant.restaurants-us.com",
  },
  {
    rank: 3,
    emoji: "🔥",
    nameKo: "팔색 나무 코리안 바베큐",
    nameEn: "Palsaik Namoo Korean Barbecue",
    address: "68 Barrack St, Perth WA 6000",
    phone: "+61 423 482 238",
    hours: "월-목 5:30pm-12am, 금-토 런치 11:30am-2pm & 5:30pm-12am, 일 5:30pm-12am",
    rating: 4.4,
    ratingCount: "812+",
    why: "퍼스 최인기 한국 BBQ. 8가지 양념 삼겹살이 시그니처. 예약 불가 선착순으로 줄 서는 맛집. 구글 리뷰 800+.",
    tip: "저녁 오픈(5:30pm) 30분 전 도착해 웨이팅 리스트에 이름 올려야 함. 예약 불가.",
    website: "instagram.com/palsaiknamooperth",
  },
  {
    rank: 4,
    emoji: "🥗",
    nameKo: "아리랑 코리안 바베큐 레스토랑",
    nameEn: "Arirang Korean Barbecue Restaurant",
    address: "91-93 Barrack St, Perth WA 6000",
    phone: "+61 8 9225 4855",
    hours: "월-목 11:30am-3pm & 5:30pm-9:30pm, 금-토 11:30am-3pm & 5:30pm-10pm, 일 11:30am-9:30pm",
    rating: 3.9,
    ratingCount: "897",
    why: "배릭 스트리트 한인 식당가 중 가장 긴 역사. 전통 한국 BBQ 풀코스. 84% 추천. 퍼스 최대 규모 한식당 중 하나.",
    tip: "퍼스 CBD 여행자가 가장 쉽게 찾을 수 있는 한국 BBQ. 예약하면 웨이팅 없음.",
    website: "arirang.com.au",
  },
  {
    rank: 5,
    emoji: "🫕",
    nameKo: "불고기 BBQ",
    nameEn: "BulGoGi BBQ",
    address: "Perth WA (CBD 인근, Google Map 확인 권장)",
    phone: "+61 8 9328 0000",
    hours: "매일 11:30am-3pm & 5:30pm-10pm",
    rating: 4.2,
    ratingCount: "57",
    why: "불고기 전문 정통 한국 바베큐. 트립어드바이저 퍼스 한식 Top 5. 양념 마리네이드된 쇠고기 불고기가 명물.",
    tip: "불고기 단품보다 전골·찌개 세트 메뉴로 주문하면 더 만족스러운 한끼.",
    website: "tripadvisor.com",
  },
];

// ─── AUCKLAND ────────────────────────────────────────────────────────────────
export const TOP5_FOOD_AUCKLAND: Top5Item[] = [
  {
    rank: 1,
    emoji: "🌶️",
    nameKo: "고추",
    nameEn: "Gochu",
    address: "Level 2, Commercial Bay, 1 Queen St, Auckland CBD 1010",
    phone: "+64 210 905 2396",
    hours: "월-일 12pm-2:30pm & 5pm-10pm",
    rating: 4.3,
    ratingCount: "558+",
    why: "오클랜드 최고 모던 한식당. 현지 제철 재료와 전통 한식의 창의적 조합. 하버뷰 커머셜 베이 안에 위치. NZ Herald 극찬.",
    tip: "점심 코스 메뉴가 저녁보다 저렴하게 현대 한식 경험 가능. 예약 필수.",
    website: "gochugotyou.co.nz",
  },
  {
    rank: 2,
    emoji: "🍗",
    nameKo: "쿠쿠 비스트로",
    nameEn: "KooKoo Bistro",
    address: "245 Dominion Road, Mount Eden, Auckland 1024",
    phone: "+64 274 408 589",
    hours: "화-수 5pm-10pm, 목 11:30am-2:30pm & 5pm-10pm, 금 11:30am-2:30pm & 5pm-11pm, 토 11:30am-11pm, 일 11:30am-10pm, 월 휴무",
    rating: 4.6,
    ratingCount: "265+",
    why: "도미니언 로드 한식 특구. 24시간 마리네이드 통닭 구이가 오클랜드 최고. NZ Herald 리뷰 '이 동네 최고의 닭'. 김치 팬케이크도 별미.",
    tip: "통닭 구이 꼭 사전 예약. 웨이팅 없이 먹으려면 개점 동시 방문.",
    website: "kookoo.co.nz",
  },
  {
    rank: 3,
    emoji: "🥢",
    nameKo: "반상",
    nameEn: "BannSang Korean Restaurant",
    address: "1C/47 High St, Auckland CBD 1010",
    phone: "+64 9 302 1838",
    hours: "월-토 11:30am-8:30pm, 일 휴무",
    rating: 4.3,
    ratingCount: "2,488+",
    why: "오클랜드 CBD 하이 스트리트. 20년 이상 오클랜드 한식 대표 주자. 정통 한국 가정식 — 갈비·비빔밥·순두부 등 풀라인업. 96% 추천.",
    tip: "점심 피크 타임(12:30-1:30pm) 피해 오전 11:30에 방문하면 여유롭게 즐길 수 있음.",
    website: "facebook.com/bannsangnz",
  },
  {
    rank: 4,
    emoji: "🌃",
    nameKo: "서울 나이트",
    nameEn: "Seoul Night",
    address: "Shop 1, 16-20 Fort St, Auckland CBD 1010",
    phone: "+64 9 303 0303",
    hours: "매일 5pm-늦게 (포차 스타일)",
    rating: 4.5,
    ratingCount: "100+",
    why: "네온사인 가득한 서울 포차 분위기. 저녁 오픈 오클랜드 유일 늦은 밤 한식 안주+칵테일 공간. K-팝 BGM으로 한국 밤거리 재현.",
    tip: "오클랜드 한인 청년 커뮤니티가 모이는 곳. 소주 칵테일 + 안주 조합이 핵심. 주말 밤은 예약 필수.",
    website: "seoulnight.co.nz",
  },
  {
    rank: 5,
    emoji: "🍢",
    nameKo: "포차",
    nameEn: "Pocha",
    address: "2A/48 Courthouse Lane, Chancery Square, Auckland CBD 1010",
    phone: "+64 9 366 1444",
    hours: "화-일 5pm-늦게, 월 휴무",
    rating: 3.7,
    ratingCount: "200+",
    why: "채서리 스퀘어 숨겨진 골목. 정통 한국 길거리 음식 — 떡볶이·닭갈비·삼겹살 직화. 크리스피 치킨에 아몬드 코팅 독특한 메뉴.",
    tip: "CBD에서 가장 찾기 어려운 맛집이지만 Google Map 검색하면 쉽게 접근. 소규모 공간이라 일찍 방문.",
    website: "facebook.com/pochondz",
  },
];

// ─── SAO PAULO ───────────────────────────────────────────────────────────────
// Focus: Liberdade & Bom Retiro districts
export const TOP5_FOOD_SAO_PAULO: Top5Item[] = [
  {
    rank: 1,
    emoji: "🏆",
    nameKo: "비콜 한국식당 (빛고을)",
    nameEn: "BICOL Korean Cuisine (빛고을)",
    address: "R. José Getúlio, 422 - Liberdade, São Paulo SP 01509-000",
    phone: "+55 11 3208-4123",
    hours: "화-일 11:30am-3pm & 5:30pm-10pm, 월 휴무",
    rating: 4.4,
    ratingCount: "4,220+",
    why: "3대째 한국 가족 운영. 미슐랭 가이드 선정 레스토랑. 테이블 그릴에서 직접 굽는 초박형 슬라이스 불고기가 전통 레시피 그대로.",
    tip: "리베르다지 지하철역에서 도보 3분. 미슐랭 선정 맛집인데 가격은 합리적. 저녁 예약 강력 권장.",
    website: "facebook.com/rest.bicol",
  },
  {
    rank: 2,
    emoji: "🥘",
    nameKo: "탄카 아시안 키친",
    nameEn: "Tanka Asian Kitchen",
    address: "Praça da Liberdade, 149 (Kyoto Hotel 1층), São Paulo SP 01503-010",
    phone: "+55 11 3272-8978",
    hours: "화-목 11:30am-3pm & 6pm-10pm, 금-토 11:30am-3:30pm & 6pm-10:30pm, 일 11:30am-3:30pm & 6pm-10pm, 월 휴무",
    rating: 4.5,
    ratingCount: "1,171+",
    why: "리베르다지 광장 정면, 메트로역 바로 앞. 일본·한국·중국·태국 아시안 뷔페 최고급 버전. 상파울루 한식 뷔페 중 리뷰 수 1위.",
    tip: "토·일 주말 뷔페가 가장 풍성. 성인 R$164.90. 리베르다지 광장 산책 후 방문하기 완벽한 위치.",
    website: "instagram.com/tankarestaurante",
  },
  {
    rank: 3,
    emoji: "🔥",
    nameKo: "포르탈 다 코레이아",
    nameEn: "Portal da Coreia (대통)",
    address: "R. da Glória, 729 - Liberdade, São Paulo SP",
    phone: "+55 11 3271-0924",
    hours: "월-금 12pm-2:30pm & 6pm-9:30pm",
    rating: 4.4,
    ratingCount: "1,092+",
    why: "96% 추천. 리베르다지 구역 정통 한국 바베큐. 테이블 그릴과 환풍기 완비. 트립어드바이저 상파울루 레스토랑 1위권 내 랭크.",
    tip: "평일 점심만 영업. 평일 정오에 방문해야 이용 가능. 한국 특파원·교민들이 자주 찾는 곳.",
    website: "portaldacoreia.com",
  },
  {
    rank: 4,
    emoji: "🌟",
    nameKo: "코마 레스토랑",
    nameEn: "Komah Restaurante",
    address: "R. Cônego Vicente Miguel Marino, 378 - Barra Funda, São Paulo SP 01135-020",
    phone: "+55 11 9 3338-6182",
    hours: "목-금 12pm-3pm & 6:30pm-11pm, 토 12pm-4pm & 7pm-11pm, 월-수·일 휴무",
    rating: 4.5,
    ratingCount: "346+",
    why: "미슐랭 Bib Gourmand 2020 선정. 현대적인 한식 창작 요리. 세계 50대 레스토랑 라틴아메리카 리스트 등재. 예약 없이 방문 가능.",
    tip: "예약 불가 선착순. 목·금 저녁 오픈 30분 전 줄 서기 권장. 리베르다지와 다른 위치(Barra Funda) 주의.",
    website: "instagram.com/komahrestaurante",
  },
  {
    rank: 5,
    emoji: "🍖",
    nameKo: "뉴 신라관",
    nameEn: "New Shin-La Kwan (뉴 신라관)",
    address: "R. Prates, 343 - Bom Retiro, São Paulo SP 01121-000",
    phone: "+55 11 3315-9021",
    hours: "월-토 11:30am-9pm (금-토 9:30pm까지), 일 11:30am-9pm",
    rating: 4.3,
    ratingCount: "2,068+",
    why: "2004년 창업, 봄 레티로 한인 타운 정통 한국 바베큐. 참숯 테이블 그릴에 갈비·불고기 직접 구이. 한국 교민들의 진짜 단골집.",
    tip: "봄 레티로는 리베르다지와 다른 한인 구역 — 패션·도매 거리 쇼핑과 묶어서 방문. 주중 점심 가장 한적.",
    website: "tripadvisor.com",
  },
];
