// ═══ VERIFIED CANADA + MILITARY CITIES (from Korean media directories) ═══
// 조사 출처: cndreams.com, koreatimes.net YP, Yelp, TripAdvisor, 공식 사이트
// 검증일: 2026-05-14

interface Top5Item {
  rank: number;
  emoji: string;
  nameKo: string;
  nameEn: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating?: number;
  ratingCount?: string;
  why: string;
  tip?: string;
  website?: string;
}

// ─── CALGARY, AB ─────────────────────────────────────────────────────────────
// 출처: cndreams.com (구인 공고 + 커뮤니티 게시판), Yelp 2026 업데이트
const TOP5_FOOD_CALGARY: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "한국관",
    nameEn: "Korean Village Restaurant",
    address: "1324 10 Ave SW, Calgary, AB T3C 0J2",
    phone: "(403) 228-1120",
    hours: "월-목 11am-10pm, 금-일 11am-",
    rating: 4.1,
    ratingCount: "260+",
    why: "1991년 개업한 캘거리 최초·최장수 한식당으로, Beltline 한복판에서 30년 넘게 교민 커뮤니티의 구심점이 되어온 곳입니다. 불고기·찌개·돌솥비빔밥 등 정통 한식을 변함없이 제공하며 캘거리 한인 1세대의 추억이 담겨 있습니다. 처음 정착하는 분들이 '한국 온 것 같다'는 말을 가장 많이 하는 집입니다.",
    tip: "평일 점심은 비교적 여유롭지만 금-토 저녁은 예약 권장. 전화 문의는 평일 오후 2-5시",
    website: "koreanvillageyyc.com",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "코릴라 코리안 BBQ",
    nameEn: "Korilla Korean BBQ",
    address: "1410 17 Ave SW, Calgary, AB T2T 5S8",
    phone: "(825) 540-1410",
    hours: "월-목 5pm-11pm, 금-일 12pm-12am/10pm",
    rating: 4.4,
    ratingCount: "300+",
    why: "17번 애비뉴의 핫플레이스로, 테이블 직화구이·루프탑 바·프라이빗 노래방까지 갖춘 캘거리 최고급 K-BBQ 공간입니다. 소갈비·삼겹살 등 프리미엄 육류와 개성 있는 칵테일의 조합이 현지 MZ세대와 교민 2세에게 큰 인기를 끌고 있습니다. cndreams.com에서도 활발히 구인 중인 성장하는 한식 브랜드입니다.",
    tip: "루프탑 좌석은 사전 예약 필수. 금-토 저녁 2시간 전 도착 권장",
    website: "korilla.ca",
  },
  {
    rank: 3,
    emoji: "🍖",
    nameKo: "인사동 코리안 BBQ",
    nameEn: "Insadong Korean BBQ",
    address: "132-920 36 St NE, Calgary, AB T2A 6L8",
    phone: "(587) 353-3273",
    hours: "월-목 11am-10pm, 금 10am-",
    rating: 4.2,
    ratingCount: "66+",
    why: "NE 한인 밀집 쇼핑몰 안에 위치해 장보기와 외식을 한 번에 해결할 수 있는 실용적인 BBQ 맛집입니다. 넓은 좌석과 합리적인 가격으로 가족 모임에 최적이며, 한국 마트와 베이커리가 인접해 정착 초기 원스톱 한인 생활권으로 자리잡은 곳입니다. 교민들이 아이들 데리고 가는 '편한 동네 고기집'으로 손꼽힙니다.",
    tip: "NE 한인 쇼핑몰 주차 무료. T&T 마트와 함께 방문하면 효율적",
    website: "insadong-calgary.com",
  },
  {
    rank: 4,
    emoji: "🌙",
    nameKo: "원웨이 서울 포차",
    nameEn: "Oneway Seoul Pocha",
    address: "1-512 6 St SW, Calgary, AB T2P 1X3",
    phone: "(368) 993-3377",
    hours: "수-일 6pm-LATE, 월-화 휴무",
    rating: 4.3,
    ratingCount: "19+",
    why: "다운타운 중심부의 감성적인 포차 분위기로, 퇴근 후 소주 한 잔과 함께 한국 노포 감성을 느낄 수 있는 캘거리의 새 명소입니다. 다양한 안줏거리와 포장마차 스타일 메뉴가 한국이 그리운 직장인 교민과 유학생들에게 위로가 되는 공간입니다. 저녁에만 운영하므로 늦게 퇴근하는 날 방문하기 좋습니다.",
    tip: "예약 없이 방문 가능하나 주말 저녁은 대기 발생. 현금·카드 모두 가능",
    website: "onewayseoulpocha.ca",
  },
  {
    rank: 5,
    emoji: "🍱",
    nameKo: "한코리아",
    nameEn: "Han Corea",
    address: "6008 Macleod Trl SW #118, Calgary, AB T2H 0K1",
    phone: "(825) 540-1636",
    hours: "월-토 11am-11pm, 일 11am-10pm",
    rating: 4.5,
    ratingCount: "150+",
    why: "간장게장·순대국밥·생선구이 등 소셜미디어에서 화제가 된 정통 한식 메뉴들로 캘거리 한인들의 뜨거운 관심을 받고 있는 곳입니다. Macleod Trail 대형 신규 공간으로 이전 후 더 넓어진 환경에서 더욱 다양한 한국 가정식을 제공합니다. '한국 본토 맛'이라는 평가가 최근 교민 커뮤니티에서 자자합니다.",
    tip: "간장게장은 주말에 품절 빈번. 오전 오픈 시간에 맞춰 방문 권장",
    website: "hancorea.ca",
  },
];

// ─── EDMONTON, AB ─────────────────────────────────────────────────────────────
// 출처: cndreams.com (Edmonton + Calgary 공동 커버), Yelp 2026, 공식 웹사이트
const TOP5_FOOD_EDMONTON: Top5Item[] = [
  {
    rank: 1,
    emoji: "☕",
    nameKo: "한잔",
    nameEn: "Hanjan",
    address: "3735 99 St NW, Edmonton, AB T6E 6J7",
    phone: "(587) 454-3333",
    hours: "화-일 11am-12am, 월 휴무",
    rating: 4.4,
    ratingCount: "136+",
    why: "에드먼턴 1등 한식당으로 손꼽히는 곳으로, 낮에는 스페셜티 커피·가벼운 한식 브런치 카페로, 저녁에는 한국 술·안주 바로 변신하는 이색 다이닝 공간입니다. 정통 한국 가정식 컴포트 푸드를 고급스러운 환경에서 즐길 수 있어 교민 모임과 현지인 데이트 코스로 모두 인기입니다. Hanjan South 지점도 운영 중입니다.",
    tip: "저녁 7시 이후 좌석 경쟁이 심함. OpenTable로 예약 강력 권장",
    website: "hanjan.ca",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "BB2 코리안 BBQ",
    nameEn: "BB2 Korean BBQ House",
    address: "2335 111 St NW, Edmonton, AB",
    phone: "(825) 394-2645",
    hours: "월-금 4:30pm-11pm, 토-일 12pm-11pm",
    rating: 4.3,
    ratingCount: "200+",
    why: "에드먼턴 남쪽의 무한리필 K-BBQ 전문점으로, 신선한 육류와 다양한 반찬 구성이 가성비 면에서 탁월하다는 평을 받고 있습니다. 넓은 공간과 효율적인 테이블 구성으로 대가족·단체 모임에 최적이며, West Edmonton Mall 근처 신규 지점도 오픈 예정입니다. 교민 가족들이 주말 특식으로 즐겨 찾는 곳입니다.",
    tip: "점심 오픈 시간(토-일 12시)에 방문하면 대기 없이 여유롭게 즐길 수 있음",
    website: "bb2kbbq.ca",
  },
  {
    rank: 3,
    emoji: "🍜",
    nameKo: "JMT 코리안 퀴진",
    nameEn: "JMT Korean Cuisine",
    address: "10463 Whyte Ave NW, Edmonton, AB T6E 3R7",
    phone: "(780) 503-2617",
    hours: "월 3pm-10pm, 화-목 12pm-12am, 금 12pm-2am",
    rating: 4.3,
    ratingCount: "180+",
    why: "JMT는 한국어로 '맛있다'는 뜻의 줄임말로, 이름처럼 맛에 자신 있는 한식 레스토랑입니다. Whyte Avenue 대학가에 위치해 유학생·젊은 교민들이 즐겨 찾으며, 다운타운 지점(10335 100 Ave)도 운영 중입니다. 불닭·떡볶이·김치찌개 등 한국 분식류부터 정통 한식까지 폭넓게 다루며 늦은 시간까지 운영합니다.",
    tip: "Whyte Ave 지점은 금요일 새벽 2시까지 운영. 야식이 필요할 때 최고의 선택",
    website: "jmtab.ca",
  },
  {
    rank: 4,
    emoji: "🍲",
    nameKo: "포차 서울",
    nameEn: "Pocha Seoul",
    address: "13-9261 34 Ave, Edmonton, AB T6E 5T5",
    phone: "(780) 465-1996",
    hours: "월-금 11am-10pm",
    rating: 4.1,
    ratingCount: "18+",
    why: "에드먼턴 남쪽의 가족 운영 한식당으로, 한국 가정식에 중화 스타일이 가미된 편안하고 따뜻한 분위기의 동네 맛집입니다. 정착 초기 심리적 위로가 필요한 분들에게 '엄마가 해준 밥 같다'는 평이 자자한 곳으로, 합리적인 가격과 후한 양이 장점입니다. 조용한 남쪽 지역 교민들의 단골 밥집입니다.",
    tip: "테이블 수가 적어 점심 피크 타임에는 대기 발생. 오전 11시 오픈 직후 방문 권장",
    website: "pochaseoul.ca",
  },
  {
    rank: 5,
    emoji: "🎎",
    nameKo: "상 서울 테이블 다이닝",
    nameEn: "Sang - Seoul Table Dining",
    address: "9929 109 St NW, Edmonton, AB T5K 1H6",
    phone: "(780) 244-1976",
    hours: "화-목 5pm-10pm, 금-토 5pm-11pm, 일 5pm-9:30pm, 월 휴무",
    rating: 4.6,
    ratingCount: "100+",
    why: "에드먼턴 최초·유일의 한정식(韓定食) 코스 다이닝 레스토랑으로, 16가지 반찬이 상 위에 가득 차려지는 한국 궁중 식사 경험을 제공합니다. 특별한 날 방문하기 좋은 파인다이닝 급 한식으로, 현지인들도 '한국 전통 문화'를 경험하러 찾는 명소가 되고 있습니다. 단백질(고기·생선)은 숯불에 직화로 구워줍니다.",
    tip: "1인당 $25(반찬 16가지) + 단백질 별도($16-23). 특별한 날 기념식사로 강력 추천",
    website: "sang.restaurant",
  },
];

// ─── OTTAWA, ON ───────────────────────────────────────────────────────────────
// 출처: koreatimes.net YP, cktimes.net, Yelp 2026, Ottawa Chinatown directory
const TOP5_FOOD_OTTAWA: Top5Item[] = [
  {
    rank: 1,
    emoji: "🔥",
    nameKo: "달동네 코리안 BBQ",
    nameEn: "Daldongnae Korean BBQ",
    address: "610 Somerset St W, Ottawa, ON K1R 5K4",
    phone: "(613) 232-8880",
    hours: "일-목 12pm-12am, 금-토 12pm-1am",
    rating: 4.5,
    ratingCount: "242+",
    why: "오타와 차이나타운 중심부에 위치한 Yelp 캐나다 Top 100 레스토랑 선정 K-BBQ 명소입니다. 달동네 특유의 서민적이고 정겨운 분위기 속에서 직화구이를 즐길 수 있어 현지인과 교민 모두에게 인기가 높습니다. 자정까지 운영해 외식 선택지가 적은 오타와에서 늦은 저녁 모임에 최적의 장소입니다.",
    tip: "주말 저녁은 1-2시간 대기 가능. 온라인 예약 또는 오픈 시간에 방문 권장",
    website: "daldongnaebbq.com",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "한국관",
    nameEn: "Korean House",
    address: "785 Somerset St W, Ottawa, ON K1R 6R3",
    phone: "(613) 237-0808",
    hours: "수-토 11:30am-9pm, 일 11:30am-9pm, 화 4pm-9pm, 월 휴무",
    rating: 4.2,
    ratingCount: "49+",
    why: "오타와 Somerset 한인·차이나타운 거리의 정통 한식 레스토랑으로, 부대찌개·갈비탕·잡채 등 전통 가정식 메뉴가 탄탄하게 구성되어 있습니다. 연방정부 공무원과 외교관 등 오타와 특유의 고학력 교민 커뮤니티의 오랜 단골집으로, 정착 초기 '한국 밥 한 그릇'이 그리울 때 찾는 안식처입니다.",
    tip: "점심 특선 메뉴가 가성비 좋음. 주차는 Somerset St 인근 유료주차장 이용",
    website: "koreanhouse.ca",
  },
  {
    rank: 3,
    emoji: "🥘",
    nameKo: "키친 마루",
    nameEn: "Kitchen Maroo",
    address: "281 Kent St, Ottawa, ON K2P 2A3",
    phone: "(613) 234-2945",
    hours: "월-목 11:30am-9pm, 금-토 11:30am-9:30pm, 일 12pm-8pm",
    rating: 4.3,
    ratingCount: "57+",
    why: "한식 퓨전 레스토랑으로 오타와 다운타운 Golden Triangle 지역에 위치해 직장인 점심 수요가 높은 곳입니다. 전통 한식에 현지 식재료를 접목한 창의적인 메뉴 구성이 특징이며, 한국 음식이 처음인 현지 동료를 데려오기에도 부담 없는 환경입니다. 교민들이 비한인 친구들에게 '한식 입문'으로 소개하는 집입니다.",
    tip: "점심 세트 메뉴가 $15 내외로 합리적. 다운타운 도보 접근성 우수",
    website: "kitchenmaroo.ca",
  },
  {
    rank: 4,
    emoji: "🌶️",
    nameKo: "코추",
    nameEn: "Kochu",
    address: "1140 Wellington St W, Ottawa, ON K1Y 2Z3",
    phone: "(613) 729-1959",
    hours: "월-목 12pm-9pm, 금-토 12pm-10pm, 일 12pm-9pm",
    rating: 4.4,
    ratingCount: "120+",
    why: "고추(Kochu)를 이름으로 내세운 만큼 매콤하고 진한 한국 본연의 맛을 추구하는 레스토랑입니다. 한국식 양념 치킨·불고기 김밥·김치볶음밥 등 한국 스트리트 푸드 스타일 메뉴가 주력이며, Wellington 웨스트 동네 특유의 힙한 분위기가 젊은 교민과 현지 MZ세대에게 인기입니다.",
    tip: "치킨 메뉴는 1시간 전 주문 예약 가능. 저녁 피크 시간대 대기 예상",
    website: "kochu.ca",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "테이블 소담",
    nameEn: "Table SODAM",
    address: "1200 Bank St, Ottawa, ON K1S 0W8",
    phone: "(613) 421-1229",
    hours: "화-목 11:30am-2pm·5pm-11pm, 월 휴무",
    rating: 4.4,
    ratingCount: "43+",
    why: "Old Ottawa South의 작고 아늑한 정통 한식 레스토랑으로, 현지인 맛집 블로거들 사이에서도 '오타와 최고 한식'으로 꾸준히 언급되는 숨겨진 보석입니다. 자리가 많지 않아 예약이 필수이며, 오타와 한인 커뮤니티가 특별한 날 선택하는 품격 있는 한식 다이닝 공간입니다.",
    tip: "테이블 수가 매우 적음. 방문 전 반드시 전화 예약 필수. 주차는 Bank St 인근 도로변 이용",
    website: "table85.com",
  },
];

// ─── WINNIPEG, MB ────────────────────────────────────────────────────────────
// 출처: koreatimes.net YP, cktimes.net, Yelp 2026, 공식 웹사이트
const TOP5_FOOD_WINNIPEG: Top5Item[] = [
  {
    rank: 1,
    emoji: "🥩",
    nameKo: "부산 코리아 BBQ",
    nameEn: "Busan Korea BBQ",
    address: "1521 Pembina Hwy #2, Winnipeg, MB R3T 2E4",
    phone: "(204) 284-6618",
    hours: "매일 12pm-10pm",
    rating: 4.5,
    ratingCount: "200+",
    why: "위니펙 최고의 한국 숯불구이 전문점으로, 프리미엄 육류와 최신식 환기 시스템을 갖춘 쾌적한 K-BBQ 환경을 제공합니다. 부산 항구 도시의 진취적인 에너지를 담은 인테리어와 함께, 직화구이의 생동감이 위니펙 교민들의 특별한 날 첫 번째 선택지입니다. 온라인 예약 시스템도 운영합니다.",
    tip: "주말 저녁은 사전 예약 강력 권장. 테이블 부킹은 busankoreabbq.ca에서 가능",
    website: "busankoreabbq.ca",
  },
  {
    rank: 2,
    emoji: "🍲",
    nameKo: "홍두깨",
    nameEn: "Hong Du Kkae",
    address: "2241 Pembina Hwy, Winnipeg, MB R3T 2H1",
    phone: "(204) 219-0025",
    hours: "매일 11:30am-9pm",
    rating: 4.3,
    ratingCount: "143+",
    why: "홍두깨(홍두깨 밀방망이)라는 정겨운 이름처럼, 사골국물 정성 들인 한국 가정식을 내어주는 위니펙 대표 한식당입니다. 김치·깍두기 등 기본 반찬이 무료 제공되며, BBQ부터 찌개·구이까지 다양한 메뉴로 가족 외식에 최적입니다. 배달·포장도 운영해 바쁜 이민 초기에 활용도가 높습니다.",
    tip: "배달·포장 이용 시 DoorDash·SkipTheDishes 앱 사용 가능. 채식 메뉴도 일부 있음",
    website: "hongdukkae.com",
  },
  {
    rank: 3,
    emoji: "🍱",
    nameKo: "키와 코리안 퀴진",
    nameEn: "KIWA Korean Restaurant",
    address: "2077 Pembina Hwy Unit 10, Winnipeg, MB R3T 5J9",
    phone: "(204) 261-3131",
    hours: "월 4pm-9pm, 화-토 12pm-9pm, 일 휴무",
    rating: 4.2,
    ratingCount: "80+",
    why: "Pembina Village 쇼핑센터 안에 자리한 정통 한식 레스토랑으로, 위니펙 한인 커뮤니티의 오랜 단골 식당입니다. 돌솥비빔밥·순두부찌개·냉면 등 정통 한식 메뉴가 탄탄하며, 쇼핑을 마친 후 들르기 편한 위치 덕분에 교민 가족들의 주간 일상 식당으로 자리잡은 곳입니다.",
    tip: "일요일 휴무 확인 필수. 쇼핑센터 무료 주차 이용 가능",
    website: "kiwakoreancuisine.com",
  },
  {
    rank: 4,
    emoji: "🌙",
    nameKo: "리틀 코리아",
    nameEn: "Little Korea",
    address: "519 Ellice Ave, Winnipeg, MB R3B 1Z1",
    phone: "(204) 783-5188",
    hours: "월-토 11am-9pm",
    rating: 4.1,
    ratingCount: "100+",
    why: "위니펙 도심부에서 접근성이 좋은 한식당으로, 소박하지만 진정성 있는 한국 가정식을 합리적인 가격에 제공합니다. 학생·직장인 교민들이 부담 없이 드나드는 동네 밥집 스타일로, 외식 선택지가 제한적인 위니펙에서 꾸준히 사랑받아온 곳입니다.",
    tip: "일요일 휴무. 점심 특선이 가성비 최고. 포장 주문도 가능",
    website: "littlekoreawinnipeg.com",
  },
  {
    rank: 5,
    emoji: "🍣",
    nameKo: "비미 코리안/재패니즈",
    nameEn: "Bimi Korean/Japanese Restaurant",
    address: "1893 Grant Ave, Winnipeg, MB R3N 1Z2",
    phone: "(204) 488-8878",
    hours: "화-일 11:30am-9pm, 월 휴무",
    rating: 4.0,
    ratingCount: "150+",
    why: "한식과 일식을 함께 즐길 수 있는 퓨전 레스토랑으로, 위니펙 남쪽 Grant Ave 주거지역에서 교민 가족들의 오랜 단골집입니다. 김치찌개·불고기 등 한식 메뉴와 함께 초밥·롤 메뉴도 즐길 수 있어 한국 음식이 낯선 배우자나 현지 친구들과 함께 방문하기 좋습니다.",
    tip: "한식·일식 메뉴 모두 준비해 두면 다양한 입맛의 손님을 동반하기 좋음",
    website: "bimiwinnipeg.com",
  },
];

// ─── KILLEEN, TX (Fort Cavazos / 포트 카바조스) ───────────────────────────────
// 출처: koreanct.com (Central Texas Korean Weekly), Yelp 2026, 공식 웹사이트
const TOP5_FOOD_KILLEEN: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍲",
    nameKo: "코리안 키친",
    nameEn: "Korean Kitchen",
    address: "525 E Veterans Memorial Blvd, Killeen, TX 76541",
    phone: "(254) 634-8172",
    hours: "월-토 11am-9pm, 일 휴무",
    rating: 4.3,
    ratingCount: "127+",
    why: "포트 카바조스(구 포트 후드) 군인들과 가족들이 가장 많이 찾는 킬린 대표 한식당으로, Veterans Memorial 대로변에 위치해 기지 출입구에서 접근이 편리합니다. 김치찌개·불고기·비빔밥 등 정통 한식 메뉴와 합리적인 가격이 한국 출신 군인 가족들에게 '고향 맛'을 전해줍니다. 현지 군인 커뮤니티에서 오랫동안 신뢰를 쌓아온 곳입니다.",
    tip: "일요일 휴무. 군복 착용 방문객에게 친절한 편. 포장 주문 가능",
    website: "koreankitchen.netwaiter.com",
  },
  {
    rank: 2,
    emoji: "🥩",
    nameKo: "한강 코리안 BBQ",
    nameEn: "Han Gang Korean BBQ",
    address: "715 W Veterans Memorial Blvd, Killeen, TX 76541",
    phone: "(254) 213-2352",
    hours: "화-토 11am-9pm, 월 휴무",
    rating: 4.2,
    ratingCount: "80+",
    why: "킬린에서 테이블 직화구이를 즐길 수 있는 한강 BBQ로, 삼겹살·소갈비 등 한국 숯불구이 메뉴를 포트 카바조스 근처에서 즐길 수 있습니다. 한국 군대를 다녀온 군인 가족들이 '훈련 끝나고 먹던 고기 맛'이라며 반기는 곳으로, 킬린 한인 커뮤니티의 주말 모임 장소로 인기입니다.",
    tip: "월요일 휴무. 주말 저녁 대기 발생 가능. 예약 또는 일찍 방문 권장",
    website: "hangangkilleen.com",
  },
  {
    rank: 3,
    emoji: "🍜",
    nameKo: "코바 우 레스토랑",
    nameEn: "Koba Woo Restaurant",
    address: "332 E Ave D, Killeen, TX 76541",
    phone: "(254) 526-3065",
    hours: "월-금 11am-8pm, 토-일 휴무",
    rating: 4.5,
    ratingCount: "67+",
    why: "킬린의 숨겨진 보석으로 불리는 정통 한식당으로, 사골국물 오랜 시간 우려낸 갈비탕·도가니탕과 정성스러운 반찬이 '군인 가족에게 한국 할머니 음식'을 연상시킨다는 찬사를 받고 있습니다. 소박하지만 음식 퀄리티에 집중하는 가족 운영 식당으로, 진짜 한식을 원하는 교민 군인 가족에게 최고의 선택입니다.",
    tip: "주말 휴무(토-일). 평일 런치만 운영하므로 시간 확인 필수. 현금 준비 권장",
    website: "koba-woo-restaurant.wheree.com",
  },
  {
    rank: 4,
    emoji: "🔥",
    nameKo: "KPOT 코리안 BBQ & 핫팟",
    nameEn: "KPOT Korean BBQ & Hot Pot",
    address: "1501 E Central Texas Expy, Killeen, TX 76541",
    phone: "(254) 833-8888",
    hours: "월-목 12pm-10:30pm, 금-토 11:30am-11:30pm, 일 11:30am-10:30pm",
    rating: 4.1,
    ratingCount: "148+",
    why: "한국 BBQ와 훠궈(Hot Pot)를 동시에 즐길 수 있는 올인원 다이닝 체인으로, 킬린에서 가장 큰 규모의 한국 음식 공간입니다. 다양한 육류·해산물과 소스 선택지가 풍부해 처음 한식을 경험하는 미국인 동료를 데려오기에도 부담 없으며, 주말 브런치부터 심야까지 운영해 군 일정에 유연하게 맞출 수 있습니다.",
    tip: "무한리필 메뉴 선택 가능. 그룹 방문 시 사전 예약 권장. 주말 오픈 시간에 방문하면 여유로움",
    website: "thekpot.com",
  },
  {
    rank: 5,
    emoji: "🍖",
    nameKo: "삼겹살 코리안 BBQ (O마트 와바 푸드코트)",
    nameEn: "O Mart Wabah Food Court Korean BBQ",
    address: "3126 E Central Texas Expy #100, Killeen, TX 76543",
    phone: "(254) 226-3153",
    hours: "일 12pm-8:30pm, 월-토 11am-9pm",
    rating: 4.2,
    ratingCount: "20+",
    why: "킬린의 한인 마트(O마트) 내 푸드코트에 위치한 한식 코너로, 장보기와 식사를 한 번에 해결할 수 있어 바쁜 군인 가족들에게 실용적입니다. 한국 식료품 구매 후 즉석에서 한식을 즐길 수 있어 '마트 안의 작은 한국'으로 불리며, 킬린 한인 생활권의 중심 허브 역할을 합니다.",
    tip: "한국 마트 쇼핑 후 식사 코스로 활용. 주차 편리. 현금 결제 선호",
    website: "omartusa.com",
  },
];

// ─── FAYETTEVILLE, NC (Fort Liberty / 포트 리버티) ────────────────────────────
// 출처: nckorean.com (NC 한인 포털), Yelp 2026, 공식 웹사이트
const TOP5_FOOD_FAYETTEVILLE: Top5Item[] = [
  {
    rank: 1,
    emoji: "🌶️",
    nameKo: "실라 코리안 레스토랑",
    nameEn: "Shila Korean Restaurant",
    address: "404 Santa Fe Dr Ste 101, Fayetteville, NC 28303",
    phone: "(910) 860-4800",
    hours: "월-금 11am-8pm",
    rating: 4.4,
    ratingCount: "120+",
    why: "페이엣빌에서 가장 오랫동안 교민 군인 가족들의 사랑을 받아온 정통 한식당으로, 신라의 이름처럼 한국 역사의 정통성을 담은 메뉴 구성이 특징입니다. 불고기·갈비·찌개류 등 기본기가 탄탄하며, 포트 리버티 복귀 후 '한국에 온 것 같은 첫 끼니'를 위해 찾는 교민 군인들의 단골 맛집입니다.",
    tip: "주말 미운영. 평일 오전 오픈 직후 방문하면 여유롭게 즐길 수 있음",
    website: "distinctlyfayettevillenc.com/listing/shila-korean-restaurant",
  },
  {
    rank: 2,
    emoji: "🍗",
    nameKo: "코코 CK",
    nameEn: "KOKO CK",
    address: "5173 Bragg Blvd, Fayetteville, NC 28303",
    phone: "(910) 491-2000",
    hours: "화-목 11:30am-8pm, 금-토 11:30am-9pm, 일 12pm-7pm, 월 휴무",
    rating: 4.3,
    ratingCount: "30+",
    why: "한국식 양념 치킨과 정통 한식 메뉴를 전문으로 하는 페이엣빌의 신흥 강자로, 바삭하고 달콤매콤한 치킨이 포트 리버티 군인들 사이에서 입소문이 자자합니다. 적당한 크기의 아늑한 공간에서 한국 치킨 특유의 소스 조합을 즐길 수 있어 비한인 동료를 데려오기에도 좋은 입문 레스토랑입니다.",
    tip: "치킨은 주문 후 조리 시간 약 15-20분. 포장·배달도 가능",
    website: "koko-ck.com",
  },
  {
    rank: 3,
    emoji: "🥩",
    nameKo: "갱남 코리안 BBQ + 핫팟",
    nameEn: "Gangnam Korean BBQ + Hotpot",
    address: "1800 Skibo Rd #300, Fayetteville, NC 28303",
    phone: "(910) 758-8010",
    hours: "월-토 11am-10:30pm, 일 12pm-10pm",
    rating: 4.4,
    ratingCount: "46+",
    why: "페이엣빌 최대 규모 한국 BBQ+핫팟 복합 레스토랑으로, 무한리필 정찰제('Extra Roll, No Extra Toll')가 군인 가족들의 월말 예산 걱정을 덜어줍니다. 대형 테이블로 부대 동기들과의 단체 회식에 최적이며, BBQ와 핫팟을 한 자리에서 즐길 수 있어 다양한 입맛을 가진 그룹에 완벽합니다.",
    tip: "단체 예약 시 사전 연락 권장. 주차장 넓음. 온라인 주문도 가능",
    website: "gangnambbqhotpot.com",
  },
  {
    rank: 4,
    emoji: "🍜",
    nameKo: "이태원 익스프레스",
    nameEn: "E Tae Won Express",
    address: "594 S Reilly Rd, Fayetteville, NC 28314",
    phone: "(910) 867-1077",
    hours: "월 11am-7pm, 화-금 11am-7:30pm, 일 11am-7pm, 토 휴무",
    rating: 4.1,
    ratingCount: "91+",
    why: "서울 이태원의 이름을 딴 이 레스토랑은 3대에 걸친 한국인 요리사가 운영하는 정통 한식 익스프레스 레스토랑입니다. 빠른 서비스와 합리적인 가격으로 군인 점심 수요를 충족하며, 된장찌개·제육볶음 등 한국 일상식을 부담 없이 즐길 수 있어 주중 점심에 자주 찾는 교민 군인들이 많습니다.",
    tip: "토요일 휴무. 점심 피크 타임(12-1시) 대기 발생. 포장 주문 추천",
    website: "menupix.com/fayetteville/restaurants",
  },
  {
    rank: 5,
    emoji: "🍱",
    nameKo: "낙원 코리안 레스토랑",
    nameEn: "Nak Won Korean Restaurant",
    address: "138 N Main St, Spring Lake, NC 28390",
    phone: "(910) 497-8858",
    hours: "수-금 10:30am-8pm, 토-일 10:30am-7pm, 월-화 휴무",
    rating: 4.2,
    ratingCount: "140+",
    why: "페이엣빌 옆 스프링 레이크(Spring Lake)에 위치해 포트 리버티에서 10분 거리의 한식+떡 베이커리 복합 레스토랑입니다. 신선한 떡과 정통 한식을 함께 즐길 수 있는 독특한 조합으로, 명절·기념일에 떡 케이크와 한식 정식을 한 번에 해결하려는 교민 군인 가족들의 특별한 날 선택지입니다.",
    tip: "명절 전후 떡 주문은 1-2일 사전 주문 권장. 월-화 휴무 확인 필수",
    website: "yelp.com/biz/nak-won-korean-restaurant-rice-cake-bakery-spring-lake",
  },
];

// ─── ANCHORAGE, AK ───────────────────────────────────────────────────────────
// 출처: akn907.com (Anchorage Korean News), knewsak907.com, Yelp 2026, 공식 웹사이트
const TOP5_FOOD_ANCHORAGE: Top5Item[] = [
  {
    rank: 1,
    emoji: "🍲",
    nameKo: "원조 코리안 퀴진",
    nameEn: "Wonjo Korean Cuisine",
    address: "515 W Fireweed Ln, Anchorage, AK 99503",
    phone: "(907) 222-2992",
    hours: "화-일 11am-10pm, 월 휴무",
    rating: 4.5,
    ratingCount: "117+",
    why: "앵커리지 한인 커뮤니티에서 가장 신뢰받는 정통 한식 맛집으로, 두부찌개·순두부·육개장 등 진한 국물 요리가 알래스카의 추운 날씨에 완벽히 어울립니다. 원조(原祖)라는 이름처럼 변하지 않는 전통의 맛을 지키며, JBER(합동기지) 군인 가족들이 '한국 집밥'을 그리워할 때 찾는 앵커리지 1번지 한식당입니다.",
    tip: "월요일 휴무. Fireweed 지역 도보 접근 가능. 순두부찌개가 시그니처 메뉴",
    website: "wonjotofu.com",
  },
  {
    rank: 2,
    emoji: "🔥",
    nameKo: "고기 코리안 BBQ",
    nameEn: "Gogi Korean BBQ",
    address: "7780 Old Seward Hwy, Anchorage, AK 99518",
    phone: "(907) 720-4644",
    hours: "매일 11am-10pm",
    rating: 4.4,
    ratingCount: "38+",
    why: "고기(肉)라는 직관적인 이름처럼 한국 직화구이에 집중하는 앵커리지 K-BBQ 전문점입니다. 연중무휴 오전 11시부터 운영해 알래스카 특유의 불규칙한 일정에도 유연하게 방문할 수 있으며, 알래스카 로컬 식재료와 한국 양념의 조합이 독특한 풍미를 만들어냅니다. 군인 가족·한인 교민 모두에게 주말 모임 장소로 사랑받는 곳입니다.",
    tip: "매일 오픈. Old Seward Hwy 주차 편리. 육류 숯불구이가 메인 시그니처",
    website: "gogi907.com",
  },
  {
    rank: 3,
    emoji: "🌮",
    nameKo: "서울 카사",
    nameEn: "Seoul Casa",
    address: "601 E Dimond Blvd Ste 6, Anchorage, AK 99515",
    phone: "(907) 344-3333",
    hours: "월-토 11am-10pm, 일 12pm-9pm",
    rating: 4.5,
    ratingCount: "367+",
    why: "한국·멕시코 퓨전 요리의 독창적인 조합으로 앵커리지에서 가장 많은 리뷰 수를 자랑하는 한식 레스토랑입니다. 불고기 타코·김치 부리또 같은 창의적인 메뉴가 한국 음식이 낯선 현지인 동료에게도 자연스러운 입문이 되어, 비한인 가족·친구를 데려오기에 최적인 장소입니다. 현지인 추천 맛집 리스트에 항상 등장합니다.",
    tip: "단체 방문에도 좌석 여유. 비한인 가족과 방문 시 입문 추천 메뉴 요청 가능",
    website: "seoulcasa907.com",
  },
  {
    rank: 4,
    emoji: "🍖",
    nameKo: "KPUB 코리안 BBQ",
    nameEn: "KPUB Korean BBQ",
    address: "3801 DeBarr Rd, Anchorage, AK 99508",
    phone: "(907) 258-3199",
    hours: "화-일 11am-10pm, 월 휴무",
    rating: 4.3,
    ratingCount: "40+",
    why: "JBER(엘멘도프 기지) 가까운 DeBarr 지역에 위치한 K-BBQ 레스토랑으로, 군인 가족들이 기지에서 15분 내 거리에서 즐길 수 있는 진짜 한국 숯불구이 명소입니다. 다양한 고기 종류와 반찬 구성이 탄탄하며, 주한미군 근무 경험이 있는 군인들이 '한국에서 먹던 그 맛'이라며 반기는 앵커리지 K-BBQ 전문점입니다.",
    tip: "월요일 휴무. JBER 방향에서 DeBarr Rd로 진입. 저녁 예약 권장",
    website: "kpubak.com",
  },
  {
    rank: 5,
    emoji: "🍜",
    nameKo: "진미 코리안 레스토랑",
    nameEn: "Jinmi Korean Restaurant",
    address: "4505 Spenard Rd Suite A, Anchorage, AK 99517",
    phone: "(907) 868-4900",
    hours: "월-금 11:30am-9pm, 토 2pm-8pm, 일 휴무",
    rating: 4.4,
    ratingCount: "106+",
    why: "앵커리지 국제공항에서 5분 거리의 스페나드 지역에 위치해, 한국行 비행기 탑승 전이나 도착 후 첫 한식을 즐기기에 최적의 위치를 자랑합니다. 진미(珍味)라는 이름처럼 귀하고 맛있는 한식을 추구하며, JBER에서 15분 거리로 군인 가족들의 주중 저녁 외식 장소로도 사랑받습니다.",
    tip: "일요일 휴무. 공항 픽업 후 바로 방문 가능한 최고의 위치. 떡볶이·잡채 인기",
    website: "jinmi-korean.com",
  },
];

// ─── 한국 정원 (보너스 — 앵커리지 대형 전통 한식당) ──────────────────────────
// 참고용 추가 정보 (Top5 외)
// Korean Garden | 300 E Dimond Blvd, Anchorage, AK 99515 | (907) 522-5556
// 월·화 휴무, 수-일 11am-9:30pm | 리뷰 97+ | 앵커리지 남쪽 Dimond Center 인근

export {
  TOP5_FOOD_CALGARY,
  TOP5_FOOD_EDMONTON,
  TOP5_FOOD_OTTAWA,
  TOP5_FOOD_WINNIPEG,
  TOP5_FOOD_KILLEEN,
  TOP5_FOOD_FAYETTEVILLE,
  TOP5_FOOD_ANCHORAGE,
};
